.travis.yml
Fix DATA_DIR by using absolute PATH $PWD.
=> use $PWD to refere to DATA_DIR

README.md
=> add basic readme with getting started instructions

casa/OS/Conversion.cc
Use SSE2 _mm_movemask_epi8 (extract most significant bits of each byte)
to implement the bool to bit conversion. This is about 5-10 faster than
the scalar loop.
=> vectorize Conversion::boolToBit

tables/TaQL/RecordGram.cc, tables/TaQL/TableParse.cc, tables/TaQL/TableParse.h
Issue #98
Table shorthand in UDF name; e.g. t1.mscal.ha()
=> Make table.udf possible in TaQL

CMakeLists.txt, casa/CMakeLists.txt, casa/Containers/Allocator.cc, casa/Containers/Allocator.h, casa/Containers/Block.h, casa/Containers/test/tBlock.cc, lattices/LatticeMath/test/tLatticeStatsDataProvider.cc
Hi Ger,
Please review the modification.
I tried to keep compatibilities of the interface but please check.
Kohji
=> Allocator features and making element-initialization controllable.

ms/MSOper/MSMetaData.cc
on behalf of @dmehring, fixes issues introduced in gh-138
=> fix infinity loop and missing check in MSMetaData

images/Images/ImageConcat.tcc
It ignored the axis of concatenation..thus fixed here
=> ImageConcat constructor from aipsio

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc, msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/MSFitsOutput.h
Rebased version of #175 (only commit message changed).
=> CAS-4852: Single field in multifield ms can now be written to msfits file

tables/TaQL/TableParse.cc
=> Fixed creation of output table in case expression is used in select

derivedmscal/DerivedMC/UDFMSCal.cc, derivedmscal/DerivedMC/UDFMSCal.h, ms/MSSel/MSAntennaIndex.cc, ms/MSSel/MSAntennaParse.cc, tables/TaQL/TableParse.cc
Issue #169: Make empty MS selections possible in UDFMSCal
=> Issue #169: Make empty MS selections possible in UDFMSCal

CMakeLists.txt, casa/Arrays/Array.h, casa/Arrays/Array.tcc, casa/Arrays/ArrayBase.cc, casa/Arrays/ArrayBase.h, casa/Arrays/Cube.h, casa/Arrays/Cube.tcc, casa/Arrays/Matrix.h, casa/Arrays/Matrix.tcc, casa/Arrays/Vector.h, casa/Arrays/Vector.tcc, casa/Arrays/test/tArray.cc, casa/CMakeLists.txt, casa/Containers/Allocator.h, casa/Containers/Block.h, casa/Containers/test/tBlock.cc, casa/Utilities/Copy.h, casa/config.h.in
This is the enhancements for casa::Array to handle aligned memory and to skip unnecessary initialization.
It would  be nice if you could merge this pull request as soon as possible.
=> Array align init2

.travis.yml, ms/MSOper/test/tMSMetaData.cc, ms/MeasurementSets/MSAntenna.cc, ms/MeasurementSets/MSDataDescription.cc, ms/MeasurementSets/MSDoppler.cc, ms/MeasurementSets/MSFeed.cc, ms/MeasurementSets/MSField.cc, ms/MeasurementSets/MSFlagCmd.cc, ms/MeasurementSets/MSFreqOffset.cc, ms/MeasurementSets/MSHistory.cc, ms/MeasurementSets/MSObservation.cc, ms/MeasurementSets/MSPointing.cc, ms/MeasurementSets/MSPolarization.cc, ms/MeasurementSets/MSProcessor.cc, ms/MeasurementSets/MSSource.cc, ms/MeasurementSets/MSSpectralWindow.cc, ms/MeasurementSets/MSState.cc, ms/MeasurementSets/MSSysCal.cc, ms/MeasurementSets/MSTable.h, ms/MeasurementSets/MSWeather.cc, ms/MeasurementSets/MeasurementSet.cc, ms/MeasurementSets/test/tMeasurementSet.cc
=> Exceptions thrown in destructors of MS classes

casa/Containers/Allocator.h
=> Fix gcc-4.4.3 warnings in Allocator

ms/MeasurementSets/MSTable.h, ms/MeasurementSets/test/tMeasurementSet.cc
(never mind the name of my branch; it was originally created for some other purpose)
=> Remove validation from MSTable::removeColumn()

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
Add MSMetaData::getReferenceDirection() to get values from FIELD:REFERENCE_DIRECTION with support for ephemeris sources.
=> CAS-7770 add getReferenceDirection() for ephemeris sources

measures/Measures/test/tMeasJPL.cc, tables/TaQL/ExprFuncNode.cc, tables/Tables/PlainTable.cc, tables/Tables/Table.cc, tables/Tables/TableCache.cc, tables/Tables/TableCache.h, tables/Tables/TableKeyword.cc
Issue #217 Make TableCache fully thread-safe
=> Make TableCache fully thread-safe

CMakeLists.txt
Document the possible values for MODULE, fix typo (`USE_FFTW` should be `USE_FFTW3`).
Only edits in comments, so I'll cancel the travis builds.
=> Update CMakeLists.txt documentation

casa/Quanta/QVector.h, casa/Quanta/QVector.tcc, casa/Quanta/test/tQVector.cc, ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
Added new QVector constructor as aid for new MSMetaData code.
Added getChanBWs() and getChanResolutions() to MSMetaData.
=> CAS-7778: MSMetaData should retrieve chan bws and resolutions

casa/Arrays/Array2Math.cc, casa/Arrays/ArrayMath.h, casa/Arrays/ArrayMath.tcc, casa/Arrays/test/tArrayMath.cc, tables/TaQL/ExprAggrNode.cc, tables/TaQL/ExprAggrNodeArray.cc, tables/TaQL/ExprAggrNodeArray.h, tables/TaQL/ExprFuncNode.cc, tables/TaQL/ExprFuncNode.h, tables/TaQL/ExprFuncNodeArray.cc, tables/TaQL/ExprFuncNodeArray.h, tables/TaQL/ExprGroupAggrFuncArray.cc, tables/TaQL/ExprGroupAggrFuncArray.h, tables/TaQL/TableParse.cc, tables/TaQL/TableParse.h, tables/TaQL/UDFBase.cc, tables/apps/taql.cc
Issue #229 Added several TaQL functions and fixed a few small issues
=> Added several TaQL functions

casa/Arrays/ArrayPartMath.tcc, casa/apps/countcode, tables/TaQL/test/CMakeLists.txt, tables/TaQL/test/tTableGramGroupAggr.out, tables/TaQL/test/tTableGramGroupAggr.run, tables/TaQL/test/tTableGramGroupAggrAll.out, tables/TaQL/test/tTableGramGroupAggrAll.run
Issue #231 Found and fixed bug in function products
=> Test all aggregate functions

images/Images/ImageExprParse.cc, images/Images/ImageExprParse.h, images/Images/test/tImageExpr.cc, images/Images/test/tImageExprGram.cc, images/Images/test/tImageExprGram.out
=> Get image names used in image expression

python/Converters/PycExcp.cc, python/Converters/PycExcp.h, python/Converters/test/tConvert.cc, python/Converters/test/tConvert.py
Issue #243
Added exceptions to tests
=> Do not convert a normal exception

tables/DataMan/ISMColumn.cc
=> Use uInt instead of size_t in ISMColumn::fromString

ms/MSOper/MSMetaData.cc
Minor updates to a code (formatting, removal of comments) to respond Julians comments (except the last one) to #259 pull request.
=> Minor format updates to respond Julians comments at #259

cmake/FindFFTW3.cmake
Use FFTW3_INCLUDE_DIR instead of FFTW3_INCLUDE_DIRS
=> Issue #274 Use FFTW3_INCLUDE_DIR instead of FFTW3_INCLUDE_DIRS

images/Images/ImageUtilities2.tcc, images/Images/test/tImageUtilities.cc
added registration of FITS and MIRIAD open image calls to openImage() so they don't have to be sprinkled at various places in higher level classes.
=> Add calls to FITS and miriad registration open functions 

msfits/MSFits/MSFitsOutput.cc
Write receptor angles to uvfits file + minor style changes (eg bracket if blocks, un-cuddle else if blcoks) + remove commented code block.
=> Write FEED::RECEPTOR_ANGLE to AN::POLAA/POLAB

msfits/MSFits/MSFitsInput.cc
AIPS writes zeros to the AN::DISH_DIAMETER table, so fall back to determining diameters the usual way if the AN table values are obviously invalid.
Also a bit of refactoring, used git add -p to add changes in stages to make them easier to review. The functionality change represents about 10 lines of code.
=> CAS-5818 only use AN::DIAMETER values if they are valid

msfits/MSFits/MSFitsInput.cc, msfits/MSFits/MSFitsInput.h
Private field names changes only, no functionality changes.
=> change private field names to have preceding _, style change only

images/Images/FITSImage.cc, images/Images/FITSImage.h
Issue #292 Always return TpFloat as data type
close
=> Always return TpFloat as data type

msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/MSFitsOutput.h
Allow users the option of overwriting an existing file
=> CAS-5492: Add overwrite option to writeFITSFile()

ms/MSOper/MSConcat.cc
in the case of attached ephemerides.
=> Fixed typo which affected  MSConcat::copySource 

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc, msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/MSFitsOutput.h
Ongoing refactoring of MSFitsOutput with help from MSMetaData. No MSFitsOutput functionality changes in this batch.
=> add MSMetaData::getSpwIDs(), continuing refactor of MSFitsOutput

.travis.yml, .travis/before_script.sh, .travis/install.sh
hopefully speeds up the builds a bit
=> cache travis compile result with ccache

tables/apps/CMakeLists.txt, tables/apps/showtableinfo.cc
Rename showtable, because already used in a perl module.
Close #320
=> Issue #320; renamed showtable to showtableinfo

scimath/Functionals/FunctionalProxy.cc
Thanks to @anchitjain1234 who found this bug in casacore/python-casacore#52
=> Fix setmasks in FunctionalProxy

casa/OS/DynLib.cc, casa/OS/DynLib.h, tables/DataMan/DataManager.cc, tables/TaQL/UDFBase.cc
Make messages from dlopen/dlsym part of the exception if loading a shared library fails.
close #313
=> Improve error message in DynLib

casa/Quanta/MVAngle.cc, casa/Quanta/MVDoppler.cc, casa/Quanta/MVEarthMagnetic.cc, casa/Quanta/MVFrequency.cc, casa/Quanta/MVRadialVelocity.cc, casa/Quanta/MVTime.cc, casa/Quanta/Quantum.h, casa/Quanta/Quantum2.cc, casa/Quanta/QuantumHolder.cc, casa/Quanta/UnitMap.cc, casa/Quanta/UnitMap.h, casa/Quanta/UnitVal.cc
Removed static needInit from MV classes
close #342
=> Make MV classes thread-safe

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/MSSummary.h
The first commit on this branch represents the functionality change. This allows one to subclass MSMetaData and override the base class implementation for computing the scan and subscan data structures. eg, subclasses might implement multithreading to compute these structures.
The second commit on this branch changes tabs to spaces in these files, there are no functionality changes in this commit.
=> Cas 8447, two commits

casa/OS/HostInfoLinux.h
cpus not in the affinity group are not usable and should not be counted
for the number of available cpus.
=> respect cpu affinity in cpu number determination

tables/Tables/ReadAsciiTable.cc, tables/apps/CMakeLists.txt, tables/apps/tablefromascii.cc
It is handy to have a program converting a text file to a table. It should support cr-lf as end-of-line
Close #345
=> Added stand-alone program to convert text file to a table

tables/TaQL/TaQLNode.cc, tables/TaQL/TableGram.cc, tables/Tables/TableError.cc, tables/Tables/TableError.h, tables/apps/taql.cc
Highlight erronous command part;
Added -f file to read commands from a file
Close #360
=> Improve the taql application

tables/Tables/TableTrace.cc, tables/Tables/TableTrace.h, tables/Tables/test/CMakeLists.txt, tables/Tables/test/tTableTrace.cc, tables/Tables/test/tTableTrace.out, tables/Tables/test/tTableTrace.run
Made it possible to write output on stdout or stderr
Added Mutex to make it thread-safe in case Tables are opened in multiple threads
Added a test program
=> Improved TableTrace and made test

tables/apps/taql.cc
=> Show taql version

casa/BasicMath/Math.cc, casa/BasicMath/test/tMathNaN.cc
As per #337. Not sure this is portable, there may be problems with old intel compilers ( https://software.intel.com/en-us/forums/intel-c-compiler/topic/297833 )
=> Add std to isinf and isnan, fixes #337

CMakeLists.txt, ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
I had made some methods protected in a previous commit that was merged, but now these can be re-made private since I was able to provide a multi-threaded implementation using openmp in MSMetaData, obviating the need for a derived class.
=> CAS-8447 enable parallel processing using omp

meas/MeasUDF/DirectionEngine.cc, meas/MeasUDF/DirectionEngine.h, meas/MeasUDF/DirectionUDF.cc, meas/MeasUDF/DirectionUDF.h, meas/MeasUDF/Register.cc, meas/MeasUDF/test/tmeas.out, meas/MeasUDF/test/tmeas.run
MeasUDF (used in TaQL) has function DIRCOS to get results as direction cosines
Close #396
=> direction cosine output in MeasUDF

ms/MSOper/MSSummary.cc
Fix bug by switching from while to for loop. Also remove useless verbose parameter. Migrate some calls to use appropriate MSMetaData methods. postfix ++ -> prefix ++ in loops.
=> CAS-6733 fix infinite loop bug

casa/OS/Conversion.cc
On larger machines each thread receives too little data to make the
parallelization worthwhile, on hyperthreaded machines it will even
oversubscribe the machine badly.
Try to avoid this by giving each thread at least 16k of data to work on
and do not start more threads than needed with this restriction.
Also bump minimum data amount for parallelization as its benefit is
marginal with smaller working sets.
=> give each thread minimum amount of work in bitToBool

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/test/tMSMetaData.cc
Also add MSMetaData::getUniqueDataDescIDs()
=> CAS-8523 modify MSSummary::listSpectralAndPolInfo() to be more effecient

coordinates/Coordinates/CoordinateUtil.cc, coordinates/Coordinates/test/tCoordinateUtil.cc, images/Images/ImageStatistics.tcc
Two commits:
1. Fix bug in which min/max pos strings were being determined if min/max pixel location was empty.
2. substitute spaces for tabs for indentation.
=> Cas 8525  Fix bug in which min/max pos strings were being determined if min/max pixel location was empty

msfits/MSFits/MSFitsInput.cc, msfits/MSFits/MSFitsInput.h, msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/test/tMSFITSInput.cc
=> Revert "CAS-8497 implement modifications to uvfits AN read/write rules"

README.md
Adding all the dependency for casacore on **CentOS**.
And all had test properly.
=> Adding dependency on CentOS

msfits/MSFits/MSFitsInput.cc, msfits/MSFits/MSFitsInput.h, msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/test/tMSFITSInput.cc
=> Revert "Revert "CAS-8497 implement modifications to uvfits AN read/write rules""

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
Also  	Place test for getScansForSpw() in its own block in tMSMetaData.
=> Cas 8731  	Implemented MSMetaData::getSpwToScansMap()

fits/FITS/FITSHistoryUtil.cc
=> CAS-8736 Change priority of log message from SEVERE to DEBUG1

msfits/MSFits/MSFitsOutput.cc
is delegated completely to MSFitsOutputAstron
=> CAS-8743 remove WSRT specific code, since writing of WSRT MSes

tables/TaQL/TableParse.cc, tables/TaQL/TableParse.h, tables/TaQL/test/tTableGram.out, tables/TaQL/test/tTableGram.run
Added extra test on table sizes.
close #448
=> Check if projection table sizes match

casa/OS/HostInfoLinux.h
You usually want to know the available memory that can be used when
using these functions but it returns all memory of a machine instead.
This causes problems when a process is resource limited via cgroups.
Update the function to consider the cgroup limits when returning its
results.
Currently only supports v1 cgroups, but currently there are no
standard distributions using v2 yet.
Currently hardcodes common cgroup mount point, technically one has to
search the location in the mount list.
It might be useful to change it to use libcgroup/cgget to be more
generic but the current layout works for ubuntu/debian/fedora/el7.
Closes gh-446
=> consider cgroup limits for memory in HostInfo

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
Import FITS-IDI WEATHER tables and store the information from those tables in an MS WEATHER table. Tested using a VLBA data set that includes a WEATHER table.  Also tested using EVN data that doesn't have weather information.
=> Import FITS-IDI WEATHER tables

ms/MSOper/MSConcat.cc
SPW IDs of the feed entries were not reindexed if necessary.
See CAS-8799.
In principle a simple fix.
=> Fixed bug in handling of the feeds of "moved antennas".

ms/MSOper/MSConcat.cc, ms/MSOper/MSConcat.h
... after copyField in MSConcat to avoid wrong source ids when
fields were merged.
=> For CAS-8801: Added a consolidation stage for the SOURCE table

fits/FITS/hdu.tcc
The blanked value loop did not use the loop counter in the condition.
Minimize scope of counter variables to avoid this type of mistake.
=> Fix wrong loop condition and minimize scope

casa/OS/HostInfoLinux.h
while not enforced by linux, clusters still often use this setting to
convey the limits to the application.
=> consider resource limits for available memory

scimath/Mathematics/InterpolateArray1D.tcc, scimath/Mathematics/test/tInterpolateArray1D.cc
Fixed nearestNeigbour interpolation to properly handle an abscissa sorted in
descending order. (George Moellenbrock)
=> Interpolate1D fix

CMakeLists.txt
Should not affect any other CasaCore client projects.
=> Pushing in mods (again) for CASA's use of casacore namespace.

casa/CMakeLists.txt
A CMakeLists.txt modification from Kumar.
=> Include JsonOut.tcc in the CMakeLists.txt

fits/FITS/BinTable.cc, images/Images/test/tImageUtilities.cc, ms/MSOper/test/tMSMetaData.cc, msfits/MSFits/test/tMSFITSInput.cc, msfits/MSFits/test/tMSFITSOutput.cc
Fix leak in FITS::BinaryTable::fullTable and some minor ones in tests.
=> Fix some memory leaks

python/Converters/PycArrayComCC.h
=> outcommented assert on pyarray_isaligned

tables/Tables/TableProxy.cc
=> Better to use a reference to be sure copy-on-write is not used

tables/TaQL/ExprFuncNodeArray.cc
Added casacore:: to pow function
Close #546
=> Ambiguity in using pow function

CMakeLists.txt
Add an option to use ccache if available.
=> Add and option to use ccache

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
and added associated unit test to tMSMetaData
=> CAS-9477 Implement getSourceTimes() to get SOURCE.TIME column

tables/TaQL/ExprFuncNodeArray.cc, tables/TaQL/test/tTableGram.out, tables/TaQL/test/tTableGram.run
Now adding missing axes and mirroring all axes correctly.
Close #561
=> Fixed transpose in TaQL python style

derivedmscal/DerivedMC/DerivedColumn.cc, derivedmscal/DerivedMC/MSCalEngine.cc, derivedmscal/DerivedMC/MSCalEngine.h, derivedmscal/DerivedMC/Register.cc, derivedmscal/DerivedMC/UDFMSCal.cc, derivedmscal/DerivedMC/UDFMSCal.h
The TaQL UDF mscal has been extended with functions to calculate the apparent UVW coordinates or the delays (in seconds) for the telescopes of a baseline.
Close #562
=> Added functions delay and uvwapp to mscal

tables/TaQL/test/tTableGramAlttab.out, tables/TaQL/test/tTableGramAlttab.run, tables/TaQL/test/tTableGramCretab.out, tables/TaQL/test/tTableGramCretab.run
Issue #541 Replaced little endian by an endian where needed
=> Make TableGramCre/Alttab succeed on big endian machines

tables/DataMan/BaseMappedArrayEngine.tcc, tables/DataMan/DataManAccessor.cc, tables/DataMan/DataManager.cc, tables/DataMan/ForwardCol.cc, tables/DataMan/ForwardColRow.cc, tables/DataMan/ISMIndColumn.cc, tables/DataMan/MSMBase.cc, tables/DataMan/MSMColumn.cc, tables/DataMan/MSMIndColumn.cc, tables/DataMan/SSMBase.cc, tables/DataMan/SSMBase.h, tables/DataMan/SSMColumn.cc, tables/DataMan/SSMDirColumn.cc, tables/DataMan/SSMIndColumn.cc, tables/DataMan/SSMIndStringColumn.cc, tables/DataMan/SSMIndex.cc, tables/DataMan/SSMIndex.h, tables/DataMan/StArrayFile.cc, tables/DataMan/StManAipsIO.cc, tables/DataMan/StManColumn.cc, tables/DataMan/TSMCube.cc, tables/DataMan/TSMCubeMMap.cc, tables/DataMan/TSMDataColumn.cc, tables/DataMan/TSMFile.cc, tables/DataMan/TSMIdColumn.cc, tables/DataMan/TiledStMan.cc, tables/DataMan/VirtArrCol.tcc, tables/DataMan/VirtualTaQLColumn.cc, tables/Tables.h, tables/Tables/Table.h
Improved many messages in the DataMan classes to make clear for which column and/or row  the exception was thrown.
close #560
=> Improved DataMan error messages

ms/MSSel/MSSelection.cc, ms/MSSel/MSSpwGram.cc, ms/MSSel/MSSpwIndex.cc, ms/MSSel/test/tMSSelection.out, ms/MSSel/test/tMSSelection.run
Bug fixes in 
- MSSelection::getChanFreqList 
-MSSpwIndex::convertToChannelIndex
Some cleanup in MSSpwGram.cc
Updated tMSSelection.{out,run}
=> Bug fixes + test update

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
Needed for CASA statwt2 requirement.
=> CAS-10101 implement MSMetaData::getIntervalStatistics()

ms/MeasurementSets/MSRange.cc
Restored line of code from comment for field MSS::ROWS
=> CAS-8050 bugfix for MSRange::range "rows"

scimath/Mathematics/ChauvenetCriterionStatistics.tcc, scimath/Mathematics/ClassicalStatistics.h, scimath/Mathematics/ClassicalStatistics.tcc, scimath/Mathematics/FitToHalfStatistics.h, scimath/Mathematics/FitToHalfStatistics.tcc, scimath/Mathematics/StatisticsAlgorithm.h, scimath/Mathematics/StatisticsAlgorithm.tcc, scimath/Mathematics/test/tChauvenetCriterionStatistics.cc
Also move StatisticsAlgorithm::setDataProvider() implementation from .h to .tcc
=> CASA-10103. Fix Chauvenet bug. Remove _clearData(), use reset() instead

ms/MSSel/MSFieldIndex.cc
The bug this fixes adversely affected the time for field-selection with MSes with a large FIELD sub-table (100s of rows).
=> Cas 10143: Fix for inefficient access of FIELD sub-table columns

scimath/Mathematics/Interpolate2D.cc, scimath/Mathematics/Interpolate2D.h, scimath/Mathematics/test/CMakeLists.txt, scimath/Mathematics/test/tInterpolate2D.cc
Thanks to @mattwhiting for suggesting the fix in `scimath/Mathematics/Interpolate2D.cc`
=> Interpolate2d tests, improvement, fixes #587

lattices/LatticeMath/LatticeStatistics.h, lattices/LatticeMath/LatticeStatistics.tcc, scimath/CMakeLists.txt, scimath/Mathematics/StatisticsAlgorithm.tcc, scimath/Mathematics/StatisticsAlgorithmFactory.h, scimath/Mathematics/StatisticsAlgorithmFactory.tcc, scimath/Mathematics/test/CMakeLists.txt, scimath/Mathematics/test/tStatisticsAlgorithmFactory.cc
which provides common way to configure and create StatisticAlgorithm objects.
Create unit test suite for StatisticsAlgorithmFactory
Modify LatticeStatistics to use StatisticsAlgorithmFactory
include GenSort in StatisticsAlgorithm.tcc (due to compile issue)
Modify relevant CMakeLists.txt files appropriately.
=> Cas 10016 create configuration class StatisticsAlgorithmFactory

msfits/MSFits/FitsIDItoMS.h
And fix a typo elsewhere in the documentation while I'm there.
=> Document the new correlat parameter of the FitsIDItoMS1 class

ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h, ms/MeasurementSets/test/tMSIter.cc, ms/MeasurementSets/test/tMSIter.out, tables/Tables/BaseTabIter.cc, tables/Tables/BaseTabIter.h, tables/Tables/TableIter.cc, tables/Tables/TableIter.h
Complete implementation of MSIter copy assignment operator and new clone() method, with supporting changes to TableIterator and BaseTableIterator.
=> Complete copy assignment for MSIter

msfits/MSFits/FitsIDItoMS.cc
FITS-IDI files from the SMA have scalar TSYS_1/2 columns instead of
array columns as required by the FITS-IDI standard.  Interpret these
as a single value that applies to all bands like we already do for
POLAA/B in the ANTENNA table.
=> CAS-10543 Add workaround for SMA SYSTEM_TEMPERATURE table

ms/MSSel/MSSelection.cc, ms/MSSel/MSTimeGram.yy, ms/MSSel/MSTimeParse.cc, ms/MSSel/MSTimeParse.h, ms/MSSel/test/tMSSelection.out, ms/MSSel/test/tMSSelection.run
Something went wrong with git rebase in PR #629; I've rebased the relevant commits here.
=> Cas 10142tjd

scimath/Mathematics/ZScoreCalculator.cc, scimath/Mathematics/ZScoreCalculator.h
Also reformat files changing tabs to spaces
=> CAS-10767 make ZScoreCalculator::getMaxZScore() thread safe

casa/HDF5/HDF5Object.h
A little error crept in with #648. No idea why the tests passed (it gave a build error when building on my mac).
=> Add missing namespace

ms/apps/CMakeLists.txt, ms/apps/readms.cc, ms/apps/writems.cc, tables/Tables/StorageOption.h
writems creates one or more MSs and fills them. It also creates a MultiMS.
readms reads one or more MSs (or a MultiMS) using various access patterns. In this first version only sequential access is implemented.
=> Added programs writems and readms for MSv3 tests

ms/apps/writems.cc
PR653 broke the build on EL6. These changes fixed the imminent issues and the unit tests passed as well (on EL6).
=> Fix namespace and omp pragma

scimath/Mathematics/ChauvenetCriterionStatistics.h, scimath/Mathematics/ClassicalStatistics.h, scimath/Mathematics/ClassicalStatistics.tcc, scimath/Mathematics/ConstrainedRangeStatistics.h, scimath/Mathematics/ConstrainedRangeStatistics.tcc, scimath/Mathematics/HingesFencesStatistics.h, scimath/Mathematics/HingesFencesStatistics.tcc, scimath/Mathematics/StatisticsAlgorithm.h, scimath/Mathematics/StatisticsAlgorithm.tcc
Also vector -> std::vector to play nice with eclipse.
=> Cas 10906 circumvent binning accounting issue by changing the bin sizes up

casa/IO/LockFile.cc, ms/apps/readms.cc, ms/apps/writems.cc, tables/TaQL/RecordGram.cc, tables/TaQL/RecordGram.h, tables/TaQL/RecordGram.ll, tables/TaQL/test/tRecordGram.cc, tables/Tables/TableIter.h, tables/Tables/test/tTableIter.cc, tables/Tables/test/tTableIter.out
writems and readms have been extended with various options to do all kind of tests.
Some convenience functions have been added to RecordGram to evaluate an expression.
While doing this, some comments in Casacore header files have been improved.
It also revealed a little bug in RecordGram.ll which has been fixed.
=> Improved writems and readms, fixed little bug and improved some comments

casa/OS/OMP.cc, casa/OS/OMP.h, ms/apps/readms.cc, ms/apps/writems.cc
readms and writems did not use the OpenMP functionality correctly.
Furthermore, OMP.h has been extended with a few more functions.
Dave Mehringer will review it after which it can be committed.
=> correct openmp in read/writems; extended OMP.h

lattices/LatticeMath/LatticeStatistics.tcc, lattices/LatticeMath/test/tLatticeStatistics.cc
also squash compiler warning when openmp not used
=> CAS-10938 bug fix to check that chunk size does not exceed limit

lattices/LatticeMath/LatticeStatistics.tcc, scimath/StatsFramework/ChauvenetCriterionStatistics.tcc, scimath/StatsFramework/ClassicalStatistics.tcc
somewhat smarter determination of number of bins in LatticsStatistics
redo iterative increase in bins in ClassicalStats to use irrational factor slightly greater than unity
=> CAS-10947 Chauvenet bugfix which prevented convergence on >4Gpix images

scimath/CMakeLists.txt, scimath/StatsFramework/ClassicalStatistics.h, scimath/StatsFramework/ClassicalStatistics.tcc, scimath/StatsFramework/ConstrainedRangeStatistics.h, scimath/StatsFramework/ConstrainedRangeStatistics.tcc, scimath/StatsFramework/FitToHalfStatistics.h, scimath/StatsFramework/FitToHalfStatistics.tcc, scimath/StatsFramework/StatisticsAlgorithm.h, scimath/StatsFramework/StatisticsAlgorithm.tcc, scimath/StatsFramework/StatisticsDataset.h, scimath/StatsFramework/StatisticsDataset.tcc, scimath/StatsFramework/StatisticsTypes.h, scimath/StatsFramework/StatisticsUtilities.h, scimath/StatsFramework/StatisticsUtilities.tcc
Also various refactors including moving static methods from StatisticsAlgorithm et al to StatisticsUtilities.
=> Cas 11028 Create StatisticsDataset to encapsulate data specific code

scimath/StatsFramework/ClassicalStatistics.h, scimath/StatsFramework/ClassicalStatistics.tcc, scimath/StatsFramework/FitToHalfStatistics.tcc, scimath/StatsFramework/StatisticsDataset.h, scimath/StatsFramework/StatisticsDataset.tcc
…taset
from ClassicalStatistics to StatisticsDataset
Also, bundle data chunk-specific fields into a single struct and reduce number of necessary fields by using PtrHolders to indicate if mask, weights, and ranges are set to make it easier to pass them to and return them from methods.
=> CAS-11049 accounting-specific methods/fields 

tables/TaQL/TaQLNode.cc, tables/TaQL/TaQLNodeDer.cc, tables/TaQL/TaQLNodeDer.h, tables/TaQL/TaQLNodeHandler.cc, tables/TaQL/TaQLNodeHandler.h, tables/TaQL/TaQLShow.cc, tables/TaQL/TaQLShow.h, tables/TaQL/TableGram.ll, tables/TaQL/TableGram.yy, tables/TaQL/TableParse.cc, tables/TaQL/TableParse.h, tables/TaQL/test/tTaQLNode.cc, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run, tables/TaQL/test/tTableGram.cc, tables/TaQL/test/tTableGram.out, tables/TaQL/test/tTableGram.run, tables/apps/taql.cc
- Added the WITH clause to make it easily possible to use temporary tables in a query
- Fixed a small parse issue for the SHOW command
- Added quite some help info to TaQLShow
=> Added WITH clause to TaQL and fixed a small parsing issue

ms/apps/readms.cc
readms had a few minor issues making it throw an exception in some cases.
- incorrect itercols used for 2nd iteration
- reading past EOF if no iteration was used with a selection
- incorrect reading of tile shape if DATA column was not read
=> Fixed a few minor readms issues

lattices/LatticeMath/LatticeApply.tcc
if done in constructors, all Arrays will reference the same array, which will screw things up for multiple output lattices.
=> Cas 11195 need to initialize vectors with copies of arrays 

images/Images/ImageFITS2Converter.cc
… which was introduced long ago for no good reason.
=> Cosmetic change to ImageFITS2Converter to remove empty card from FITS header

scimath/Mathematics/Interpolate2D.cc, scimath/Mathematics/Interpolate2D.h, scimath/Mathematics/test/tInterpolate2D.cc
real and imaginary parts independently
=> CAS-11375 implement interp method for complex values, treat

doxygen.cfg
Remove reference to non-existing custom casacore.css
[skip ci] Fixes #316
=> [Doc] Fix doxygen build

coordinates/Coordinates/DirectionCoordinate.cc, coordinates/Coordinates/DirectionCoordinate.h, coordinates/Coordinates/test/tDirectionCoordinate.cc
* improve precision of angle returned and update tests accordingly
* avoid over the pole offsets
* improve API documentation
=> DirectionCoordinate::convert() mods

.travis.yml, .travis/before_script.sh, CMakeLists.txt
=> Force C++11 support

scimath/CMakeLists.txt, scimath/StatsFramework/BiweightStatistics.h, scimath/StatsFramework/BiweightStatistics.tcc, scimath/StatsFramework/ClassicalQuantileComputer.h, scimath/StatsFramework/ClassicalQuantileComputer.tcc, scimath/StatsFramework/ClassicalStatistics.h, scimath/StatsFramework/ClassicalStatistics.tcc, scimath/StatsFramework/ConstrainedRangeQuantileComputer.h, scimath/StatsFramework/ConstrainedRangeQuantileComputer.tcc, scimath/StatsFramework/ConstrainedRangeStatistics.h, scimath/StatsFramework/ConstrainedRangeStatistics.tcc, scimath/StatsFramework/FitToHalfStatistics.h, scimath/StatsFramework/FitToHalfStatistics.tcc, scimath/StatsFramework/HingesFencesQuantileComputer.h, scimath/StatsFramework/HingesFencesQuantileComputer.tcc, scimath/StatsFramework/StatisticsAlgorithm.h, scimath/StatsFramework/StatisticsAlgorithm.tcc, scimath/StatsFramework/StatisticsUtilities.h, scimath/StatsFramework/StatisticsUtilities.tcc, scimath/StatsFramework/StatsHistogram.h, scimath/StatsFramework/StatsHistogram.tcc, scimath/StatsFramework/test/tClassicalStatistics.cc
* change type of nBins uInt64 -> uInt (shouldn't need more than 2e9 bins, ever!)
* add C++11 features
* add useful typedefs
=> Cas 11504 bug fix improved bin accounting for quantile computations

ms/MSOper/MSConcat.cc, ms/MSOper/MSConcat.h
Similar to what PR #701 did for SYSCAL tables. Tested using a small VLBA data set that Walter Brisken provided.
=> Concatenate WEATHER tables

casa/Containers/RecordDescRep.cc, tables/TaQL/TaQLShow.cc, tables/Tables/ReadAsciiTable.cc
=> Fixed compiler warnings and typo

casa/OS/HostInfoLinux.h
Fix https://github.com/casacore/casacore/issues/542
=> Fix too small int type for memory on 32 bit

tables/DataMan/ISMBase.cc, tables/DataMan/SSMBase.cc, tables/DataMan/TiledStMan.cc, tables/TaQL/test/tTableGramAlttab.out, tables/TaQL/test/tTableGramCretab.out, tables/Tables/TableProxy.cc, tables/Tables/TableProxy.h, tables/Tables/test/tTableCopy.out
=> Harmonized get/setProperties

measures/apps/measuresdata/measuresdata.cc
Fix for casacore/casacore/issues/537
=> Fix JPL ephemerides download (DE200, DE405)

lattices/LatticeMath/LatticeApply.tcc
﻿Use ssize_t and std::min
Close #823
=> Fixed compile error in LatticeApply

build-tools/CMakeLists.txt, build-tools/casacore_floatcheck, build-tools/update_measures, casa/apps/CMakeLists.txt, casa/apps/countcode, casa/apps/plotmemory, casa/apps/watchmemory, python/Converters/test/tConvert.py
All python scripts have been changed to run well in both python 2 and 3.
A few scripts are not installed anymore as they are not needed and eases the Debian packaging.
close #829
=> Support python3 in all python scripts

msfits/MSFits/FitsIDItoMS.cc
Skip digital corrections and scaling for baselines with stations that
didn't use 2-level or 4-level sampling.  Only affects data correlated
with DiFX as these corrections are not applied for other correlators.
Addresses CAS-12092.
=> Fix reading FITS-IDI with data sampled at more than 2 bits.

tables/DataMan/Adios2StMan.cc, tables/DataMan/Adios2StMan.h, tables/Tables/BaseTable.cc
Somehow a MPI_Comm_rank call is missing in BaseTable.cc which causes all ranks not knowing what itself is. 
@rtobar This should fix the error you have seen from writing multiple mpi processes
=> fixed MPI and Adios2StMan bugs

casa/IO/LockFile.cc, tables/DataMan/Adios2StMan.cc, tables/Tables/ConcatTable.cc, tables/Tables/PlainTable.cc
PR #835 mentioned that tMSSelection failed. This issue has been fixed.
Furthermore, a memory leak in Adios2StMan was detected which has been fixed.
=> Make sure lock file is read if NoLocking is used

ms/MSOper/MSConcat.cc
=> Added missing feature in copyWeather in MSConcat (don't reindex ant ids==-1)

casa/Containers/RecordInterface.cc, casa/Containers/RecordInterface.h, casa/Containers/RecordRep.cc, casa/Containers/test/tRecord.cc, casa/Containers/test/tRecord.out, python/Converters.h, python/Converters/PycValueHolder.cc, python/Converters/test/tConvert.out, python/Converters/test/tConvert.py, scimath/Functionals/FunctionHolder.tcc, tables/Tables/TableProxy.cc
Do not treat PyLong as TpInt for Python3
Close #911
=> Always use TpInt64 for PyLong

tables/apps/showtablelock.cc
showtablelock has been extended to show verbose informatio; it lists all fields stored in the .lock file of a table.
This is done to aid in a CASA problem. It is also generally useful.
=> Added -v to showtablelock

ms/MSOper/MSMetaData.cc, ms/MSOper/test/tMSMetaData.cc
update tests
C++11 upgrades and reformatting
=> Cas 12592 update WVR SPW algorithm

msfits/MSFits/MSFitsOutput.cc
The inverse of what was addressed in pull request #946
=> Correctly write out Nasmyth mount types

casa/BasicMath/Math.h
=> Removed obsolete abs functions (issue #947)

ms/MSOper/MSConcat.cc, ms/MSOper/MSConcat.h
... and reindex the Main table references to it.
=> Added code to MSConcat to properly merge the MS PROCESSOR table

images/Images/ImageRegrid.tcc
This PR contains only the WCS related changes from #949.
=> Steve ord/image regrid wcsmany

derivedmscal/DerivedMC/test/tUDFMSCal.cc, derivedmscal/DerivedMC/test/tUDFMSCal.out, tables/TaQL/UDFBase.cc
UDF library synonyms now also work fine for statically linked programs.
close #1030
=> fix UDF library synonym issue

msfits/MSFits/MSFitsOutput.cc
which is optional according to the MS spec
=> CAS-11514 fix bug that required SOUrCE::REST_FREQUENCY column

ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h
The containers Vector and Block used size_t for nelements() since more than 5 years ago. 
MSIter now properly supports size_t as the type for container sizes.
=> Update the support for 64bits containers sizes.

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
=> Add support for importing FITS-IDI GAIN_CURVE tables

casa/Utilities/Regex.cc, casa/Utilities/test/tRegex_1.cc, casa/Utilities/test/tRegex_1.out
=> Fix matching empty strings

ms/MSOper/MSConcat.cc, ms/MSOper/MSConcat.h
Adjusting ANTENNA_ID and SPECTRAL_WINDOW_ID numbers when appropriate.
=> Merge GAIN_CURVE tables.

msfits/MSFits/FitsIDItoMS.cc
When only a single band is present, certain columns become scalar.
Handle this in the code and warn about this if we it is unexpected.
While there, suppress a similar warning for the SYSTEM_TEMPERATURE
table when there is only one band.
=> Handle FITS-IDI GAIN_CURVE tables for a single band

tables/Tables/BaseTable.cc
When updating table.dat file because table has changed, write before to a temporary file and the do an atomic renaming. Otherwise, the update of table.dat is done with open() flag O_TRUNC, which effectively empties the file for a small time window. 
If a second process tries to open the table exactly during that small time window then it fails (#1077).
Note a couple of additional remarks:
- The fix is done at the BaseTable level, in the function that writes the table.dat file. The fix is in two functions: writeStart() and writeEnd(). Those functions take a AipsIO& ios which is assumed to be the same object in both calls. This is the case for all the uses of writeStart/writeEnd in PlainTable, ConcatTable and RefTable.
- This fixes the code snippet that I posted in #1077. That code snippet …
=> Avoid race condition when a process updates table.dat

measures/Measures/MCFrame.cc, measures/Measures/MeasFrame.cc, measures/Measures/MeasFrame.h
=> Simplify MeasFrame

tables/Dysco/aftimeblockencoder.cc, tables/Dysco/aftimeblockencoder.h, tables/Dysco/bytepacker.h, tables/Dysco/dyscodatacolumn.cc, tables/Dysco/dyscodatacolumn.h, tables/Dysco/dyscostman.cc, tables/Dysco/dyscostman.h, tables/Dysco/dyscostmancol.h, tables/Dysco/dyscostmanerror.h, tables/Dysco/dyscoweightcolumn.cc, tables/Dysco/dyscoweightcolumn.h, tables/Dysco/header.h, tables/Dysco/rftimeblockencoder.cc, tables/Dysco/rftimeblockencoder.h, tables/Dysco/rowtimeblockencoder.cc, tables/Dysco/rowtimeblockencoder.h, tables/Dysco/serializable.h, tables/Dysco/stochasticencoder.cc, tables/Dysco/stochasticencoder.h, tables/Dysco/tests/runtests.cc, tables/Dysco/tests/testbytepacking.cc, tables/Dysco/tests/testdyscostman.cc, tables/Dysco/tests/testtimeblockencoder.cc, tables/Dysco/threadeddyscocolumn.cc, tables/Dysco/threadeddyscocolumn.h, tables/Dysco/threadgroup.h, tables/Dysco/timeblockbuffer.h, tables/Dysco/timeblockencoder.h, tables/Dysco/weightblockencoder.h, tables/Dysco/weightencoder.h
This fixes https://github.com/aroffringa/dysco/issues/21
=> Replace dysco files with those from the dysco repos after fixing some bugs

tables/Tables.h
=> Add a reference to DyscoStMan in the tables documentation

tables/Tables.h
=> Add a reference to Adios2StMan in the tables documentation

ms/MeasurementSets/MeasurementSet.cc, ms/MeasurementSets/test/tMeasurementSet.cc
The MS copy constructor and assignment now test for a null MS object.
Close #1135
=> Fix copy of null MS

tables/TaQL/TaQLNode.cc, tables/TaQL/TaQLNodeDer.cc, tables/TaQL/TaQLNodeDer.h, tables/TaQL/TaQLNodeHandler.cc, tables/TaQL/TaQLNodeHandler.h, tables/TaQL/TaQLNodeRep.h, tables/TaQL/TaQLNodeVisitor.h, tables/TaQL/TableGram.ll, tables/TaQL/TableGram.yy, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run, tables/apps/taql.cc
This is the second part of the issue #1143 changes.
It contains the changes in the TaQL grammar and the 1st stage parsing. The actual implementation of the new commands is part of another PR.
=> Changes in TaQL grammar for new commands

casa/HDF5/test/tHDF5.cc, casa/IO/FiledesIO.cc, casa/Quanta.h, casa/Quanta/QMath.h, casa/Quanta/Unit.h, doxygen.cfg, meas/MeasUDF/Register.cc, measures/Measures.h, python/Converters.h, scimath/Functionals.h, tables/Dysco/dyscostman.h, tables/Dysco/dyscostmancol.h, tables/Dysco/stochasticencoder.h, tables/Dysco/threadeddyscocolumn.h, tables/Tables.h
Various doxygen warnings are fixed to improve the documentation.
Furthermore, some user messages are extended to be more clear.
=> Improve documentation

measures/apps/measuresdata/measuresdata-update, measures/apps/measuresdata/measuresdata.cc
Work done by Arno Schoenmakers
=> Move back to maia.usno.navy.mil for measures data

docker/ubuntu1804_clang.docker, docker/ubuntu1804_gcc.docker, docker/ubuntu2004_clang.docker, docker/ubuntu2004_gcc.docker
Also combine docker RUN commands and use all cores for make.
=> Remove dependency on kernsuite image

casa/CMakeLists.txt, images/CMakeLists.txt, ms/CMakeLists.txt, tables/CMakeLists.txt
Bison version >= 3.0 requires different command parameters (-Dapi.prefix instead of -p)
Close #1191
=> Support newer bison versions

casa/Exceptions/Error2.cc
=> Use overloading to detect strerror variant

CMakeLists.txt, casa/OS/CanonicalDataConversion.h, casa/OS/IBMConversion.cc, casa/OS/IBMDataConversion.h, casa/OS/LECanonicalDataConversion.h, casa/OS/RawDataConversion.h, casa/OS/VAXDataConversion.h, casa/OS/test/tCanonicalConversion.cc, casa/OS/test/tLECanonicalConversion.cc, casa/OS/test/tVAXConversion.cc, casa/Quanta/UnitDim.cc, casa/Quanta/UnitDim.h, casa/test/tTypes.cc, python/Converters/PycArrayComCC.h
Support systems where 'char' is unsigned.
Should fix #1193
=> AST-882 Fix ARM GCC-12 build

ms/MSOper/MSConcat.cc, ms/MSOper/MSConcat.h, msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
This implements the new VLBI sub-table presented in issue #1165, including concatenation of the tables when MeasurementSets with such tables are concatenated.
=> Import FITS-IDI PHASE-CAL tables

tables/TaQL/ExprFuncNode.cc, tables/TaQL/ExprFuncNodeArray.cc, tables/TaQL/test/tExprNode.cc
It was detected that a few TaQL function for complex values were not implemented.
=> Add missing TaQL function implementartions

meas/MeasUDF/MeasEngine.tcc
It was not checked if colNode!=0
Close #1266
=> Fix bug; colNode can be 0

tables/TaQL/TableParseUtil.cc, tables/TaQL/test/tTableGram.out, tables/TaQL/test/tTableGram.run
=> Fix use of .. in TaQL table names

tables/DataMan/MSMDirColumn.h, tables/DataMan/MSMIndColumn.h, tables/Tables/PlainTable.cc
=> Fix a few small clang/clang-tidy warnings

casa/IO/MultiFile.cc, casa/IO/MultiHDF5.cc, ms/MeasurementSets/MSIter.cc, tables/Tables/ConcatRows.cc
While working on changing the data types, a few more DebugAssert problems appeared.
Two files gave a build warning, two others resulted in a test failure.
=> Fix a few more DebugAssert build/test problems

tables/Tables/PlainTable.cc
=> Fix double delete in PlainTable::syncTable

casa/IO/MultiFile.cc, derivedmscal/DerivedMC/UDFMSCal.cc, derivedmscal/DerivedMC/UDFMSCal.h, ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/NewMSSimulator.cc, ms/MSOper/NewMSSimulator.h, ms/MSOper/test/tNewMSSimulator.cc, ms/MSSel/MSAntennaParse.cc, ms/MSSel/MSAntennaParse.h, ms/MSSel/MSFeedParse.cc, ms/MSSel/MSFeedParse.h, ms/MSSel/MSSelection.cc, ms/MSSel/MSSpwParse.cc, ms/MSSel/MSSpwParse.h, ms/MSSel/MSStateParse.cc, ms/MSSel/MSStateParse.h, ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h, ms/MeasurementSets/MSTable.h, ms/apps/readms.cc, ms/apps/writems.cc
It also uses std::make_shared where possible.
=> Replace CountedPtr by std::shared_ptr in ms classes

tables/DataMan/TSMCubeBuff.cc, tables/DataMan/TSMCubeBuff.h, tables/DataMan/TiledStMan.cc
Also the code has been modernized a bit.
=> Fix build warning in tables/DataMan

tables/Dysco/uvector.h
Fixes the problem reported in #1312 reported by @sjperkins.
=> Fix a typedef in Dysco

.github/workflows/osx.yml, cmake/FindHDF5.cmake
What it says on the tin. It supersedes #1327.
=> Update macOS runners to macos-12

casa/Utilities/Regex.h
Here is the PR with the fixed forward declaration.
=> Commented out the forward declaration of conflicting structs

tables/Dysco/tests/testdyscostman.cc
=> Add missing include in test

msfits/MSFits/MSFitsOutput.cc
Check the present units and if they are RAD/S, convert to DEG/DAY, otherwise write the values as they are and give warning if the original units were not DEG/DAY.
=> correct proper motion unit conversion in MSFitsOutput.cc

tables/AlternateMans/test/CMakeLists.txt, tables/AlternateMans/test/tBitPacking.cc, tables/AlternateMans/test/tColumnarFile.cc, tables/CMakeLists.txt
This PR merges towards the stokes-storage-manager branch and is part of several PRs that together will add this stman. The work is split in several PRs to allow easier reviewing.
This adds tests for https://github.com/casacore/casacore/pull/1380.
=> Add tests for the columnar file classes

tables/AlternateMans/test/tBitPacking.cc, tables/AlternateMans/test/tColumnarFile.cc
=> Add Stokes I stman edge case test (as suggested by review)

casa/Arrays/IPosition.cc, casa/Arrays/test/tIPosition.cc
=> Fix the IPosition std::vector<ll> constructor

casa/Utilities/DataType.h, tables/AlternateMans/StokesIStMan.cc, tables/AlternateMans/StokesIStMan.h, tables/AlternateMans/StokesIStManColumn.h, tables/CMakeLists.txt, tables/DataMan/DataManager.cc, tables/Dysco/CMakeLists.txt
Part of the Stokes I stman changes.
=> Add the Stokes I storage manager classes

casa/Utilities/DataType.h, tables/AlternateMans/BitPacking.h, tables/AlternateMans/BufferedColumnarFile.h, tables/AlternateMans/RowBasedFile.h, tables/AlternateMans/SimpleColumnarFile.h, tables/AlternateMans/StokesIStMan.cc, tables/AlternateMans/StokesIStMan.h, tables/AlternateMans/StokesIStManColumn.h, tables/AlternateMans/test/CMakeLists.txt, tables/AlternateMans/test/tBitPacking.cc, tables/AlternateMans/test/tColumnarFile.cc, tables/CMakeLists.txt, tables/DataMan/DataManager.cc, tables/Dysco/CMakeLists.txt
This is the main branch for a Stokes I stman. PRs #1380 , #1381 , #1382 and #1383 merge towards this branch. Once all those PRs are merged and this branch is fully functional, it will be merged to master.
=> Stokes I storage manager

tables/AlternateMans/UvwStMan.cc, tables/AlternateMans/UvwStMan.h, tables/AlternateMans/UvwStManColumn.h, tables/CMakeLists.txt, tables/DataMan/DataManager.cc
One a standard LINC-processed 20-channel LOFAR ms, this saves 9%. Together with flag "Stokes I" compression, the total savings are 11%.
=> Add a UvwStMan for compressing UVW values

ms/MSOper/MSDerivedValues.cc, msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/MSFitsInput.cc, msfits/MSFits/MSFitsOutput.cc
Added support for Beam-Waveguide mounts as discussed in https://arxiv.org/abs/2210.13381
=> added support for beam-waveguide mount

measures/apps/measuresdata/cronjobs.txt, measures/apps/measuresdata/distribute_measures.sh, measures/apps/measuresdata/iers.cron, measures/apps/measuresdata/measuresdata.docker
These files are running the daily update of "WSRT_Measures.ztar" at ASTRON. Copied into the repository for reference.
=> Add cronjobs for measures update
