casa/Utilities/GenSort.tcc
It is poor style to modify the thread count in a library and not restore
it on exit.
Instead use the num_threads attribute of the pragma to set the number.
=> don't set global thread number in gensort

casa/Utilities/GenSort.tcc
gnu openmp will always start a full group of threads regardless of loop
iteration count. So e.g. on a 16 core machine two threads are working
and the rest will wait in the barrier which is a spinlock with approx
3ms spin time.
When the machine is oversubscribed this causes massive slowdowns as the
threads holding the logs need to be scheduled before the parallel block
can end.
To avoid this issue only attempt parallization when there is enough work
to do for the two threads. Alternatively one could also limit the number
of threads to min(2, OMP_NUM_THREADS) or implement more efficient omp task
based parallization which has much smaller spincounts in the
barriers.
=> only parallelize quicksort when there is significant work to do

casa/Utilities/GenSort.tcc
Even with the previously applied limit there one can still see
measurable performance degradations due to the poor parallization of the
quicksort.
Try to reduce them some more by increasing the threshold and reducing
the worker group to the 2 threads the code is currently using.
This should remove the overhead due to the barrier.
=> put a larger limit on the sort parallelization and limit worker group to 2

tables/DataMan/TSMCube.cc, tables/DataMan/TSMCube.h
Previously whenver the TSMCube cube object needed to evict a tile from
cache and add a new one it would write the target tile, if needed, and
then deallocate it; then a new tile was allocated and filled.  This
mod caches a tile whenver it is deallocated and allows the allocation
logic to use that cached tile rather than allocated a brand new one.
This approach reduces the amount of allocation which can become
significant when tiles are large (and they are likely to get larger in
HPC applications).
Ran the various tests named tTiled* using valgrind and fixed the one
potential error that was introduced.  Valgrind reports the writing of
unitialized storage but these errors predate this mod.
=> Cube Tile Reuse

python/Converters/PycArray.cc, python/Converters/PycArrayComCC.h, python/Converters/PycArrayNP.cc, python/Converters/PycBasicData.cc
Direct access to members of numpy structures is deprecated.
Remove the structure access with the associated access functions which
exist since at least numpy 1.1.
=> Remove use of deprecated numpy API

CMakeLists.txt
I added CMAKE_INSTALL_NAME_DIR in CMakeLists.txt as this is needed for OS X builds of CASA.
=> Adding CMAKE_INSTALL_NAME_DIR in CMakeLists.txt

CMakeLists.txt
When using cmake 3.x you get warnings, see below. Since this is science we want to be compatible with every obsolete, outdated, old fashion, antiquated and engrained cmake version imaginable, so I think best solution is to keep the 'old behavior'.
first warning:
```
CMake Warning (dev) at measures/fortran/sofa/CMakeLists.txt:5 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.
The following variable(s) would be set to empty:
PROJECT_VERSION
PROJECT_VERSION_MAJOR
PROJECT_VERSION_MINOR
PROJECT_VERSION_PATCH
```
second warning:
```
Warning:Policy CMP0054 is not set: Only interpret if() arguments as variables or keywords
when …
```
=> remove warnings with cmake 3+

ms/MSOper/MSMetaData.cc
Allow an empty STATE subtable in MSMetaData (for LOFAR MSs)
=> Allow an empty STATE subtable in MSMetaData (for LOFAR MSs) (fix issue #140)

derivedmscal/DerivedMC/test/tUDFMSCal.run
Added tUDFMSCal.run to set LD_LIBRARY_PATH correctly
=> Issue #148: set LD_LIBRARY_PATH for tUDFMSCal

cmake/FindCFITSIO.cmake, cmake/FindWCSLIB.cmake
Fix issue #147, where CMake's `find_package_handle_standard_args` behaves differently before cmake 2.8.3. 
If you have such an old cmake, then the wcslib and cfitsio versions will not be checked (which was the behavior before 9bbb01c)
=> Compatibility with cmake <2.8.3

casa/CMakeLists.txt
The file was introduced in gh-132 but it was forgotten to install it.
=> Install Allocator.h needed by public Block.h

casa/version.h, tables/Tables/ArrayColumn.h, tables/Tables/ArrayColumn.tcc, tables/Tables/test/tArrayColumnCellSlices.cc
Forgot to add the putColumnCells that corresponds to the getColumnCells
of the earlier pull request.  I didn't find out until I built against
CASA that I was missing it.
Includes bump of patch level to 2.0.3.
=> Follow-on PR to #121 (Column Cell Slice Access)

casa/Quanta/Quantum.h, casa/Quanta/Quantum.tcc
A very tiny change was not merged from the original CASA/casacore
codebase.  This fixes that omission.
=> QuantumUpgrade (missing from CASA-->CC merge)

casa/BasicSL/Complex.h, casa/Quanta/QMath.h, casa/Utilities/CountedPtr.h
Mavericks (10.9) clang:
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
This needs to be included in the __APPLE_CC__ version detection.
=> OSX 10.9 clang fix

casa/BasicSL/Complex.h, casa/Quanta/QMath.h, casa/Utilities/CountedPtr.h
Reverts casacore/casacore#163 as this seems to cause a segfault.
=> Revert "OSX 10.9 clang fix"

casa/aipsdef.h, casa/aipsenv.h, casa/math.h, ms/MeasurementSets/MSTable.tcc
Changed versioned gcc checks that are destined to break to generic
unversioned ones.
May break some builds with gcc2 but that should not exist anymore in any
useful environment.
=> allow build with gcc 5

.travis.yml
With this webhook, reports of the travis builds are published to the casacore gitter channel. Gitter is a sort of 'developer chat room', you can visit at https://gitter.im/casacore/casacore
=> Travis: add Gitter webhook

.travis.yml, travis-deps.sh
Running travis in a container supposedly makes it quicker. However, you cannot be root in a container. So the test now installs into a user directory instead of using `sudo make install` which installed into `/usr/local` or something.
The OSX build does not use containers, but this build ignores the flag `sudo: false` in `.travis.yml` (thank Travis support for helping out).
=> Use travis container based setup

casa/aipsenv.h
AIPS_HAVE_CXX11 denotes c++11 support or newer. This is usually better
because c++ standards are usually souce level backward compatible so a
minimum version check is more future proof.
=> add better c++11 macro

casa/OS/CanonicalConversion.h, casa/OS/LECanonicalConversion.h
Most architectures have dedicated byteswap instructions but the code is
written so the compiler does not detect the swap.
Use intrinsics or use more compiler friendly code to archive better code
generation.
=> optimize byteswap implementation

casa/OS/CanonicalConversion.h, casa/OS/LECanonicalConversion.h
Remove alignment checks by using memcpy function which is alignment
safe.
A decent compiler optimizes them away on architectures with unaligned
access.
Also explicitly mark all literals unsigned and long long to avoid
implicit conversion issues.
=> cleanup byteswap code

ms/MeasurementSets/MSTable.h
The validation call inside removeColumn is counterproductive for the same reasons
as it was in renameColumn. Working on modifications of a table setup may have invalid
intermediate states. The validation has to be called explicitly by the programmer at
the right moment.
=> Removed validation from removeColumn for same reasons as for renameColumn

casa/Arrays/Array.h, casa/Arrays/Array.tcc, casa/Arrays/ArrayBase.cc, casa/Arrays/ArrayBase.h, casa/Arrays/Cube.h, casa/Arrays/Matrix.h, casa/Arrays/Vector.h, casa/Arrays/test/tArray.cc, casa/Containers/Block.h
To improve the performance of resize without ArrayInitPolicy parameter, the behavior of the resize becomes inconsistent.
=> make initialization behavior of array::resize without ArrayInitPolicy parameter inconsistent.

casa/Arrays/Array.h, casa/Arrays/Array_tmpl.cc, casa/Arrays/Vector.h, casa/Arrays/Vector_tmpl.cc, casa/CMakeLists.txt, casa/Containers/Block.h, casa/Containers/Block_tmpl.cc, msfits/MSFits/MSFitsInput.cc, tables/CMakeLists.txt, tables/Tables/ArrColDesc.h, tables/Tables/ArrColDesc_tmpl.cc, tables/Tables/ArrayColumn.h, tables/Tables/ArrayColumn_tmpl.cc, tables/Tables/ScaColDesc.h, tables/Tables/ScaColDesc_tmpl.cc, tables/Tables/ScalarColumn.h, tables/Tables/ScalarColumn_tmpl.cc
The explicit instantiation of often used template types reduces the build time and library sizes considerably.
=> Add explicit template instantiation to reduce build time and library sizes

coordinates/Coordinates/Spectral2Coordinate.cc
For CAS-7327: The conversion methods should better report problems like NaN velocities or zero frequencies. Also set_error should be used.
=> Improved error messaging in SpectralCoordinate.

ms/MSOper/MSMetaData.cc, ms/MSOper/test/tMSMetaData.cc
This is a small change to fulfill Ger's request that the actual net sideband values be stored an returned, rather than using Todd Hunter's algorithm which causes -1 or 1 to be stored and returned, no matter what the actual values might be.
=> CAS-7523, store the true sideband value for getNetSideBands()

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h
In the case of the MS having no intents, a segfault would occur in _getFieldsAndIntentsMaps(). This submissions fixes that by returning immediately if that condition is met.
=> CAS-7837 account for case of no intents, so segfault doesn't occur

ms/MSOper/MSKeys.cc, ms/MSOper/MSKeys.h, ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
added SourceKey struct to MSKeys
added getRestFrequencies() and getTransitions() to MSMetaData along with private method for retrieving and storing data from SOURCE table.
Replaced CountedPtr with SHARED_PTR in MSMetaData, since that's what we are moving toward.
Replaced a couple of instances of "brute force" code with uses to Measures columns.
=> CAS-7637 add getRestFrequencies() and getTransitions() to MSMetaData

casa/Quanta/Unit.cc
Small allocations are very expensive with glibc, if they are performed
often it can be very worthwhile to replace them with stack based
buffers.
Unit::check is a function which can be called very often by unoptimized
code. To reduce the impact of this avoid the heap allocation for small
strings.
=> Avoid heap allocations for small Unit strings

coordinates/Coordinates/DirectionCoordinate.cc, coordinates/Coordinates/FITSCoordinateUtil.cc, coordinates/Coordinates/Projection.cc
The LON ref val must be forced to zero.
Also improved warning messaging for GLS projection conversion to SFL.
Related CASA ticket: CAS-7759 .
=> Special treatment for SFL projection when reference values are set.

images/Images/ImageUtilities2.tcc
Upon certain failure modes of opening an image, a memory leak would occur and a table would be left open upon an exception being thrown. This modification fixes that.
=> CAS-5996, plug memory leak, close open table upon exception

CMakeLists.txt
This was triggered by #238. Building the python libraries does not have a disadvantage except for compilation time. Of course it can be manually disabled, and is disabled by default if CASA_BUILD=True.
=> Build python bindings by default (not for CASA build)

images/Images/ImageProxy.cc, images/Images/ImageProxy.h, images/Images/test/CMakeLists.txt, images/Images/test/tImageProxy.cc
Added imageInfoObject() and type() methods to return native casacore objects/types rather than Records/Strings.
=> Added methods to ImageProxy to return objects

lattices/LatticeMath/LatticeStatistics.h, scimath/Mathematics/ChauvenetCriterionStatistics.h, scimath/Mathematics/ChauvenetCriterionStatistics.tcc, scimath/Mathematics/ClassicalStatistics.h, scimath/Mathematics/ClassicalStatistics.tcc, scimath/Mathematics/ConstrainedRangeStatistics.h, scimath/Mathematics/ConstrainedRangeStatistics.tcc, scimath/Mathematics/FitToHalfStatistics.h, scimath/Mathematics/FitToHalfStatistics.tcc, scimath/Mathematics/HingesFencesStatistics.h, scimath/Mathematics/HingesFencesStatistics.tcc, scimath/Mathematics/StatisticsAlgorithm.h, scimath/Mathematics/StatisticsAlgorithm.tcc, scimath/Mathematics/StatisticsIncrementer.h, scimath/Mathematics/StatisticsIncrementer.tcc, scimath/Mathematics/StatsDataProvider.h, scimath/Mathematics/StatsDataProvider.tcc, scimath/Mathematics/test/tChauvenetCriterionStatistics.cc, scimath/Mathematics/test/tClassicalStatistics.cc, scimath/Mathematics/test/tFitToHalfStatistics.cc, scimath/Mathematics/test/tHingesFencesStatistics.cc
Upcoming changes to CASA's visstat require that some classes in the new statistics framework support different types for the iterator over data vs the iterator over weights. This branch includes all of the required changes to support that feature, including appropriate unit tests. Note that the changes have been implemented to be backward compatible -- previously existing unit tests are still applicable, and have not been changed.
=> Statistics framework enhancements

lattices/LatticeMath/LatticeHistograms.h, lattices/LatticeMath/LatticeHistograms.tcc, lattices/LatticeMath/test/tLatticeHistograms.cc
Requirement to return stats for each histogram, so overloaded getHistograms() with a version that also returns the stats array. Much of the changes are formatting only changes (eg indent 4 spaces not 3, and elimnate a lot of unnecessary blank lines). Also added tests for new method version.
=> CAS-5346 also return stats from getHistograms()

ms/MSSel/MSAntennaParse.h, ms/MSSel/MSSelection.cc, ms/MSSel/MSSelection.h, ms/MSSel/test/tMSSelection.out, ms/MSSel/test/tMSSelection.run
When re-using an existing MSSelection object, the error handlers were not getting reset before a fresh parsing cycle and would remember the last error message string.   This issue is fixed with the modification in this PR.  
Added a few more tests to test correctness when freq. specifications over/underflow at the edges of the SPW limits.
=> Fixed a bug in re-using MSSelection object + added more test

casa/Quanta/Euler.cc, casa/Quanta/Euler.h, casa/Quanta/MVEpoch.cc, casa/Quanta/MVEpoch.h, casa/Quanta/MVPosition.cc, casa/Quanta/MVPosition.h, casa/Quanta/test/CMakeLists.txt, casa/Quanta/test/tMVPosition.cc, measures/Measures/Aberration.cc, measures/Measures/MeasTable.cc, measures/Measures/MeasTable.h, measures/Measures/SolarPos.cc
coordinate transformations in casa are spending most of their time allocating memory instead of actually computing. This set of patches improves this a situation a bit via a few small changes, see the commits for details.
The largest change is using a small Vector cache to avoid creating new Vectors for each MVPosition and Euler temporary object that are created en mass in the conversion code.
This cache could in theory be moved lower into the stack, e.g. in the allocator itself and the Array object would need to use placement new's to create its Block object, though this is quite tricky to get right so I opted for the simpler change of just caching the objects that are problematic.
A disadvantage is that the small cache is never free'd so it would show up in valgrind, but that can be …
=> various coordinate performance improvements

ms/MSOper/MSMetaData.cc
Two changes are made to optimize MSMetaData::getPointingDirection (CAS-7643).
1. use ScalarColumn::get to access a cell instead of generating a vector of column values in all rows by ScalarColumn::getColumn. The latter causes severe performance degrade.
2. omitt redundant operation for rows of auto-correlation.
See https://bugs.nrao.edu/browse/CAS-7643 for more details.
=> Optimization of MSMetaData::getPointingDirection (CAS-7643).

lattices/LatticeMath/LatticeApply.tcc
This was trying to load all pixel values into a contigous slice of memory, and failing for large values. So, I've added code to make the required memory chunks no larger than 1024*1024 pixels.
=> CAS-7980 control the amount of contiguous memory required

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/test/tMSMetaData.cc
This commit ultimately fixes a defect exposed on OSX in my recent MSSummary commit. To avoid this same issue in the future, I've made MSMetaData::getScanKeys() (with no parameters) public.
=> OSX bug fix to recent MSSummary commit

CMakeLists.txt
Print a warning if DATA_DIR not given or does not contain ephemerides data (as a reminder for the person doing the installation).
=> Check for ephemerides data in DATA_DIR

mirlib/miriad.h, mirlib/uvio.c
Changed signature of uvrdvr_c to take a "const char *" rather than a char *; since the parameter is read-only, that's the appropriate type.
=> Changed signature of uvrdvr_c to take a "const char *" 

CHANGES.md, CMakeLists.txt, README.md, python/CMakeLists.txt, python/Converters/PycArrayComCC.h, python/Converters/PycBasicData.h, python/Converters/PycImport.cc, python/Converters/PycValueHolder.cc, python3/CMakeLists.txt
Adds support for Python3. Not enabling travis build, since it requires a recompilation of boost with python3 which just takes ages.
=> Add support for python3

casa/aipsenv.h
This is a belt-and-braces fix: if `__BYTE_ORDER__` is set (defined by GCC and
Clang), then that is used instead of trying to guess based on a list of known architectures. The architecture list is still there as a fallback, and I've added armel and aarch64el to the list of little-endian architectures.
I've also added aarch64 to the list of 64-bit architectures.
I've tested that this works on an armel system, which was previously unable to
read a measurement set due to the endianness being mis-detected. The aarch64
support is untested.
=> Fix endian detection for ARM

CMakeLists.txt
casacore assumes in several places that char is signed, even though C/C++
does not guarantee it. Passing -fsigned-char forces the compiler to treat it as
signed even on architectures (such as ARM) where it is normally unsigned.
This is potentially risky if inlined header code in any included library
assumes that char is unsigned, but this change makes all the unit tests pass
so it is almost certainly better than not using it.
See #249.
=> Add -fsigned-char to compiler arguments

images/Images/ImageFITS2Converter.cc, images/Images/ImageFITSConverter.h, images/Images/test/tFITSImage.cc
gh-272 introduced a regression in BITPIX 16 storing as the min and max pixel values where not progated from the fits header function to the fits output function.
also use a CountedPtr for the header structure to avoid leaking the mask from the header structure (like the one in the testsuite)
=> fix regression from gh-272

.gitignore, CMakeLists.txt, README.md, measures/Measures/MeasIERS.cc, measures/Measures/MeasTable.cc
Philosophy: only two paths are searched.
1. A user path, set in .casarc
2. A system path, set at compile time (actually cmake time)
This change removes hardcoded paths like /share/casacore/data. For compatibility, I kept the special paths casahome() and casaroot(), which can be specified at compile time with %CASAHOME% and %CASAROOT% and will be expanded at run time.
=> Meake measures data search path smaller

scimath/Mathematics/ClassicalStatistics.tcc
Quantile computations will failing on large data sets because of "rollover" of 32 bit uInts.
=> Fixed bug where uInt's should have been declared as uInt64's

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/test/tMSMetaData.cc
Add support for retrieving intents for a specified subscan. MSSummary now logs intents for the subscan, rather than the scan.
=> Support retrieving intents for a given subscan

tables/apps/taql.cc
This fixes the following compile error (with CXX11=True, but probably it's a bug everywhere). Probably just a typo.
```
[ 37%] Building CXX object tables/apps/CMakeFiles/taql.dir/taql.cc.o
/root/lofar/casacore/src/tables/apps/taql.cc: In function 'bool readLine(casa::String&, const casa::String&)':
/root/lofar/casacore/src/tables/apps/taql.cc:80:10: error: cannot convert 'std::istream {aka std::basic_istream<char>}' to 'bool' in return
return cin;
^
tables/apps/CMakeFiles/taql.dir/build.make:62: recipe for target 'tables/apps/CMakeFiles/taql.dir/taql.cc.o' failed
make[2]: *** [tables/apps/CMakeFiles/taql.dir/taql.cc.o] Error 1
CMakeFiles/Makefile2:7731: recipe for target 'tables/apps/CMakeFiles/taql.dir/all' failed
make[1]: *** [tables/apps/CMakeFiles/taql.dir/all] Error 2
Makefile:160: …
```
=> Fix taql if readline is not available

ms/CMakeLists.txt, ms/MSSel/MSFeedGram.cc, ms/MSSel/MSFeedGram.h, ms/MSSel/MSFeedGram.ll, ms/MSSel/MSFeedGram.yy, ms/MSSel/MSFeedIndex.cc, ms/MSSel/MSFeedIndex.h, ms/MSSel/MSFeedParse.cc, ms/MSSel/MSFeedParse.h, ms/MSSel/MSSelection.cc, ms/MSSel/MSSelection.h, ms/MSSel/MSSelectionError.cc, ms/MSSel/MSSelectionError.h, ms/MSSel/MSSelectionTools.cc, ms/MSSel/MSSelectionTools.h, ms/MSSel/test/CMakeLists.txt, ms/MSSel/test/tMSFeedGram.cc, ms/MSSel/test/tMSSelection.cc
Added code to enable MS feed selection in MSSelection including flex scanner and bison parser files.  Feed selection is a simplified form of antenna selection, as feeds are indices only and not names and there are no stations to select.
=> Added MS feed selection to MSSelection

msfits/MSFits/MSFitsInput.cc, msfits/MSFits/MSFitsInput.h
Cleaned up logic in the method to write the ANTENNA table including defect fixes and better error handling and logging. Refactored common code into a method of its own. Other refactoring. Since I'm the only one working on these files now, I'm using the industry standard _ prefix for private fields and methods. I will slowly be migrating existing fields to this format as I continue refactoring this code.
=> CAS-3660 bug fix for gaps in AN table, better error handling

fits/FITS/blockio.cc, msfits/MSFits/MSFitsInput.cc
Before this change, importing uvfits files with certain names would fail because FITS extended filename support was enabled. Now we first check the file name, and if that file exists, this support is disabled to allow import of those files which would otherwise fail if such support was enabled.
=> CAS-7696: Turn off extended filename support if specified file exists

CMakeLists.txt
Swap order of `data/` and `casacore/` in the default DATA_DIR, such that all casacore files under `share/` are installed and expected under `share/casacore/`. This brings it in line with where the casacore valgrind suppression file is installed, i.e. also under `share/casacore/`.
=> Rework default DATA_DIR

ms/MeasurementSets/MSTableImpl.cc, ms/MeasurementSets/MSTableImpl.h
For WSRT-APERTIF we need to create many MS quickly. The call to `MS::requiredTableDesc()` initializes some data structures once, but is not thread-safe. Add a mutex to resolve this. We need a recursive mutex, because the underlying `MSTableImpl::init()` function calls init() functions that call the original init() function again.
=> Fix multi-threaded MS creation

images/Images/ImageExprParse.cc, images/Images/test/CMakeLists.txt, images/Images/test/tImageExprParse.cc
Previously, parsing an empty LEL string caused a segfault. Now we check to ensure the string is not empty, and if so, we throw an exception.
=> CAS-8329: Throw exception if string to be parsed is empty

casa/BasicSL/String.cc, casa/BasicSL/String.h, msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/MSFitsOutput.h
I provided an OO interface to MSFitsOutput. I moved the implementation of MSFitsOutput::writeFitsFile() to MSFitsOutput::write(), changing variable names to their private counterparts, and changed some style elements. 
For some reason SubString::before() and SubString::_substr() were not const, which required callers to make copies of const Strings. I fixed that.
=> make String::before() const, provide OO interface to MSFitsOutput

images/Images/LELImageCoord.cc, images/Images/test/CMakeLists.txt, images/Images/test/tImageExpr2.cc, lattices/LEL/LatticeExprNode.cc, lattices/LEL/LatticeExprNode.h
For operator && and || images are now automatically extended.
Also added support for Double and DComplex in LELImageCoord.
Close #323
=> Issue #323; make images with different shapes possible for && and ||

tables/Tables/ConcatRows.cc, tables/Tables/TableProxy.cc
Issue #325 
Use openTable to be able to use :: in table names;
Check if nrows exceeds 2**32
close #325
=> Make :: possible in names of tables to concatenate

casa/Logging/LogIO.cc, casa/Logging/LogIO.h, ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/MSSummary.h, ms/MSOper/test/tMSMetaData.cc
Added support for logging uInt64 and Int64.
Fixed bug in MSMetaData::_getSubScanProps() which caused incorrect size of data structure to be computed.
_getSubScanProperties() -> getSubScanProps() (private to public) to allow caller to hold the entire property structure so it doesn't have to call for each subscan. => performance improvement
added progress meter when running getSubScanProps()
added MSMetaData::getNRowMap() to allow caller to hold entire data structure rather than having to call another method for each separate subscan => performance improvement
Added method to allow caller to specify that MSMetaData should always cache subscan properties structure since it can be very expensive to recompute if max cache size has already been exceeded.
Added …
=> Cas 8405: logging support for Int64 and uInt64 various MSMetaData/MSSummary mods

tables/DataMan/TSMCube.cc
This changeset aims to improve the cpu efficiency of non-strided part of the tiled storage manager.
I noticed that a CASA task doing nothing but IO is significantly bottlenecked by the cpu and not able to fully utilize a mid-range SSD (700mb/s bandwidth).
The main culprit is the TSMCube::accessSection which reads non-stride tiles. In ALMA and EVLA data the tiles are typically (X, Y, Z) with X being only of size 2 or 4 elements, the main copy-loop in this function loops over each dimension of the tiles so it iterates on a tiny dimension. As the buffers read and written are usually contiguous we can often merge the loops into larger copy calls.
There are four commits, the first just reindents some code, the second refactors the copy loop into a function without using local variables. The …
=> improve efficiency of tilestmanager

casa/Arrays/MatrixIter.tcc
Use 2 instead of 1 axis in MatrixIter constructor.
Close #340
=> Use correct nr of axes in MatrixIter

measures/Measures/MDirection.cc
A source name has to be looked up in the Sources table if unknown otherwise.
Close #341
=> Use Sources table in makeDirection

casa/apps/countcode
Countcode did not take .git into account.
Furthermore, type other is renamed to unknown.
Close #347
=> Improved countcode

CMakeLists.txt, measures/CMakeLists.txt
It also caches DATA_DIR, so it is known when a build causes cmake to be rerun.
Close #358
=> Moved test on existence of DATA_DIR to measures/CMakeLists.txt

casa/Containers/Record.h, casa/Containers/Record2.cc, casa/Containers/Record2Interface.cc, casa/Containers/RecordInterface.cc, casa/Containers/RecordInterface.h, casa/Containers/ValueHolder.h, casa/Containers/ValueHolderRep.cc, casa/Containers/test/tRecord.cc, casa/Containers/test/tRecord.out, python/Converters/test/tConvert.out, tables/Tables/TableRecord.cc, tables/Tables/TableRecord.h, tables/Tables/test/tTableRecord.cc, tables/Tables/test/tTableRecord.out
defineFromValueHoler and toValueHolder have been made virtual, so a TableRecord can also be converted to a ValueHolder. A Table in a TableRecord is kept as 'Table: <name>'
Close #361
=> Generalize Record::defineFromValueHolder

CMakeLists.txt
It was not possible to build module derivedmscal without fits; this has been improved.
Close #365
=> Change specification of modules to build

tables/DataMan/DataManager.cc, tables/DataMan/DataManager.h, tables/Tables/ColumnSet.cc
It must be possible for a data manager to forbid renaming a column.
Close #366
=> Added check if column can be renamed

tables/DataMan/TSMCube.cc, tables/DataMan/TiledCellStMan.cc, tables/DataMan/TiledColumnStMan.cc, tables/DataMan/TiledShapeStMan.cc
By using toArray in the TSM classes, the properties can be specified with other data types making it much easier to use from Python and TaQL.
Close #367
=> Use toArray instead of asArray

CMakeLists.txt
defaults (protected by 'CASA_BUILD=1') for developer builds in the context of a wider CASA build
=> set defaults for -DCASA_BUILD=1 (i.e. building within CASA context)

casa/Arrays/ArrayLogical.h, casa/Arrays/ArrayMathBase.h, casa/Arrays/ArrayPartMath.cc, casa/Arrays/ArrayPartMath.h, casa/Arrays/ArrayPartMath.tcc, casa/BasicMath/test/tFunctors.cc, casa/CMakeLists.txt, casa/OS/Time.h, tables/TaQL/ExprFuncNodeArray.cc, tables/Tables/test/tArrayColumnCellSlices.cc, tables/Tables/test/tConcatTable3.cc
Array functors derive from a base class to reduce code bloat in arrayPartMath.
Furthermore, a few functors have been added.
Close #371
=> Array functors derive from a base class

tables/Tables/BaseTable.cc, tables/Tables/BaseTable.h, tables/Tables/ConcatTable.cc, tables/Tables/ConcatTable.h, tables/Tables/MemoryTable.cc, tables/Tables/MemoryTable.h, tables/Tables/NullTable.cc, tables/Tables/NullTable.h, tables/Tables/RefTable.cc, tables/Tables/RefTable.h, tables/Tables/Table.cc, tables/Tables/Table.h, tables/Tables/TableCopy.cc, tables/Tables/TableCopy.h, tables/apps/showtableinfo.cc
Copying an table can use the StorageOption argument.
showKeywords has been moved to class Table to be commonly available.
Close #374
=> Added StorageOption argument to Table::copy

derivedmscal/DerivedMC/test/tUDFMSCal.run
This is needed to make this test pass if one uses a compiler that is not at the default location. Using this fix it can actually find the right libc++.
=> Added the LD_LIBRARY_PATH to the run

ms/MSOper/MSMetaData.cc
This prevents an unnecessary table scan to recompute scan keys when they have already been computed and cached in the _scanProperties map.
=> CAS-8509, increase effeciency of getScanKeys() in certain instances

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h
If _subScanProperties has been computed already, the necessary map can be gotten from that structure, avoiding a full table scan.
=> CAS-8511: Use subscan props in getNRowMap() if possible

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/test/tMSMetaData.cc
1. create MSMetaData::getFieldCodes()
2. avoid unnecessary table scan in MSMetaData::_getSubScanKeys() if _subScanProperties data structure has previously been cached
3. avoid unnecessary table scan in MSMetaData::getUniqueFiedIDs() if _subScanProperties data structure has previously been cached 
Performance increase of 15-20% realized.
=> improve performance of MSSummary and MSMetaData

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/test/tMSMetaData.cc
Also add correct spelling of getUniqueFieldIDs() and deprecate getUniqueFiedIDs().
=> CAS-8919 modify getRowStats() to use _subScanProps if it is cached

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/test/tMSMetaData.cc
add MSMetaData::getUniqueAntennaIDs() which uses subscan information if it exists rather than doing complete scans of two main table columns
add default parameter value to MSMetaData::getAntennaStations() to allow callers to retrieve all stations without having to provide cumbersome vector<uInt>() parameter.
rewrite portions of MSSummary::listAntenna() to use MSMetaData methods, along with minor style changes of existing code
add MSMetaData::getUniqueAntennaIDs() unit test to tMSMetaData
streamline MSMetaData::getUniqueDataDescIDs() unit test in tMSMetaData
=> CAS-8526 improve effeciency of MSSummary::listAntenna()

measures/TableMeasures/ScalarQuantColumn.h, measures/TableMeasures/ScalarQuantColumn.tcc, measures/TableMeasures/test/tTableQuantum.cc, ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc
This decreases the run time of MSMetaData::_getExposureTimes()
by a factor of 4 to 5 on large data sets.
Also, add a unit test for MSMetaData::getFirstExposureTimeMap()
which verifies this change
=> CAS-8529 improve performance of MSMetaData::_getExposureTimes()

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h
Also using col.getColumn(Vector<T>&) provides a noticeable performance
increase over Vector<T> = col.getColumn() for large tables.
=> CAS-8569 add _getMainScalarColumn() for common way of retrieving col data

msfits/MSFits/MSFitsInput.cc, msfits/MSFits/MSFitsInput.h, msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/test/tMSFITSInput.cc
New UVFITS AN table writing rules:
1. Antenna positions are ITRF, with geocentric origin, no subtraction of a fiducial "array center" is done
=> Array position ARRAYX, ARRAYY, ARRAYZ are always written as 0.
2. Antenna coordinate systems are right-handed, => XYZHAND is always written as "RIGHT" 
(which I believe is what AIPS hopes for if I've read the uvfits spec correctly). 
Reading rules:
Antenna positions are not implicitly rotated or inverted unless user explicitly specifies that they should be rotated and other conditions are met (the added configuration parameter allows for backward compatibility with UVFITS files written prior to this change).
=> CAS-8497 implement modifications to uvfits AN read/write rules

tables/DataMan/TiledStMan.cc, tables/DataMan/TiledStMan.h, tables/DataMan/TiledStManAccessor.cc, tables/DataMan/TiledStManAccessor.h, tables/DataMan/test/tTiledShapeStMan.cc, tables/DataMan/test/tTiledShapeStMan.out
The tile cache for an StMan is set on a per hypercube basis.  The methods
available from the TiledStManAccessor class use a row number that the
StMan then uses to determine the appropriate hypercube.  For virtually
concatenated databases, it's handy to be able to walk through the
hypercubes without regard to the row number.  TiledStManAccessor already
provides the number of tiles, so the new feature allows looping over the
hypercubes in the StMan and setting each hypercube to have the appropriate
cache size.
I don't fell that this mod does not appear to significantly expose any
additional abstractions from the StMan beyond what TiledStManAccessor
already exposes.
=> Mod to allow setting tile cache using hypercube number instead of row.

tables/TaQL/TaQLNodeDer.cc, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run, tables/TaQL/test/tTableGram.out, tables/TaQL/test/tTableGram.run
The values had to be put in an extra TaQLMultiNode because INSERT now can have multiple value lists. Added some tests.
Close #418
=> Fixed update-like insert problem

scimath_f/fgridsd.f
This change intends to make result of ggridsd2 identical with the one from ggridsd. To do that, gridding  operation in ggridsd2 are aligned with the corresponding part of ggridsd.
=> Align gridding operation in ggridsd2 with the corresponding part of ggridsd

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc
Account for ephemeris objects in getPhaseDirs() and improve performance of MSSummary by retrieving entire phaseDir data structure in one go rather than making multiple calls to msmd method.
=> CAS-8645 improve MSSummary performance for MS with many fields

tables/CMakeLists.txt, tables/DataMan/DataManager.cc, tables/DataMan/DataManager.h, tables/DataMan/TSMDataColumn.cc, tables/DataMan/TSMDataColumn.h, tables/DataMan/VirtualTaQLColumn.cc, tables/DataMan/test/tTiledShapeStMan.cc, tables/DataMan/test/tTiledShapeStMan.out, tables/Tables/ArrColData.h, tables/Tables/ArrColData.tcc, tables/Tables/ArrayColumn.h, tables/Tables/ArrayColumn.tcc, tables/Tables/BaseColumn.cc, tables/Tables/BaseColumn.h, tables/Tables/BaseTable.cc, tables/Tables/ScalarColumn.h, tables/Tables/ScalarColumn.tcc, tables/Tables/SetupNewTab.cc, tables/Tables/TableColumn.cc, tables/Tables/TableColumn.h, tables/Tables/TableCopy.cc, tables/Tables/TableCopy.h, tables/Tables/TableCopy.tcc, tables/Tables/TableRow.cc, tables/Tables/TableRow.h, tables/Tables/test/CMakeLists.txt, tables/Tables/test/tTableCopy.cc, tables/Tables/test/tTableCopy.out, tables/Tables/test/tTableCopyPerf.cc
CASA needed functionality to clone a table column, which has been done by adding a few functions to class TableCopy.
- cloneColumn clones a column using the same description and data manager type
- cloneColumnTyped does the same, but can change the data type
- copyColumnData copies the data from the given column to another (e.g., the new one)
- fillArrayColumn fills an array column with the given array
- fillColumnData fills a column from another column or with a given value
The cloning/copying functionality can preserve the tile shape of the original column, for which a preserveTileShape argument has been added to some table functions.
Close #354
=> Add functionality to clone a table column

ms/MSOper/MSKeys.cc, ms/MSOper/MSKeys.h, ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSKeys.cc, ms/MSOper/test/tMSMetaData.cc
expose MSMetaData::getScanToStatesMap() in public interface
add private MSMetaData::_generateScanPropsIfWanted() to allow methods to generate _scanProperties
data structure if it will be needed later.
Add filter() to filter scan keys based on an array key
Change tabs to spaces in some files.
=> CAS 8681 changes:

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
Antenna exes offsets don't seem to be used in CASA yet, but they are almost certainly going to be needed in the future for future VLBA-specific tasks such as UV shifting data to a new phase center.
Tested with both EVN and VLBA data.
=> Populate antenna axes offsets when importing FITS IDI files.

casa/BasicSL/STLMath.h, tables/TaQL/TaQLShow.cc, tables/TaQL/TaQLShow.h, tables/TaQL/TableGram.ll, tables/TaQL/TableGram.yy, tables/TaQL/TableParse.cc, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run, tables/Tables/BaseTable.cc, tables/Tables/BaseTable.h, tables/Tables/Table.h, tables/apps/showtableinfo.cc, tables/apps/taql.cc
TaQL now displays shapes in C-order when using that style.
The DIRECT option has been added for create table and add column commands.
close #428
=> Show shape in C-order when needed

tables/TaQL/ExprFuncNode.cc, tables/TaQL/TableParse.cc, tables/TaQL/TableParse.h, tables/TaQL/test/tTableGram.out, tables/TaQL/test/tTableGram.run
This makes queries like the following possible:
```
taql 'select from L1235-2438143.MS where TIME in [SELECT DISTINCT TIME FROM :: LIMIT 5]'
```
Before this change, one had to type the name of the measurement set twice, or use an alias.
=> TaQL: alias :: for outer table in subqueries

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/test/tMSMetaData.cc, msfits/MSFits/MSFitsOutput.cc, msfits/MSFits/MSFitsOutput.h, msfits/MSFits/test/tMSFITSOutput.cc
do not vary on an antenna by antenna basis
implemented MSMetaData::getUniqueSpwIDs()
modify MSFitsOutput::writeFitsFile() not to consume thrown exception just to return False, but rather allow thrown exceptions to continue to propogate up the stack. Method return type remains Bool.
=> CAS-8477 Ensure that receptor angles for specified spectral windows

scimath/Mathematics/FFTW.cc
Allows controlling openmp based applications completely via the openmp
env variables.
=> Use omp_get_max_threads to determine fftw thread number

tables/Tables/ArrayColumn.h, tables/Tables/ArrayColumn.tcc
the conversion from const char to String implies unnecessary memory
allocation in some relatively commonly called functions. Avoid this via
a const char interface
=> remove unnecessary String constructions

casa/Arrays/Array.h, casa/Arrays/Array_tmpl.cc, casa/Arrays/Matrix.h, casa/Arrays/Matrix_tmpl.cc, casa/CMakeLists.txt, casa/Quanta/Quantum.h, casa/Quanta/Quantum2.cc, casa/System/AipsrcValue.h, casa/System/AipsrcValue2.cc, images/CMakeLists.txt, images/Images/ImageInterface.h, images/Images/ImageRegrid.h, images/Images/ImageStatistics.h, images/Images/Image_tmpl.cc, images/Images/PagedImage.h, images/Images/SubImage.h, images/Images/TempImage.h, lattices/CMakeLists.txt, lattices/LatticeMath/LatticeStatistics.h, lattices/Lattices/Lattice.h, lattices/Lattices/LatticeIterInterface.h, lattices/Lattices/Lattices_tmpl.cc, lattices/Lattices/PagedArray.h, lattices/Lattices/SubLattice.h, measures/CMakeLists.txt, measures/TableMeasures/ArrayQuantColumn.tcc, measures/TableMeasures/TableMeas_tmpl.cc, ms/MeasurementSets/MSColumns.cc, ms/MeasurementSets/MSColumns.h
Add extern templates for types commonly used in CASA. Saves a bit of compilation time and disk space.
=> add some more extern templates

tables/Tables/TableRow.cc
Attempt to use copy less asArray<type> before falling back to the
converting function toArray<type> which implies copying.
This fixes a performance regression introduced in gh-426
=> avoid unnecessary conversions in TableRow::putField

lattices/Lattices/PagedArray.tcc, tables/Tables/Table.cc, tables/Tables/TableCache.cc, tables/Tables/TableInfo.cc
The PagedArray destructor flushes its underlying Table which essentially
makes the write Tile cache useless as many short lived objects do
contain PagedArray objects. When iterating over a Lattice in an
order that does not match the tileshape it will flush the cache on
destructions of for example LatticeIterators, LatticeExpressions or
SubImages and it while thus constantly rewrite partially modified tiles.
In some CASA tasks this leads to unnecessary very large write
amplifications.
To remove the all code that explicitly looks at table files on disk must
be adapted to respect the TableCache as it the flush frequency is
massively reduced and the files might not exist on disk at the time the
functions try to read them.
This commit updates Table::isReadable and TableInfo which is enough to …
=> Remove table flush on destruction of PagedArray

measures/apps/measuresdata/measuresdata.cc
The update frequency for IERS EOP-files was reduced in December 1 2011, see http://hpiers.obspm.fr/eop-pc/index.php?index=C04 . This has cause the script that generates the measures data tables to go into an infinite loop, downloading eopc04.16 , causing unnecessary load on the hpiers.obspm.fr server. 
The attached fix was implemented at ASTRON in december 2011 but apparently didn't make it upstream...
=> Measures data: reduce update frequency for IERS tables

CMakeLists.txt
When a predefined `CMAKE_CXX_FLAG` is used, it is (often) not project specific.
For example Debian sets it generically to enable hardening of the object files.
The `-fsigned-char` flag however is projectspecific and shall always be set here to ensure correct behaviour of char independently of the compiler.
This fixes the Debian failure mentioned in #249.
=> Unconditionally add -fsigned-char to CMAKE_CXX_FLAGS

casa/OS/HostInfo.cc, casa/OS/HostInfo.h
Prologue: I have not changed any existing functionality / interface, just added some new features.
Following requirements from the CASA HPC project (parallelization framework) I've added some set/gets to the casacore HostInfo class to override the aipsrc file values. In this way we can set different values per process for the memory/memoryFraction/numCores settings. 
When the custom memory/memoryFraction/numCores values are <= 0 they are ignored, so it is possible to set them to some custom value and then go back to the .aipsrc file defaults by setting them to 0.
See CAS-8159 and CAS-8158.
=> Justoagv aipsrc

casa/Utilities/GenSort.h, casa/Utilities/GenSort.tcc, casa/Utilities/test/tGenSort.cc
limit worst case runtime to O(NlogN) by aborting to heapsort when the
recursion level goes above the expected depth of log2(len(data))
This avoids O(N^2) performance worst case and stack overflow on the not
so uncommon case where the median of 3 pivot selects the last element.
E.g. [1, 2, 3, 4, 5, 0] which can happen on indirect sorting of MS index
columns like SCAN_NUMBER.
=> turn quicksort into introsort

casa/Arrays/ArrayMath.tcc
Removing the else allows the compiler to remove a branch by using the
branchless min and max instructions. It also allows vectorization.
Currently GCC does not vectorize the variation which also stores the
index so leave those unchanged.
=> Improve minMax performance

casa/Arrays/ArrayMath.tcc
some compilers are stupid and spill the max onto the stack, to avoid
that minimize the scope of the min/max values
=> further minMax improvement

CMakeLists.txt, casa/aipstype.h
Modified casa/aipstype.h to use an ifdef to enabled/disable the macro that
changes the "casacore" name to "casa".  Previously it was always defined but
with this mod it will only be defined when the symbol UseCasacoreNamespace
is not defined (i.e., ! defined (...)).
The CMakeLists.txt file was modified to define the C++ symbol
"UseCasacoreNamespace" by defining a similar vairable to make; for example
cmake .. -DUseCasacoreNamespace=1
The default behavior of the mod is to leave things the way they were so
that all "namespace casacore" are modified by the macro to be seen by
the compiler as "namespace casa", etc.   Only by defining the cmake
symbol will the new behavior be obtained.
Note: Any client project (e.g., CASA) that uses the new behavior will need
to define the same C++ symbol …
=> Added control of casa/casacore namespace via cmake.

tables/DataMan/TSMOption.h
Change incorrect references to "tables.tsm.\*" aipsrc variables in
TSMOption.h to "table.tsm.\*" to agree with implementation in
TSMOption.cc (and other Table aipsrc variable names).
=> Fix references to TSMOption aipsrc variable names

casa/Arrays/Array.h, casa/Arrays/ArrayMath.tcc, casa/Containers/Allocator.cc, casa/Exceptions/Error.h, casa/Utilities/Assert.h, images/Images/ImageStatistics.tcc, lattices/LRegions/LCEllipsoid.cc, measures/Measures/test/tMeasIERS.cc, ms/MSOper/MSMetaData.cc, ms/MSOper/test/tMSMetaData.cc, ms/MSSel/test/tMSSelection.cc
There were apparently some omissions in the previous commit as well as updates
to the codebase where people reintroduced the "casa" namespace.
=> Further mods supporting changeover to casacore namespace.

lattices/LEL/LELFunction.tcc
Several loops iterating arrays used uInt as counter, this could overflow
for large arrays.
Also minimize the scope of the accumulators in some of the computation
loops to avoid unnecessary stack spills.
=> Fix possible uInt overflows and tighten scopes

images/Images/ImageStatistics.tcc, scimath/Mathematics/ClassicalStatistics.h, scimath/Mathematics/ClassicalStatistics.tcc, scimath/Mathematics/FitToHalfStatistics.tcc
ensure _centerValue is computed in FitToHalfStatistics
FitToHalf stats extrema computation bug fixes
remove trailing character from string stream used for output in ImageStatistics.
=> Cas 8783 1 bug fixes

CMakeLists.txt
This will not affect builds where CASA_BUILD cmake variable is false.
=> Making casacore namespace the norm for casa builds.

lattices/LatticeMath/LatticeStatistics.tcc, lattices/LatticeMath/StatsTiledCollapser.tcc
CAS-8984 Reimplement inefficient method for zero-ing out quantile stats when they are not to be computed.
Catch noncontiguous array exceptions when old TiledApply method is used so that the new Stats framework method can be tried. Avoid that exception for smallish lattices by always using the new
framework method for them.
=> Cas 8984 LatticeStats reimplement zero-ing out of quantile stats when they are not computed, et al.

casa/aipsxtype.h, fits/FITS/fits.h
This is currently the case on all useful platforms. Cfitsio basically does the same in `fitsio.h`:
```
#define INT32BIT int  /* 32-bit integer datatype.  Currently this       */
/* datatype is an 'int' on all useful platforms   */
/* however, it is possible that that are cases    */
/* where 'int' is a 2-byte integer, in which case */
/* INT32BIT would need to be defined as 'long'.   */
```
This commit fixes some problems on some 64-bit architectures, namely arm64 and s390x which used the wrong typedef here because they were not explicitely listed. The test which failes was `images/Images/test/tFITSExtImage.cc`. Note, however, that there are still other tests failing, so this is just one step to get it running on non-x86 archs.
An alternative to the PR could be to use `#include <cstdint>` …
=> Unconditionally use `int` as data type for FitsLong.

tables/TaQL/ExprLogicNode.cc, tables/TaQL/ExprLogicNode.h, tables/TaQL/ExprNodeSet.cc, tables/TaQL/ExprNodeSet.h
Optimize `WHERE x in [integers]`
Replace the range limited constant lookup table with a set, much simpler code and consistent performance regardless of range. This avoids degrading to quadratic performance when the set range is too large.
It still seems like the wrong place to me to do this optimization, to me it would be more logical to have the implemented in the right hand operand instead of the operator, but I don't know the design of the taql very well so I left the current structure.
A possible improvement could be to use an c++11 `unordered_set` to kept he constant time, but its is not really relevant enough in practice do bother.
Also removed a quadratic performance issue in `TableExprNodeSet::add` when you do have a very long input taql set. Its cause is `casacore::Block::resize` …
=> taql constant integer set optimization

casa/CMakeLists.txt
The newly added Json*.h files weren't installed into the include directory
during build and would break casacore client builds.
=> CMakeLists.txt mod to fix PR #506

msfits/MSFits/FitsIDItoMS.cc
FITS-IDI files generated by difx2fits.
=> Allow alternate spelling of SOURCE_ID random parameter that is used in

images/Images/ImageOpener.cc
ImageOpener::openImage() don't have to
=> CAS-9271 call registerOpenFuncs() in ImageOpener::openImage() so callers of 

lattices/LatticeMath/StatsTiledCollapser.tcc
Issue #516 
Removed use of complex function real and imag to set the complex values as it is only supported in C++11. Until we all agree, no C++11 features should be used (unless ifdef-ed).
=> Removed use of C++11 feature

casa/OS/Timer.cc, casa/OS/Timer.h
There are some non-Linux systems using glibc as well, namely GNU HURD and kFreeBSD. For `getrusage()` they should be handled like the Linux systems.
This closes #463 by following the recommendation of the bug author Aaron M. Ucko amu@alum.mit.edu.
=> For glibc systems, use the correct getrusage() declaration

derivedmscal/DerivedMC/DerivedColumn.cc, derivedmscal/DerivedMC/DerivedColumn.h, derivedmscal/DerivedMC/DerivedMSCal.cc, derivedmscal/DerivedMC/DerivedMSCal.h, derivedmscal/DerivedMC/MSCalEngine.cc, derivedmscal/DerivedMC/MSCalEngine.h, derivedmscal/DerivedMC/Register.cc, derivedmscal/DerivedMC/UDFMSCal.cc, derivedmscal/DerivedMC/UDFMSCal.h, derivedmscal/DerivedMC/test/tDerivedMSCal.cc, meas/MeasUDF/DirectionEngine.h
Added functionality to derivedmscal to get the ITRF coordinates for the PHASE_DIR (or another FIELD column or another direction) using the TaQL UDF mscal.itrf or as a derived column that can be added to the MS.
=> Added functionality to create ITRF coordinates for an MS

CMakeLists.txt
As suggested earlier by @alxames , using C++11 by default is probably good.
=> Use c++11 by default

casa/OS/HostInfoLinux.h
Unlimited memory usage can be declared by a very large number but
smaller than size_t.max. Then the free memory is computed using this
wrong very large number.
So instead accept memory limits only when it is smaller than the total
memory of the physical machine determined earlier.
Also cleanup the code and add use of Linux 3.14 MemAvailable for the non cgroup code path. MemAvailable is more accurate than MemFree + MemCached.
=> fix free memory determination with cgroups

msfits/MSFits/FitsIDItoMS.cc
Makes it possible to import EHT FITS-IDI files created by the DiFX software correlator. Since polarisation leakage information is missing for the EHT telescopes (for now) the POLCALA/B columns contain no data (column descriptor 0E, consistent with the FITS-IDI standard) which makes attaching the columns fail.
=> Skip attaching POLCALA/B columns if NOPOL is 0

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h, ms/MSOper/MSSummary.cc, ms/MSOper/test/tMSMetaData.cc
because a single antenna name can be listed multiple times in the ANTENNA table. Main changes are to private data structure and associated methods which make use of it. Note that some public interface changes are necessarily not backward-compatible.
=> CAS-9358: Necessary fixes for antenna-related methods

images/Images/ImageBeamSet.cc, images/Images/ImageBeamSet.h, scimath/Mathematics/GaussianBeam.cc, scimath/Mathematics/GaussianBeam.h, scimath/Mathematics/test/tGaussianBeam.cc
Add optional unwrap parameter to GaussianBeam::setPA()
Add tests to test unwrap parameter in GaussianBeam::getPA()/setPA()
Add optional unwrap parameter to ImageBeamSet::rotate().
=> Cas 8482 fix unwrap bug in GaussianBeam and refactor that code into own method

.travis.yml
Solving issue #503 and #507 takes some time. In the meantime we could limit the testing to linux.
=> Disable travis test on OSX, until #503 is resolved

casa/Arrays/Cube.tcc
I found that Cube<T>::xzPlane(size_t) const outputs a message "test" to stdout. Since this is completely meaningless from the user's point of view, I guess it is temporary message for development that supposed to be removed finally. 
This request is just to remove the message. No functional change is made.
=> Removing message that may be put for developer testing.

tables/Tables/TableProxy.cc, tables/Tables/TableProxy.h, tables/Tables/test/tTableRecord.cc
Previously, much of the functionality for constructing a TableDesc
object from the more generic (and python convertible) Record object class was
static private. This meant that it was only possible to perform this
conversion within TableProxy methods.
By contrast, the functionality for constructing a Record
from the internal TableDesc (via TableProxy.getTableDescription) is public.
This commit changes many of the static private methods for constructing
a TableDesc from a Record public. By doing so, it becomes possible to
create more flexible C++ functions for creating various types of tables
from python-casacore. In particular, this makes it possible to create
default MeasurementSet tables from python while supplying additional table
description parameters. For example:
```cpp
TableProxy …
```
=> Make TableProxy Record to TableDesc static methods public

scimath/Mathematics/Convolver.tcc
This is a possible fix for the issue #572. Please merge it if appropriate.
=> Issue #572 Properly copy "valid" when Convolver object is copied.

.travis.yml
This change re-runs all failed tests on Travis. This should make it easier to spot why a test failed.
=> Travis: re-run failed test with verbose output

casa/Exceptions/Error.h
CASA Assert* macro definitions are dependent on whether NDEBUG is defined or
not, such that when NDEBUG is defined, the CASA macros are defined in terms of
the standard assert() macro. However, when NDEBUG is defined, the assert() macro
is effectively a no-op. The drawback of maintaining the inclusion of the
assert() macro is that it requires the assert.h header file, which is actually
missing from the Error.h file. Rather than include the header file so that
compilation works in the case of NDEBUG being defined, removing the use of
assert() in that case, in which it becomes a no-op, is the better solution.
=> Remove use of assert() in Error.h

msfits/MSFits/MSFitsIDI.cc
This fixes importing FITS-IDI files produced by DiFX, which produces
empty subtables if certain metadata is missing for all stations.
=> Only skip over a subtable if it actually contains data

CMakeLists.txt, images/Images/ImageConcat.tcc, images/Images/test/tFITSImage.run
The CAS-9605 was not fully correct, because the ImageInfo (beam info) was not always combined.
It also appeared that the sed command in tFITSIMage did not always work properly, so it has been fixed.
=> Fixed ImageConcat problem with ImageInfo

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h
FITS-IDI generated by the DiFX software correlator has weights encoded in
the WEIGHT random parameter instead of encoding it along the COMPLEX axis.
This replaces the no-working/unused code that looked for a WEIGHT keyword
which doesn't exist in FITS-IDI.
Tested with both GMVA data (DiFX data that uses the WEIGHT random parameter)
and EVN data (SFXC data that stores weights along the COMPLEX axis).
=> Handle FITS-IDI that uses the WEIGHT random parameter

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
Data correlated with the DiFX correlator needs to have quantization
corrections applied.  Since these corrections are different for auto
correlations and cross correlations it is easiest to apply them while
importing the data.  This implementation matches what the AIPS FITLD task
does and what is described in VLBA Correlator Memo 75 and VLBA Scientific
Memo 12.
=> Implement digital corrections for DiFX/VLBA

ms/MSOper/MSMetaData.cc, ms/MSOper/MSMetaData.h
Reimplemented _computeScanAndSubScanProperties() to use significantly less memory for large data sets. Associated refactoring, including moving the merge of properties to its own private method.
=> Cas 10150 reimplemenet _computeScanAndSubScanProperties()

coordinates/Coordinates/FITSCoordinateUtil.cc, fits/FITS/FITSKeywordUtil.cc
This is part 2 of 2 of the fix for CAS-9993 / CAS-10342 (the latter ticket needed to be filed for technical reasons as a continuation of CAS-9993). The problem solved here is that the PC matrix written by FITSKeywordUtil.cc is transposed w.r.t. its proper value. However, FITSKeywordUtil.cc is self-consistent in its read/write behaviour. The problem is therefore solved at the transition from the image representation of the linear image coordinates transformation to the PC matrix, i.e. in FITSCoordinateUtil.cc where the pc matrix is retrieved from the CASA image.
Comprehensive tests were performed to verify that the change (a) solves the problem within the CASA framework and (b) does not damage anything else in casacore.
As promised in pull 606, I also added the comment explaining the magic …
=> Fix transpose problem of FITS PC matrix found in CAS-9993

ms/MSOper/MSMetaData.cc
in order to resize input array if necessary to avoid array
conformance exception
=> CAS-10409, add resize=True to restfreq.get()

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h
Initialize the WEIGHT/WEIGHT_SPECTRUM and SIGMA/SIGMA_SPECTRUM columns
in a way that is compatible with the conventions used by CASA 4.4 an later.
This uses the correlator weights to calculate the effective integration time
that is used in the caclulation of the expected per-channel noise.
This should make is possible to combine data with different integration
times and channel widths.
=> Properly initialize weights when importing FITS-IDI

scimath/Mathematics/ChauvenetCriterionStatistics.h, scimath/Mathematics/ChauvenetCriterionStatistics.tcc, scimath/Mathematics/ClassicalStatistics.h, scimath/Mathematics/ClassicalStatistics.tcc, scimath/Mathematics/FitToHalfStatistics.h, scimath/Mathematics/FitToHalfStatistics.tcc, scimath/Mathematics/HingesFencesStatistics.h, scimath/Mathematics/HingesFencesStatistics.tcc, scimath/Mathematics/StatisticsAlgorithm.h, scimath/Mathematics/test/tChauvenetCriterionStatistics.cc, scimath/Mathematics/test/tClassicalStatistics.cc, scimath/Mathematics/test/tFitToHalfStatistics.cc, scimath/Mathematics/test/tHingesFencesStatistics.cc
Implemented clone() method and added tests
If being called from a parallelized block, don't parallelize stats computations
Substituted macros in some places
Made more eclipse-friendly in some places (eg vector -> std::vector)
=> CAS-10358 implement clone() method, do not parallelize if called from a parallelized block

casa/OS/Time.cc, casa/Quanta/MVAngle.cc, casa/Quanta/MVAngle.h, casa/Quanta/MVTime.cc, casa/Quanta/MVTime.h, casa/Quanta/test/tMVTime.cc, casa/Quanta/test/tMVTime.out
In some cases it was not checked if the entire date/time was processed when parsed. It has been fixed.
Furthermore, an argument has been added (in an ABI-compliant way) to tell if an exception has to be thrown in case of an error.
Finally, it appeared that Time had rounding problems when returning hours, minutes or seconds. It has been improved.
Close #614
=> Fixed parsing of date/time

.travis.yml
The default travis Linux OS has become Ubuntu "trusty". To continue using Ubuntu "precise" on travis, this configuration value is required. Note that a build of the branch for #615 was failing until I tried out this change (which has been reverted on that branch). Long term, I suggest we move to "trusty", in which case pinning the version at "precise" may be considered a workaround.
=> Pin travis Linux OS at "precise"

msfits/MSFits/FitsIDItoMS.cc
The current approach of using ARRAYNAME:NUMBER as the station name breaks
concatenating imported FITS-IDI files that have different sets of antennas.
This results in differences in station names for the same antenna which
the concatenation code interprets as moving the antenna.
=> Use antenna name as station name when provided

coordinates/Coordinates/SpectralCoordinate.cc
Fixed an exception for the near test when it is a TabularCoordinate with 1 value only (which happens commonly when doing subimage on a Tabular spectral cube for e.g)
=> Tabular SpectralCoordinate::near bug

scimath/Mathematics/StatisticsAlgorithm.tcc, scimath/Mathematics/StatisticsAlgorithmFactory.h, scimath/Mathematics/StatisticsAlgorithmFactory.tcc
Grimmer noticed that some of the header paths were incorrect. This went undetected by the Casa build system but caused trouble if Carta.
=> Correct the header paths.

ms/MSOper/MSDerivedValues.cc, msfits/MSFits/FitsIDItoMS.cc
This introduces new mount types "NASMYTH-LEFT" and "NASMYTH-RIGHT"
for left-handed and right-handed Nasmyth mounts found on EVN, GMVA
and EHT antennas.  This change also makes the FITS-IDI import code
recognize these mount types, which are described in the update
FITS-IDI standard (AIPS Memo 114).
=> Parallactic angle calculation for Nasmyth mounts

casa/Arrays/IPosition.cc, casa/Arrays/IPosition.h, casa/Arrays/test/tIPosition.cc, images/Images/ImageOpener.cc, images/Images/ImageOpener.h, lattices/LatticeMath/LatticeStatistics.tcc
* Added COMPLISTIMAGE to ImageOpener::ImageTypes enum and added code to ImageOpener.cc for recognizing such images.
* Implemented IPositionComparator to allow IPositions to be used as keys in ordered lists.
* Fixed bug regarding progress meter in LatticeStatistics.
=> CAS-7309 add support to ImageOpener for componentlist images

scimath/Mathematics/FitToHalfStatistics.h, scimath/Mathematics/FitToHalfStatistics.tcc, scimath/Mathematics/test/tFitToHalfStatistics.cc
to always include MEAN if centerType is CMEAN.
=> CAS-10760 bug fix for FitToHalfStatistics::setStatsToCalculate()

images/Images/ImageUtilities2.tcc
History copying can be problematic, for example, for some FITS images,
as the FITS history reading code is not perfect in all cases.
=> CAS-10829: Catch history copying exception, log message, and continue

images/Images/ImageRegrid.tcc, lattices/LatticeMath/LatticeStatistics.tcc, lattices/LatticeMath/LatticeStatsDataProvider.h, lattices/LatticeMath/LatticeStatsDataProvider.tcc, lattices/LatticeMath/MaskedLatticeStatsDataProvider.h, lattices/LatticeMath/MaskedLatticeStatsDataProvider.tcc, scimath/CMakeLists.txt, scimath/Mathematics/ClassicalStatistics.h, scimath/Mathematics/ClassicalStatistics.tcc, scimath/Mathematics/ClassicalStatisticsData.cc, scimath/Mathematics/ClassicalStatisticsData.h, scimath/Mathematics/StatisticsAlgorithm.h, scimath/Mathematics/StatsDataProvider.h
decreases overhead and increases performance when less than the number of maximum threads available to openmp can be used.
improves run time of one of my image stats test cases by almost a factor of 2
=> CAS-9007 allow data provider to control max number of threads

msfits/MSFits/FitsIDItoMS.cc
While the VLBA dishes themselves have a diameter of 25m, VLBA
observations regularly include Green Bank or (phased) VLA.
On top of that, other VLBI arrays that use the DiFX correlator
often set the array name in their FITS-IDI file for compatibility
with (older versions of) AIPS.  Setting the dish diameter to 25m
for these arrays is simply wrong.  Instead, rely on the diameters
set in the FITS-IDI file for the VLBA.
=> Do not set default diameter for VLBA to 25m

tables/Tables/TableIter.cc
Replace the call to TableIterator::next(), which initializes the subTable_p
member, in the TableIterator copy assignment operator with a copy assignment of
the subTable_p member. This is intended for the copy to have the same state as
the copied instance.
=> Avoid incrementing TableIterator in copy assignment

casa/HDF5/HDF5DataSet.cc, casa/HDF5/HDF5DataSet.h, casa/HDF5/HDF5Object.h, casa/HDF5/test/tHDF5DataSet.cc
In HDF5-1.10 the hid_t has been increased from 32 to 64 bits, which caused problems in HDF5Object. This has been fixed in a way that both 32 and 64 bit hid_t is supported.
Furthermore, HDF5DataSet has been extended with a get and put function to handle an Array object. Finally, the error messages in HDF5DataSet have been improved.
Close #638
=> Issue #638 Fixed HDF-1.10 problem with 64-bit hid_t

images/Images/ImageBeamSet.h, images/Images/ImageConcat.h, images/Images/ImageConcat.tcc, images/Images/ImageInfo.cc, images/Images/ImageInfo.h, images/Images/ImageInterface.h, images/Images/ImageInterface.tcc, images/Images/test/tImageConcat.cc
CAS-10849 reported that when setting the restoring beam for a ConcatImage, it did not get updated in the child images. This has been added now and the tImageConcat test program has been extended accordingly.
Maybe Dave Mehringer should review the code before merging the PR.
=> Set ImageConcat restoring beam in child images

ms/MeasurementSets/MSIter.cc
The setMSInfo() function would check the keywords of the DATA column,
or if it doesn't exist FLOAT DATA in order to get a possible channel selection.
If you create a synthethic MS with MsFactory (from CASA) without any of the
two columns a segfault happens. Still, such an MS can be useful for unit
testing purposes.
I encountered this issue while working on CAS-10458, reported by David Mehringer.
=> Check for not null DATA or FLOAT DATA columns before accessing the keywords

ms/MeasurementSets/MSIter.cc
This fixes a problem with commit 689fb9b487b2d2174faafdb19197e8fc9fd93f81
reported by valgrind. The preselected_p was left uninitialized when
these columns are not present.
This is part of fixing CAS-10458
=> Initialize preselected_p properly even if no DATA or FLOAT DATA columns exist

tables/Tables/TableIter.cc, tables/Tables/test/tTableIter.cc
It turns out the solution in #644 did break the DPPP build; I'm not sure how this slipped (I tested it then, but I don't know how it could have passed). Unfortunately this also means that the released 2.4.0 under some circumstances does not work well with DPPP.
In the following code, I expect `iter1` and `iter2` to be really the same:
```
TableIterator iter1(tab1, iv1, compObj, orders);
TableIterator iter2 = TableIterator(tab1, iv1, compObj, orders);
```
It turns out that although they have the same `nrows()`, they yield a different number of rows. This is demonstrated in the test in this PR.
I think it is valid to call `next()` in the copy constructor, because it is also called once in the normal [constructor](https://github.com/casacore/casacore/blob/master/tables/Tables/TableIter.cc#L52 …
=> Initialize tableiterator in assignment like in constructor

.travis.yml
The macOS jobs are failing, see #682. This is due to some issues with the build system. While that is being fixed, I suggest to temporarily disable the test to avoid seeing the build error in every PR.
=> Temporarily disable travis on OSX

ms/MSOper/test/tNewMSSimulator.cc
`AIPS_CXX11` gets set by `aipsenv.h`, which is included from `aips.h`. By convention, `aips.h` should be one of the first includes. I'm not sure how the test could have built before; on my system the line `#include <random>` did not get called.
=> Add forgotten include to tNewMSSimulator

casa/CMakeLists.txt, casa/System/AppState.cc, casa/System/AppState.h, casa/System/test/CMakeLists.txt, casa/System/test/tAppState.cc, measures/Measures/MeasIERS.cc
As work begins on CASA's (https://casa.nrao.edu) transition to Python 3, we would like to fix structural issues at the same time because the Python 3 conversion will necessarily involve changes and fixes on the part of CASA's users. Two related things we would like fix is (1) removing CASA's dependency on environment variables (CASAPATH in this case) without requiring that static paths be compiled into the application, and (2) support checking multiple directories when attempting to open image or measurement sets (i.e. a data path in the $PATH sense of the word).
This change introduces a hook for applications which use casacore to specify a data path, and it includes changes so that measures is able to find the IERS data when it is included in the optionally specified data path. Other …
=> casacore configuration sans environment variables

scimath/StatsFramework/ClassicalStatistics.h, scimath/StatsFramework/ClassicalStatistics.tcc, scimath/StatsFramework/test/tClassicalStatistics.cc
using similar pattern to what has been used in other methods that
have been parallelized in this class. In addition to obvious performance
boost, is also necessary for further refactoring so similar patterns
can be used.
* Add unit tests.
* vector -> std::vector in some places in tClassicalStatistics to play more nicely with eclipse.
=> CAS-11050 parallelize ClassicalStatistics::_doNpts()

lattices/LatticeMath/LatticeStatistics.tcc
Minimum number of full lattice scans when _doRobust = True is 3, not 2.
=> CAS-11065 fix progress meter estimated number of steps

build-tools/casacore_memcheck, build-tools/casacore_memcheck.supp, casa/HDF5.h, casa/HDF5/HDF5DataSet.cc, casa/HDF5/HDF5DataSet.h, casa/HDF5/HDF5DataType.cc, casa/HDF5/HDF5DataType.h, casa/HDF5/HDF5HidMeta.cc, casa/HDF5/HDF5HidMeta.h, casa/HDF5/HDF5Record.cc, casa/HDF5/test/CMakeLists.txt, casa/HDF5/test/tHDF5DataSet.cc, casa/HDF5/test/tHDF5DataType.cc, casa/HDF5/test/tHDF5Record.cc, ms/apps/readms.cc, ms/apps/writems.cc
Improved read/writems to store most of the MS main columns as a compound datatype when storing the visibility data in HDF5 format.
Made it possible to read HDF5 data (and MS data) without column iteration.
=> Added code to use HDF5 compound data types in MS testing

measures/Measures/MeasIERS.cc
This bug from my last commit was missed because the tables were found from other locations.
=> check flag while traversing data directories

casa/OS/malloc.h
Pedantic compilers complain about the ; after extern "C" { ... }, which indeed is not required.
=> Removed semicolon after extern "C" { ... }

casa/OS/HostInfo.cc
The HostInfo class is not implemented for ppc64, in which case defaults are used. These defaults still had outdated signatures.
=> fix HostInfo signatures for ppc64

casa/aipsenv.h
The `__linux` define is deprecated (see https://sourceforge.net/p/predef/wiki/OperatingSystems/), we should use `__linux__` instead.
=> Fixed deprecated check for Linux.

ms/MSOper/MSConcat.cc, ms/MSOper/MSConcat.h
When concatenating MeasurementSets the associated SYSCAL tables should be concatenated as well. Otherwise only Tsys values from the first MeasurementSet survive and amplitude calibration will fail for the appended data. With this change the importfitsidi task in CASA can be used to read in multiple FITS-IDI files that contain a SYSTEM_TEMPERATURE table with Tsys measurements.
For "virtual" concatenation, additional values are appended to the SYSCAL table of the first MeasurementSet when creating the MMS.
=> Concatenate SYSCAL tables

casa/Arrays/Array.h, casa/Arrays/Array.tcc, casa/Arrays/Vector.tcc, casa/Arrays/test/tArray.cc, casa/Containers/Allocator.cc, casa/Containers/Allocator.h, casa/Containers/Block.h, casa/Containers/test/tBlock.cc, measures/Measures/MCDoppler.cc, measures/Measures/MCDoppler.h
I encountered static initialization errors when trying to compile casacore object modules directly into a stand-alone executable (i.e. a stand-alone distribution of the casa viewer). The problems arise with the Array initialization constants and the initialization of MCDoppler state. These static are initialized properly when casacore is built into the various standard libraries (libcasa_casa, etc.). However, the initialization-before-use only happens because of this particular breakdown of the code into libraries. It falls apart when the object files are compiled into a single library or a single executable. It’s easy to see the issue, but there are a couple of solutions to the static issue in general:
1. convert the static to a static function which returns the static value
1. convert …
=> Allocator::INIT/NO_INIT and MCDoppler static state initialization prob

casa/Quanta/Euler.cc, casa/Quanta/Euler.h, casa/Quanta/MVPosition.cc, casa/Quanta/MVPosition.h, casa/Quanta/test/tMVPosition.cc
This pull request fixes some memory leaks in the Euler and MVPosition classes.
The part that leaks is the caching mechanism to avoid too many allocations put in place around two year ago. The leak is actually small but it clutters the output of valgrind in almost any unit test in casa/code, by outputting 150+ errors.
I have cleanup the output of valgrind for the tMSDerivedValues unit test but there are still 8 remaining memleaks, which I didn't dare to clean up since they look a bit more complex to me.
This patch uses smart pointers to ensure RAII, with the caveat of being a bit slower than the raw pointers used before. The slowdown is around 50% (only in the construction/destructor code) but it is still 5x faster than not using cache at all.
=> Fix memory leaks in the Measures module

ms/MSSel/MSSelectionTools.cc
Fixes #707, see issue for a description of the problem. 
This simply replaces `throw(x)` with `throw` where the old `throw(x)` doesn't let us distinguish specific exception types such as  `MSSelectionNullSelection`.
=> Preserve original exception object in ms/mssSetData

python/Converters/test/tConvert.py
keep numpy 1.13 printoption for numpy 1.14 or above, otherwise doctest for tConvert will fail
=> Keep numpy array printing consistent for doctest with numpy v1.14 or above

ms/MeasurementSets/MSFieldColumns.cc, ms/MeasurementSets/MSFieldColumns.h, ms/MeasurementSets/test/tMSFieldEphem.cc
Added MDirection ephemerisDirMeas(Int row, Double time = 0) const;
(CASA ticket CAS-11214); added corresponding unit test code and documentation in the header file.
The new method behaves exactly like, e.g., 
MDirection referenceDirMeas(Int row, Double time = 0) const;
however, it does not apply any offsets which might be stored in the nominal direction columns. 
I.e. it always gives the unaltered direction of the attached ephemeris or, if there is no ephemeris attached, simply the same as referenceDirMeas().
=> Added new method MDirection MSFieldColumns::ephemerisDirMeas()

tables/TaQL/TaQLNodeDer.cc, tables/TaQL/TaQLNodeDer.h, tables/TaQL/TaQLNodeHandler.cc, tables/TaQL/TaQLNodeHandler.h, tables/TaQL/TaQLShow.cc, tables/TaQL/TaQLShow.h, tables/TaQL/TableGram.ll, tables/TaQL/TableGram.yy, tables/TaQL/TableParse.cc, tables/TaQL/TableParse.h, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run, tables/TaQL/test/tTableGram.out, tables/TaQL/test/tTableGram.run
This PR fixes issue #706 regarding subtables used with a temporary table name.
It also fixes a minor issue related to using table aliases in wildcarded column names.
Finally, quite some documentation has been added to TableGram.ll and .yy.
Close #706
=> Fixed temp table issue in TableGram

images/Images/FITSImage.cc, images/Images/FITSImage.h, lattices/LatticeMath/LatticeApply.h, lattices/LatticeMath/LatticeApply.tcc
add static method to FITSImage to be able to test for name of
image type without having to create an object to do it
=> CAS-11195. Make LatticeApply::lineMultiApply more effecient at reading

measures/Measures/MCDirection.cc, measures/Measures/MeasComet.cc, measures/Measures/MeasComet.h
The code in MCDirection setting up the conversion for ephemerides is hardwired hardwired to MDirection::APP. This is a fix for it. 
[meascomet_bug.py.txt](https://github.com/casacore/casacore/files/1857876/meascomet_bug.py.txt)
You can try the attached file (edit it to point to your data repository ephemerides) in any  casa and you'll see that it gets nearly 0.13 deg difference between the value given by DE405  and the ephemerides
*here is the output of the script in non-fixed casa*
Direct value for JPL table  18:44:52.203168 -023.02.14.394480
Using Measures me.direction("SUN") converted 18:44:52.202443 -023.02.14.390270
Using Measures me.direction("SUN") converted correcting for parallax 18:44:51.692250 -023.02.19.888463
Using measures  me.direction("COMET") converted  18:44:16.891719 …
=> Measures conversion of ephemerides table direction is ignoring the frame

derivedmscal/DerivedMC/DerivedColumn.cc, derivedmscal/DerivedMC/DerivedColumn.h, derivedmscal/DerivedMC/test/tDerivedMSCal.cc, tables/DataMan/VirtArrCol.h, tables/DataMan/VirtArrCol.tcc
pyrap gave an error on a derivedmscal column when getting a row from a table.
It appeared that DerivedColumn did not have isShapeDefined implemented.
=> Fixed problem with isDefined on derivedmscal columns

casa/Quanta/Euler.cc, casa/Quanta/Euler.h, casa/Quanta/MVPosition.cc, casa/Quanta/MVPosition.h, casa/Quanta/test/tMVPosition.cc
This PR removes altogether the Vector cache for MVPosition and Euler classes that was introduced
in #258 and modified in #680.
The cache was implemented using a thread_local storage, which means that the cache shouldn't be shared among different threads. This was unfortunately the case, since the MeasTable class creates some global objects that include instances of MVPosition derived classes. This causes
undefined behaviours, since the constructors for thread_local variables are called before the destructors for the global variables, according to the C++11 standard. Running the tTableMeasures test triggered in fact a segmentation fault due to this and valgrind reports those errors.
The original cache implementation didn't clean the memory, so the problem was simply hidden. The original …
=> Remove altogether the Vector cache for MVPosition and Euler classes.

CMakeLists.txt
because CASA no longer build ASAP we no longer need the Boost-python libraries from casacore
=> turn off python for casa builds of casacore

.travis.yml, .travis/before_script.sh, .travis/install.sh
The repo homebrew/science became outdated, and no there seems to be no
way to install wcslib through homebrew. Move to conda for both cfitsio
and wcslib.
Fix a brew compiler installation error: uninstall oclint, see
https://github.com/travis-ci/travis-ci/issues/8826
Fixes #682
=> [Travis] Fix Travis OSX environment

ms/MeasurementSets/MSWeather.cc, msfits/MSFits/MSFitsOutput.cc
In [MSv2 design document](http://casacore.github.io/casacore-notes/264), the unit for atmospheric pressure is defined as
"hPa". However, implementation was different (Pa). This commit fix the
unit to be consistent with the documentation.
cf. https://open-jira.nrao.edu/browse/CAS-11528
=> Align the unit for atmospheric pressure with documentation

.travis/before_script.sh, CMakeLists.txt, casa/aipstype.h
With this change, the `casacore` namespace becomes the default. It can be defined to `casa` at compile time. Currently, the behavior is the opposite: without specifying anything on the command line, the `casa` namespace is used.
=> Make casacore namespace default

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/MSFitsIDI.cc
Not all possible flagging commands are supported, but this seems to be enough to support the flagging commands provided by the VLBA, which is far as I know the only array that provides FLAG tables in their FITS-IDI tables.
=> Import FITS-IDI FLAG tables and store translated flagging commands in a MS FLAG_CMD table.

tables/Tables/ConcatColumn.cc, tables/Tables/ConcatColumn.h, tables/Tables/ConcatTable.cc, tables/Tables/ConcatTable.h, tables/Tables/test/tConcatTable.cc
Fixes #753.
See issue for a description of the problem. I've extended tConcatTable to catch this kind of issue (but I'm not totally sure I'm following the casacore test conventions properly). 
In CASA, this fixes the issue for the calibrater tool and uvcontsub (for which we had an ugly workaround) and tclean (for which we don't have a workaround).
=> Fix addColumn in ConcatTable

tables/Tables/TableProxy.cc, tables/Tables/TableProxy.h
Currently TableProxy::getCol returns an empty ValueHolder if no rows are given with the result that  in python-casacore a None object is returned.
It is better to change that into an 1-dim array with 0 entries, so in Python one can iterate over the result.
=> Let getcol() return an empty array if no rows

python/Converters/test/tConvert.py
This is a followup to 7d47522e044b7fcb23eb894f3827c64da5209500. The test should be being comparing with 1.14; for 1.13 there exists a 1.13.1 which still cannot use the `set_printoptions` function.
=> Fix version number check for numpy print option

CMakeLists.txt, tables/CMakeLists.txt, tables/Tables/BaseTable.cc, tables/Tables/BaseTable.h, tables/Tables/PlainTable.cc, tables/Tables/PlainTable.h, tables/Tables/Table.cc, tables/Tables/Table.h
See discussions in #729 
This PR added MPI support for the casacore table data system. Previously we can partially achieve parallel I/O by introducing a parallel storage manager (e.g. https://github.com/SKA-ScienceDataProcessor/AdiosStMan). However, the table layer API was strictly serial for writing. In this PR, I added MPI-awareness to the table layer API. The logic is to write the table files only on Rank 0, while other ranks do not write any data. This fixed the issue that slave ranks of user applications have to pass in garbage tables with the table API to avoid conflicts when writing table files. 
To use this feature, one must configure casacore using the following flags
-DUSE_MPI=ON 
-DENABLE_TABLELOCKING=OFF
Also, one must use a parallel CTDS storage manager. Some of the existing …
=> Added MPI support for parallel CTDS I/O

build-tools/casacore_memcheck.supp, tables/DataMan/SSMIndColumn.cc, tables/DataMan/test/tStandardStMan.cc, tables/DataMan/test/tStandardStMan.out
With the StandardStMan the indirect array file (e.g., table.f0i) grew if an array (or record) with the same shape was written. It has been fixed by taking care the existing shape is known.\
close #721 #767
=> Take care similary shaped data overwrites existing data

casa/HDF5/HDF5Object.h
Fixes #771.
Casacore defines it's own 64-bit integer type, Int64, in casacore/casa/aips.h as 'long long'. The HDF5 library defines it's hid_t as int64_t from <stdint.h>. On different systems int64_t can be 'long long' or simply 'long', and in the latter case the compiler cannot match HDF5Group::init's arguments for the constructor that uses implicit conversion from HDF5Object to hid_t.
=> Change HDF5Object hid type to match hdf5 headers.

casa/Utilities/CountedPtr.h
It would be nice if older CASA versions can be built with this version of casacore. Hence a #define of SHARED_PTR is added again.
=> Re-introduced SHARED_PTR for older CASA versions

README.md
The name of the file with the contribution manual has changed, but the link in the main README file hasn't.
=> Correct link to contribution manual

fits/FITS/hdu.tcc, fits/FITS/hdu2.cc, lattices/LatticeMath/LatticeConvolver.tcc, measures/Measures/test/tMeasJPL.cc, ms/MSOper/MSSummary.cc, ms/MeasurementSets/MSDoppler.cc
In the spirit of clearing warnings before 3.0, please have a look at these. I found them with gcc 6.3 + -Wall (in particular with -Wmisleading-indent) some time ago. Most of the changes are statements that should have been within brackets in the first place. The commit message contains more information.
=> Fixing warnings due to misleading indentations

tables/TaQL/ExprFuncNode.cc, tables/TaQL/TableParse.cc, tables/Tables/NullTable.cc, tables/Tables/NullTable.h
valgrind found an array bound error in ExprFuncNode.cc.
It also improves NullTable how to avoid compiler warnings.
Close #812
=> Fixed TaQL segfault and a valgrind error

casa/OS/Mutex.h, ms/MSOper/test/tNewMSSimulator.cc
class CallOnce and CallOnce0 did not work well when used with USE_THREADS=OFF. Certainly std::call_once failed on Linux with gcc-4.8.2 when used without threading. It has been fixed by using a Bool flag if USE_THREADS=OFF is used.
The obsolete auto_ptr was replaced by unique_ptr in tNewMSSimulator.cc.
Close #815 
Close #808
=> Fix call_once with USE_THREADS=OFF and fix use of auto_ptr

lattices/LatticeMath/LatticeApply.tcc
This is a followup to #827 which did not fix the 32-bit issue completely. Same pattern however ;-)
Now it builds fine on [x86 32 bit](https://buildd.debian.org/status/fetch.php?pkg=casacore&arch=i386&ver=3.0.0-3&stamp=1542884655&raw=0).
=> Fix another compile error in LatticeStatistics

COPYING
Almost all source files already mention the Library GPL (and have done
so since 1997). Having the COPYING file different from the source files
is confusing.
Closes #834
=> Replace GPLv2.0 by LGPLv2.0 in COPYING

tables/DataMan/StManColumn.cc, tables/DataMan/StManColumn.h
Today while playing with the Adios2StMan I was surprised to see a
reference to putArray in my error messages, as I was actually juggling
with the putSlice* methods. I dug a bit and realized that the error
message was misleading. This patch fixes that, giving the correct method
name in the error message.
=> Correct method name in error messages

tables/DataMan/Adios2StMan.cc, tables/DataMan/Adios2StMan.h, tables/DataMan/Adios2StManColumn.cc, tables/DataMan/Adios2StManColumn.h, tables/DataMan/Adios2StManImpl.h, tables/Tables/BaseTable.cc
After playing with the Adios2StMan for a while now, including using it within the [OSKAR](https://github.com/OxfordSKA/OSKAR) simulator to write measurement sets, we have come up with the following set of fixes and improvements for it. They include:
* Adding `getSlice`/`setSlice` support
* Avoiding code duplication in the `Adios2StMan` and `Adios2StManColumn` classes
* Implemented `Adios2StMan` using a pimpl idiom to avoid passing on ADIOS-specific dependencies to users
* Improved the MPI checks on the `BaseTable` class, including error checking, code centralization and serialization of the initial MPI checks.
I've run these changes through @JasonRuonanWang already and he thinks they seem fine.
=> Further Adios2StMan fixes

python/Converters/PycArrayComCC.h, python/Converters/PycArrayComH.h, python/Converters/PycArrayNP.cc
Reading a very large column (> 32 GB) gives incorrect results.
It appeared that the C++-Python conversion used uInt instead of size_t, which had the effect that only (size modulo 2**32) was handled. This has been fixed.
=> python-casacore getcol gives incorrect result

ms/MSSel/MSSelection.h
This simply adds a comment to the getDDIDList documentation explicitly stating that the output vector might potentially be unsorted. CASA was hit by this in CAS-12283, hence the update to casacore.
=> Add note about potentially unsorted vector from getDDIDList()

lattices/Lattices/HDF5Lattice.h
For some of our work on CARTA, we need to read large slices of data to an allocated memory buffer directly (in this case, managed by a `std::vector`). The HDF5DataSet object's `get` method allows us to do so, but the HDF5Lattice currently does not expose the underlying HDF5DataSet object associated with that lattice. This PR adds a single accessor function which returns the HDF5DataSet. I have used `array()` rather than `dataset()` to be consistent with the existing `arrayName()` function.
=> adds accessor to underlying HDF5DataSet to HDF5Lattice

casa/HDF5/HDF5DataSet.cc
Currently, attempting to read a contiguous HDF5 dataset will always throw an error, because `H5Pget_chunk` returns an error value (-1) when a dataset does not have a chunk size. This PR modifies the `HDF5DataSet::open` function to skip reading of the chunk size for contiguous datasets.
=> Fix reading of contiguous HDF5 datasets

casa/Containers/Allocator.h
I'm having trouble getting casacore to open different measurement sets from multiple (~20) threads, resulting in crashes and messages that say that tables cannot be removed from the table cache. Helgrind identifies several race conditions, one of them being in the bulk allocator. This commit solves those race conditions. On a simple test application that opens two different measurement sets in two different threads, this fix decreases the number of helgrind errors from 124 to 71 in this test application.
When I run `make check` (somewhat to my surprise) I see several failures because of this edit. I'm quite confused why this is, but the old code generates a race condition so needs some kind of change, so I'm posting this for now as a pull request -- maybe someone else can comment on why …
=> Fix thread safety of bulk allocator

ms/MeasurementSets/MSTable.tcc, ms/MeasurementSets/MeasurementSet.cc, tables/CMakeLists.txt
When producing the commits for my last pull request #884 I was careless and didn't double-check that my last commit (which merged the latest changes on the `master` branch with mine) was fully correct (it definitely was before that last merge). It however was incorrect, as it didn't fully take into account the changes on the changes on the `master` branch, specifically the template arguments for the `MSTable` class, and it failed to build. Since Travis doesn't build MPI-enabled builds by default it didn't catch this either.
I've now double-checked that everything *actually* builds and that all tests pass.
In merging the latest changes from the `master` branch I've also started using the new `CONFIG`-based cmake lookup for the ADIOS2 libraries introduced in b185392. This worked out of the …
=> Fixes for latest MPI-communicator-enabled MS classes

casa/Utilities/Regex.cc, casa/Utilities/cregex.cc, casa/Utilities/test/tRegex.cc
This was fixed in PR #881 by using std::regex, but unfortunately gcc-4.8 has errors in the std::regex support. Hence that PR cannot be merged.
This PR fixes it in a simpler way by using a function static and presetting the syntax mode.
tRegex was extended with a parallel loop; helgrind did not report any error.
=> Fixed race conditions in Regex

CMakeLists.txt, casa/IO/MultiFile.cc, casa/IO/MultiFile.h, casa/IO/MultiFileBase.cc, casa/IO/MultiFileBase.h, casa/IO/MultiHDF5.cc, casa/IO/RegularFileIO.cc, casa/IO/RegularFileIO.h, casa/IO/test/tMultiFile.cc, tables/Tables/ColumnSet.cc, tables/Tables/StorageOption.cc, tables/Tables/StorageOption.h, tables/Tables/test/tTable.cc, tables/Tables/test/tTable.out
MultiFile got support for file creation with the O_DIRECT option (provided the OS supports it) to bypass the kernel's file cache. It makes the I/O behaviour much more predictable which is useful for some real-time applications. It means that new tables using the MultiFile option can be written with O_DIRECT. It is not (yet) possible to use O_DIRECT on existing tables.
Close #882
=> Added support for O_DIRECT

casa/BasicSL/STLIO.h, casa/BasicSL/test/tSTLIO.cc
This change adds a forward declaration for all `operator<<` overloads defined in STLIO.h *before* the declaration of the `showDataIter` template function.
This makes then usable in situations when the value type of a container is a container itself (e.g., `map<int, list<int>>`). In such situations the instantiation of `showDataIter` will eventually reference to `operator<<(ostream &, T &c)` with `T` being a container type, but those template functions are declared after the declaration of `showDataIter` itself. Apparently gcc is happy with this, but clang isn't, and trying to compile such an example fails.
The pull request includes also a small use case added to the `tSTLIO` test program. The program fails to compile with clang. I tried both versions 7.0 and 3.4, so it's safe to say that …
=> Forward declaration of operator<< overloads

lattices/Lattices/HDF5Lattice.h, lattices/Lattices/HDF5Lattice.tcc
A previous PR allowed contiguous HDF5 data sets to be opened correctly. However, we ran into issues when iterating through the data set, because the `HDF5DataSet` object's `tileShape` was left as an empty `IPosition`. 
This PR modifies `HDF5Lattice` to return a default tile shape for contiguous datasets, rather than the empty tile shape defined by the dataset. The default tile shape is calculated using `TiledShape::tiledShape`, similarly to how FITS files' tile shape is determined. 
I initially placed this functionality in `HDF5DataSet`, but then had linking issues, as `HDF5DataSet` belongs to `casa_casa` library, while `TiledShape` belongs to the `casa_lattices` library, and including it creates circular dependencies.
=> returns a default tile shape for contiguous HDF5 data sets

lattices/LRegions/LCRegionFixed.cc, lattices/LRegions/LCRegionFixed.h
I am @veggiesaurus's colleague on the CARTA project. We need to access the mask arrays of regions in order to implement our custom low-level code for reading region statistics in a fast and memory-efficient way from a rotated (XYZW -> ZYXW) image dataset in our HDF5 schema.
=> Add a public getter for the mask array to LCRegionFixed

casa/System/ObjectID2.cc, casa/System/test/tObjectID.cc
The intent of the `hashFunc` function clearly is to fill the individual bytes of an uInt variable with data coming from various fields via shifting and bitwise ORing of the individual bytes. However the current implementation used a *logical* OR operator. This meant that the four individual logical operations don't return an integer value but rather either true or false, which then gets converted into 1 or 0 when written into the uInt value, and then converted to true/false again during the subsequent logical operations. From the four values involved in the logical OR operations, only the sequential number can be zero, while the rest will definitely be different from zero (when the object is "not null"); therefore it is expected that hashFunc always returns 1.
The first commit in this …
=> ObjectID's hash function behavior fix

images/Images/ImageExprGram.cc, images/Images/ImageExprParse.cc, images/Images/test/tImageExpr.cc, tables/TaQL/TableGram.cc
In LEL it was not possible to have a colon as part of the file name, because it was always interpreted as a separator for mask or region. Now it is possible to use it in a quoted file name if the colon is escaped with a backslash.
Testing the code revealed that ImageExprGram did not behave properly when a recursive parse had to be done. This has been fixed. The same fix has been applied to TableGram.
=> Allow colon and fix recursive bison parsing

tables/Tables/TableProxy.cc
This fix deletes the TableDesc pointer allocated internally with new, similarly as done in TableProxy::getTableDescription().
Maybe using unique_ptr would be a better approach, but I'm not sure if there's any policy on this in casacore.
getColumnDescription() is used in CASA in the table tool, exposed via the getcoldesc() function.
=> Fix memory leak in TableProxy::getColumnDescription

casa/Arrays/ArrayPartMath.h
This is exactly the same as the previous pull request but I've just changed the <from> branch for my own reasons.
Issue is that MadfmFunc should <probably> inherit from ArrayFunctorBase. As it currently does not you cannot use this function as an argument to the slidingArrayMath method
=> Changed MadfmFunc so that it inherits from ArrayFunctorBase

python/Converters/PycArrayComCC.h, python/Converters/PycRecord.cc, python/Converters/PycValueHolder.cc
There is a Unicode converter for casacore strings, but not for
std::string (under Python 2). Rather than define one for std::string
(which would then be foisted on all extensions in the process), change
the few places I could find that use extract<std::string> to use
extract<String> instead (most of them immediately converted the result
to a String anyway).
=> Extract Python strings via casacore::String not std::string

python/Converters/PycBasicData.h
Closes #908. I also fixed up the indentation in this function so that I
could tell where things were going to go out of scope.
=> Fix memory leak when converting Python unicode to casa string

python/Converters/PycArrayComCC.h, python/Converters/PycArrayComH.h, python/Converters/PycArrayNP.cc
This converts numpy Unicode arrays by re-encoding from UTF-32 to UTF-8.
It is intended to supersede #909.
=> Handle numpy Unicode arrays

casa/casa.dox, tables/Tables/ArrayColumn.tcc, tables/Tables/test/tArrayColumnCellSlices.cc
ArrayColumn::getColumnCells was always using DataManager.getSlice without testing if it was supported. The same was true for putColumnCells. This has been fixed.
Close #899
=> Only use DataManager.get/putSlice if possible

msfits/MSFits/FitsIDItoMS.cc
Replicate what is done for array columns.  Fixes importing VLBA data
with only a single spectral window.
=> Allow double-precision in scalar FREQOFF column

tables/TaQL/ExprFuncNode.cc, tables/TaQL/TableGram.yy, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run, tables/TaQL/test/tTableGramFunc.cc
1. The result of the arg function on a complex function is an angle, so its unit should be set to rad.
2. A parse error could be given when a WITH clause was used followed by a select function with multiple arguments. This has been fixed.
=> Set unit of function arg to rad; fixed little parset bug

ms/MSSel/MSAntennaGram.yy, ms/MSSel/MSFeedGram.yy, ms/MSSel/MSFieldGram.cc, ms/MSSel/MSFieldGram.yy, ms/MSSel/MSSpwGram.yy, ms/MSSel/MSStateGram.yy
valgrind reported one more leak in MSFieldGram which occurred in case of an exception.
Furthermore, a few obsolete 'delete$$' were removed and '$$=$1' was inserted where needed.
Now all MSSel tests pass without leaks or errors.
=> Fixed remaining leaks and errors in MSSel

images/Images/ImageProxy.cc
ImageProxy did not support Int64 arrays. It was desirable to have this since Python3 uses Int64 by default.
=> Added support for Int64 arrays

images/Regions/RegionManager.cc, images/Regions/RegionManager.h
Fixes #933 by replacing the bare pointer with a unique_ptr.
See ticket for details about the leak.
While looking into this issue I noticed that the testing status of this RegionManager is a bit weak. There is a https://github.com/casacore/casacore/blob/master/images/Regions/test/tRegionManager.cc but is disabled in the CMakeLists and it won't compile as it uses stuff that is only available in CASA. It is actually a copy of https://open-bitbucket.nrao.edu/projects/CASA/repos/casa/browse/code/imageanalysis/Regions/test/tCasacRegionManager.cc.
In a separate CASA ticket I've managed to enable this tCasacRegionManager test (which also happened to be disabled in CASA!).
=> Fix memory leak (CoordinateSystem) in RegionManager::setcoordsys()

tables/TaQL/TaQLNodeDer.cc, tables/TaQL/TaQLNodeRep.cc, tables/TaQL/TaQLNodeRep.h, tables/TaQL/TableGram.cc, tables/TaQL/TableGram.h, tables/TaQL/TableGram.ll, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run
python-casascore#116 tells that something like $t::subtable results in a parse error because $t is substituted by "name", so the result is "name"::subtable giving a parse error.
This is fixed by this PR which accepts a mix of quoted and unquoted strings.
=> Support mix of quoted and unquoted strings

tables/TaQL/TableGram.ll, tables/TaQL/TableGram.yy, tables/TaQL/TableParse.cc, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run
A few improvements to TaQL:
- Improved error messages
- Better state handling in TableGram.ll/yy, so unquoted table name can be given in concatenation
- function name 'ampl' as synonym for 'amplitude'
=> Small TaQL improvements

tables/DataMan/Adios2StManColumn.cc, tables/DataMan/Adios2StManColumn.h, tables/DataMan/test/tAdios2StMan.cc
The default read mechanism of Adios2StMan could cause big performance issues when the reader application reads only one row at a time and repeat a large number of times. The problem was identified when we were running large-scale SKA simulations on Summit.
This PR added a pre-fetch cache mechanism into Adios2StMan so that it reads a number of rows at a time and put them into a buffer. Thus, when the reader reads a large number of contiguous rows one by one, it will significantly improve the performance.
=> Added read prefetch cache in Adios2StMan

msfits/MSFits/MSFitsInput.cc
With this fix importuvfits sets the antenna mount type correctly in the MS for UVFITS data with antennas that have Nasmyth mount types such as certain EHT data products and EVN data exported from AIPS.
=> Recognize Nasmyth mount types

casa/OS/Directory.cc
In lofar-astron/DP3#177 it is reported that casacore sometimes fails with
std exception detected: (/opt/lofar/casacore/src/casa/OS/Directory.cc : 304) Failed AlwaysAssert system(command.chars()) == 0
To avoid having to check the code what this means, I've improved that error msg a bit. The cause is a failing `cp` command (which could still be for various reasons...)
=> Improve error when executing `cp` fails

lattices/LatticeMath/Fit2D2.tcc, lattices/LatticeMath/test/tFit2D.cc
Ok this is a simple one.
One of my tests was failing as Fit2D could not find the correct minMax template for a MaskedArray. I found I had to include the correct header.
Its a one line addition. All the current tests pass. None of them seem to test estimate. Hang on. I'll extend the tFit2D test to do that.....
=> Fit2D::estimate using a Masked array in the minMax call. Needs the right template

casa/OS/Conversion.cc, casa/Utilities/GenSort.tcc
If a calculation of the number of threads previously yielded a value of zero,
replace it by a value of one.
AFAICT, the OpenMP specification states that a "num_threads" value must be a
positive integer or else the behavior is implementation defined. While the
meaning of "positive integer" appears undefined in the specification, it's usage
in that document suggests a value that is strictly greater than zero, which also
happens to agree with my intuitive sense of a minimum valid value of
"num_threads".
This bug originally appeared (for me) in Conversion.cc when using the OPARI2
tool (https://www.vi-hps.org/projects/score-p/) to instrument the casacore code,
while the bug apparently remains latent when using one of the standard compilers
without the tool.
Note that …
=> Prevent setting OpenMP num_threads to zero

tables/DataMan/Adios2StManColumn.cc, tables/DataMan/Adios2StManColumn.h
In Adios2StMan so far we have supported putting scalars and arrays into single cells, or into cell slides, but haven't supported single operations that span across either the whole column, or a slice of a column. Since we haven't advertised such support, the storage manager classes have resorted so
far to perform multiple cell-wise I/O operations, even when at the application level users perform a single write or read. This, in turn, has led us to have poor performance when using ADIOS2 as we have been hit by its bigger metadata-to-data ratio.
This commit adds support for column-wise operations. Whole column slices are fully supported, but partial column slices are supported only when a single slice is requested (requests spanning multiple slices will currently receive an exception).
This …
=> Adding more I/O patterns to Adios2StMan

.travis.yml, .travis/before_script.sh
Homebrew switched to installing CMake config files to find boost components, but apparently this does not work for boost-python. I think the actual fix should be done at the homebrew end ( https://github.com/Homebrew/homebrew-core/issues/44093 )
I disabled the python2 test on Travis Mac to make the test environment a bit easier.
=> Fix travis mac2

measures/apps/measuresdata/measuresdata.cc
Certain tables that used to be hosted by https://maia.usno.navy.mil/ser7/,
which has shut down for maintenance without replacement (thank you...)
=> Fix measuresdata.cc with new URLs

tables/DataMan/ISMColumn.cc, tables/DataMan/ISMColumn.h, tables/DataMan/test/tIncrementalStMan.cc
In class ISMColumn startRow_p and endRow_p might not be invalidated if the columnCache is invalidated. Hence, always set the cache.
Also do a small improvement in the logic.
Close #970
=> More fundamental fix for issue 970

casa/System/ObjectID2.cc
The previous version of this code stored the individual bytes of information into a char variable, which was later shifted to place its value into the final hash. This shifting was illegal though, as it took an 8-bit variable type and shifted it by 8, 16 and 24 places to the left. This might be the underlying reason causing #986, but even if it isn't it still deserves to be fixed.
The fix avoids casting the individual bytes through the char type, and instead it performs the masking and shifting in a single expression, keeping the original value types and avoiding UB. Additionally, the last byte is converted to uInt before bit shifting, as its original type is char.
=> Avoiding UB by not casting through char anymore

ms/MSOper/MSConcat.cc
Swap the rows corresponding to cros--polarization products in
DATA, MODEL_DATA, CORRECTED_DATA, WEIGHT, WEIGHT_SPECTRUM, SIGMA,
SIGMA_SPECTRUM, FLAG and FLAG_CATEGORY columns if necessary when
swapping antennas for a baseline.
=> Fix issue #977

tables/Tables/BaseTabIter.cc, tables/Tables/BaseTabIter.h
Currently, the TableIterator class has a parameter Option in all the constructors which defaults to TableIterator::ParSort. This parameter is propagated trough several classes:    TableIterator::TableIterator() -> BaseTable::makeIterator -> BaseTabIterator::BaseTabIterator()
However the later constructor BaseTabIterator::BaseTabIterator() simply ignores the option ParSort (whereas QuickSort, HeapSort and InsSort are supported.
This basically adds the support for ParSort as it is intended by adding the proper "else if".
=> Supports ParSort sorting algorithm in BaseTabIterator class

CMakeLists.txt
Although readline and sofa are advertised as optional, users have no way to actually control whether or not readline and sofa are used. The unguarded call to `find_package(Readline)` will create casacore libraries that link to readline libraries if they are found (and a similar situation holds with sofa). In some environments, this behavior is not desirable.
This PR allows users to state whether or not to build against and link casacore to the readline and sofa libraries through the use of `USE_READLINE` and `USE_SOFA` CMake options. I have verified that setting `USE_READLINE=OFF` results in casacore libraries that do not link to libreadline.so, even on systems where that library is present.
=> Allow user control of readline usage

casa/OS/test/tHostInfo.cc, casa/System/test/tObjectID.cc
This is a follow-up to the problems found during #1007
In tHostInfo an assertion was being made on the amount of time slept on the system as a way to ensure HostInfo::secondsFrom1970 worked as intended. This combination of sleeping plus checking the time difference was very sensible to how computers sleep, their current workload, etc, and the assertion actually broke in a Travis test under MacOS because the sleep(5) call slept either less than 4.9 or more than 5.1 seconds. A less precise but more correct assertion is simply sleeping for less time and assert that the difference is greater or equal than 0, which should always be true.
On the other hand, in tObjectID the byte in the hash coming from the PID can actually be zero 1/256th of the times when the PID of the process running the …
=> Adjusting tests expectations

.travis.yml, .travis/before_script.sh
This might the cause of cmake not being able to build python3 (i.e., the Headers/ directory is still pointing to python@2's). An alternative would be to pass down the include directory explicitly.
I will be force-pushing into this branch until things work -- so expect a couple of failures.
=> Fixing MacOS Travis builds

tables/Tables/TableLock.cc, tables/Tables/TableLock.h, tables/Tables/test/tTableLock.cc
Prebuilt packages such as CASA come with table locking enabled, but sometimes file systems fail on locking. In such cases it is useful to disable table locking by means of an aipsrc variable.
=> Added aipsrc option table.nolocking

casa/BasicSL/Complex.cc, casa/BasicSL/test/tComplex.cc
I noticed that the complex versions of asin and acos in casacore return the wrong sign for the imaginary part. In casacore, these two functions are custom implementations and don't use std::asin/std::acos. The std versions do return the right values.
I wrapped my head a bit around the question whether a flipped sign of asin/acos imaginary return value is really incorrect or not, or whether 'both answers are correct' and I believe it is really wrong: for the complex trig functions, for any input phase, the values have a unique output phase, hence an imaginary sign swap is wrong. Even if that were not the case, cos(acos) and sin(asin) do not return the same value in casacore's implementation, while they do for std's version.
I checked and I don't see any usage of complex asin/acos in …
=> Replace incorrect implementation of complex asin/acos with std versions

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h
Swap the data, weight and flags corresponding to cross-polarization
products if necessary when swapping antennas for a baseline.
=> Fix issue #1019

tables/DataMan/Adios2StMan.cc, tables/DataMan/Adios2StMan.h, tables/DataMan/Adios2StManColumn.cc, tables/DataMan/Adios2StManColumn.h, tables/DataMan/Adios2StManImpl.h
This patch ports the Adios2StManColumn class hierarchy to inherit
directly from StManBaseColumn (the new, 64bit-only interface) instead of
StManColumn (the old, 32bit-backwards-compatible one) and adjusts the
implementation to comply with the new methods taking rownr_t instead of
uInt. The Adios2StMan class itself (and its pimpl) also needed to be
adjusted, although the changes were minimal.
A major change that happened together with this porting was a small
refactoring of the internal Adios2StManColumn class hierarchy. The
Adios2StManColumn has always been the base class used by the many
AdiosStManColumnT<T> class template specializations, but the latter
contained a fair bit of code that could be moved down to the base class
with minimal changes. In this commit I thus adjusted and moved …
=> Port Adios2StMan to use 64bit row numbers

msfits/MSFits/MSFitsInput.cc
I believe this resolves the memory violation with uvfits. It was unrelated to either the 64bit row change or the lldb inspired potential fix.
=> must check getIndex return (CAS-12818)

tables/DataMan/VirtualTaQLColumn.cc, tables/DataMan/VirtualTaQLColumn.h, tables/DataMan/test/tVirtualTaQLColumn.cc
The ColumnCache increment was not set correctly (should be 0).
Also setMaxLen and setColumnShape were not handled; the latter caused an exception if a column was defined with a fixed shape.
=> Fixed VirtualTaQLColumn

msfits/MSFits/FitsIDItoMS.cc, scimath/Mathematics/FFTW.cc, scimath/Mathematics/FFTW.h
The FitsIDItoMS class is the only class that was still dependent on the FFTPack
Fortran code. By rewriting it to use FFTW, the FFTPack code can be removed.
This required implementing a wrapper for the real even FFT in the FFTW class,
as that was not available.
The FFTW class should be rewritten to have a more sensible interface. I've added
some TODO comments for that. Despite the use of a mutex, the FFTW wrapper is
also not thread safe.
This is related to the work in #1024 and #1017.
=> Use FFTW instead of FFTPack in Fits-IDI to MS table converter

casa/Utilities/Compare.cc, casa/Utilities/Compare.h, ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h, ms/MeasurementSets/test/tMSIter.cc, ms/MeasurementSets/test/tMSIter.out
A new constructor is created to support giving explicit comparison functions to the table sorting algorithms. This makes MSIter more generic. Eventually the other constructors could be removed if   all the code that uses MSIter (like VisibilityIterator* in CASA) moves to the new API.
Note that this new constructor doesn't support cached SORTED_TABLE, which could be considered legacy by now.
This work is in the context of CAS-8352 to allow the combination of SPW within subchunks.
=> Support explicit comparison functions for iteration grouping

casa/Utilities/MUString.cc, measures/Measures/test/tMeasure.cc, measures/Measures/test/tMeasure.out
Restores behaviour of this method that was changed in
commit d2e04b9ed56c59c5daf3a030d2c29ddca1e79bb2.
Fixes #1045
=> Restore minimaxNC behaviour

casa/Arrays/Cube.h, casa/Arrays/Matrix.h, casa/Arrays/test/tCube.cc, casa/Arrays/test/tMatrix.cc
In psuedo code, this didn't work anymore, causing Casa errors:
```
Cube cube(5, 1, 1);
cube = Vector(5);
```
It did "by accident" work for a Matrix, because Matrix didn't implement a specialization of assignment, causing
an implicit call conversion via the Matrix(const Array&) constructor which did allow this.
This "feature" allowing assignment from lower dim arrays isn't yet documented and is also not consistent. For example,
this isn't allowed:
```
Array arr(IPosition{5, 1, 1});
arr = Vector(5);
```
So in the nearby future it would be good if i) this were documented; and ii) this would be made consistent
between Array and Matrix/Cube classes. By doing so, the specialized assignment methods from Matrix and Cube could
be removed, so it would also simplify the code.
This PR also adds unit …
=> Solve issue when assigning from lower to higher dim array

casa/Arrays/Array.tcc, casa/Arrays/ArrayBase.cc, casa/Arrays/Vector.h, casa/Arrays/Vector.tcc, casa/Arrays/test/tArray.cc, casa/Arrays/test/tCube.cc, casa/Arrays/test/tMatrix.cc, casa/Arrays/test/tVector.cc
Code like this used to work, but didn't after the array refactor:
Matrix<int> matrix;
matrix = Vector<int>();
The same holds for Vector to Cube and Matrix to Cube assignment.
This has been fixed, and test cases have been added for these assignments.
=> Fix empty dim-changing assignment like matrix = Vector()

tables/DataMan/test/CMakeLists.txt
This commit removes the dependency that DataMan tests have on Boost's
unit testing framework. This was added in cd54d948f, where boost is
effectively used for unit testing some of the new array changes, but
it's definitely not needed by the DataMan tests, as none of them
includes boost or links against it.
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>
=> Remove boost dependency in DataMan tests

casa/Quanta/MVAngle.h, casa/Quanta/MVBaseline.cc, casa/Quanta/MVBaseline.h, casa/Quanta/MVDirection.cc, casa/Quanta/MVDirection.h, casa/Quanta/MVEarthMagnetic.cc, casa/Quanta/MVEarthMagnetic.h, casa/Quanta/MVTime.h, casa/Quanta/MVuvw.cc, casa/Quanta/MVuvw.h, casa/Quanta/QBase.cc, casa/Quanta/QBase.h, casa/Quanta/QVector.h, casa/Quanta/QVector.tcc, casa/Quanta/Quantum.h, casa/Quanta/Quantum.tcc, tables/DataMan/test/dRetypedArrayEngine.h, tables/DataMan/test/dVSCEngine.h, tables/Tables/test/tTableDesc.h
In C++11 generation of implicitly-declared copy assignment operator is deprecated if a user-provided copy constructor is given, and vice-versa. In new-ish versions of gcc (9+) a very visible set of warnings is issued because of this, and therefore the situation needed to be tackled.
These two commits remove a few user-provided methods that prevent the generation of other implicitly-defined ones. In all cases removing these user-defined methods leads to no loss, as the compiler will still implicitly define them, and with the expected behavior.
There was also a misleading comment in one of the constructors of the classes *deriving* from `MVPosition`: the comment above the constructor read "Copy constructor", but in reality the constructor took always an `const MVPosition &` argument. I …
=> Remove user provided methods

casa/HDF5/HDF5DataType.cc
H5free_memory was introduced in 1.8.13 and is the way one should free memory allocated via the HDF5 library. Using free has worked until now, but local tests against HDF5 1.12 are broken due to this (they segfault).
When building against HDF5 versions older than 1.8.13 we simply define H5free_memory = free. There is no clear statement in casacore about which HDF5 versions are supported, so I played it conservatively and avoided using the H5_VERSION_LE macro introduced in 1.8.7, and used a boolean logic combination to check the major/minor/release components of the HDF5 version at compile time.
=> Use H5free_memory instead of free

casa/OS/Directory.cc
Copying a dir causes a call to chmod. When this fails
(e.g. because a second process has deleted the dir in the mean time), Casacore
causes a very cryptic message. This PR improves the error message
somewhat.
=> Improve error message when chmod fails

casa/System/AppState.h, measures/Measures/MeasIERS.cc
CASA is moving toward supporting user configuration via a Python config file that is evaluated. These configuration settings are made available in C++ via the AppState class. There is already a dataPath( ) option which provides a list of directories which MeasIERS searches for IERS data. In general this has worked well, but some CASA stakeholders want to explicitly set the specific path that is used instead of leaving it up to a path search. This modification adds a measuresDir( ) option to AppState which take precedence over the dataPath( ) in MeasIERS.
This change should have no effect outside of CASA. The default value returned by measuresDir( ) is an empty string which MeasIERS ignores. To change this, a casacore user (like CASA) derives from AppState and provides a non empty string …
=> allow for direct specification of IERS data with AppState

casa/Quanta/Quantum.h, casa/Quanta/Quantum.tcc, casa/Quanta/test/tQuantum.cc
The removal of the copy-constructor in the `Quantum` class brought unintended consequences, breaking one of the CASA tests  (original report [here](https://github.com/casacore/casacore/commit/e5d8484b5108f0a890ddd9d494c2efcab738ce7c#r42799565) by @dmehring). This test is present in the casacore codebase, but is skipped by default as it requires some extra data hosted by NRAO, making the problem invisible to the Travis CI environment.
After some investigation, it turned out this was due to the different semantics of the copy constructor and copy assignment of the casacore Array classes (see [this explanation](https://github.com/casacore/casacore/commit/e5d8484b5108f0a890ddd9d494c2efcab738ce7c#r42992327)).
This PR brings back the user-defined copy-constructor, which needs to *assign* …
=> Restore Quantum user-defined copy constructor

msfits/MSFits/MSFitsIDI.cc
This improves upon commit 8f1127361ea745c9eecc78adc4c4c45e9f677f8b
by handling the case where the subtable contains a small amount
of data that has already been read when parsing the table header.
This fixes skipping the GATEMODL subtable found in VLBA pulsar
bin data.
=> Only skip over a subtable if there still is data to skip

casa/Arrays/IPosition.cc, casa/Arrays/test/tIPosition.cc
Benjamin Bean found a bug in the IPosition(const Array<long long>&) constructor. I've added
a test for this constructor, which indeed failed before the fix and now passes.
=> Fix IPosition constructor from Array<long long> and add test

casa/OS/HostInfo.cc, casa/OS/HostInfoDarwin.h, measures/Measures/test/tMeasMath.cc, measures/apps/measuresdata/measuresdata.cc, ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h, msfits/MSFits/MSFitsInput.cc, tables/DataMan/test/tIncrementalStMan.cc, tables/TaQL/test/tTableExprData.cc
This PR fixes some warnings that I have seen while compiling with g++ 10.2.
The warnings that are now fixed are:
```
casacore_github/casacore/casa/OS/HostInfo.cc: In static member function ‘static casacore::Double casacore::HostInfo::secondsFrom1970()’:
/home/cgarcia/PPS/src/casacore_github/casacore/casa/OS/HostInfo.cc:114:28: warning: ‘int ftime(timeb*)’ is deprecated [-Wdeprecated-declarations]
114 |     AlwaysAssert(ftime(&ftm) >= 0, AipsError);
casacore/msfits/MSFits/MSFitsInput.cc:1740:9: warning: unused variable ‘nrows’ [-Wunused-variable]
1740 |     Int nrows = bt.nrows();
casacore/tables/DataMan/test/tIncrementalStMan.cc:563:34: warning: comparison of integer expressions of different signedness: ‘int’ and ‘casacore::uInt’ {aka ‘unsigned int’} [-Wsign-compare]
563 | …
```
=> Fix compilation warnings with g++ 10.2

images/Images/ImageFITSConverter.tcc
Fixes #1075 - see issue for details.
=> FITS import: prevent 2^32 pixels overflow in loop counter, CAS-12837

casa/IO/test/tAipsIO.out, casa/IO/test/tByteIO.out, measures/TableMeasures/test/tTableMeasures.out, ms/MSSel/test/tMSSelection.out, tables/TaQL/test/tTaQLNode.out
Some of the test output reference files (.out) have diverged slightly (mainly spaces and return carriages) from what the tests are delivering. These differences are masked by the fact that casacore_floatcheck tool tries to see numerical differences, so they are not really a problem, but I thought it is good to have them aligned with the real output.
By the way, I come across this issue when running the tests in a machine without the python command installed (only python3 was installed). See also https://github.com/casacore/casacore/issues/983.
=> Minor changes to the test reference output files 

casa/Arrays/IPosition.cc
This PR fixes two small errors reported by valgrind in IPosition:
- uninitialized values in IPosition constructor. This has been triggered by the use of the IPosition constructor with just the length without specifying the values of the vector. I guess this constructor is not used much, but the unit test tCpp11Features uses it in lines 350 and 394.
- memory leak in IPosition move constructor.
=> Fix two erros reported by valgrind in IPosition

casa/Arrays/IPosition.cc, casa/Arrays/IPosition.h, casa/Arrays/MaskArrMath.tcc, casa/Arrays/test/tCpp11Features.cc
This reverts one part of #1079 (by @cquike). An IPosition does not need to be zeroed; it's part of its interface to leave it uninitialized by default. The valgrind error that cquike reported was actually an invalid use of IPosition, which I've corrected in the test.
It's open to discussion whether the IPosition *should* be like that or whether we better chose for the safe option, but currently it's often declared and then filled.
On top of that I also went through IPosition and used std::copy, std::fill and std::move where appropriate to replace for loops, and this simplifies/removes a lot of for statements.
=> Revert zeroing IPosition and some clean-up

.github/workflows/osx.yml
What I did:
- fix https://github.com/casacore/casacore/issues/1092
- re-enabled the build script in `.github/workflows/osx.yml` (removed `continue-on-error`)
- set Fortran compiler with `-DCMAKE_Fortran_COMPILER=gfortran-10` (GitHub Actions quirk)
- made minimal syntax changes to the build script so that it would work with GitHub Actions (e.g. `cd build` in each job)
- removed job count limit with `make -j` (reduces build time by 3 minutes!)
=> [casacore#1092] 👷 Fix OSX build on github actions

casa/OS/EnvVar.cc
setenv() is prefered over putenv() as descirbed in the POSIX standard:
https://pubs.opengroup.org/onlinepubs/9699919799/functions/putenv.html#
Addtionally this fix a small memory leak, since with putenv one
cannot modify the input buffer and therefore the buffer must remain allocated. With setenv() that's not the case and is therefore cleaner.
=> Use setenv() rather than putenv() to set environmental variables.

casa/Arrays/IPosition.cc, casa/Arrays/IPosition.h, casa/Arrays/test/tIPosition.cc, tables/DataMan/test/tTiledShapeStMan.cc
The old constructor was inefficient. To prepare for deprecation of this constructor,
I've added a Make() factory function which is to replace this constructor for
cases where a initializer list isn't possible (i.e. inside a macro).
=> Rewrite the IPosition(size, args...) constructor to use a parameter pack

tables/DataMan/Adios2StMan.cc, tables/DataMan/Adios2StMan.h, tables/DataMan/Adios2StManColumn.cc, tables/DataMan/Adios2StManColumn.h, tables/DataMan/test/tAdios2StMan.cc
There was a bug in Adios2StMan::setShape() which messed up some functionalities in TableCopy. The bug was identified when we recently tried to copy tables with huge sparse data produced by the ASKAP DINGO survey. This PR fixes the bug, and also includes a testing section in the tAdios2StMan test.
=> fixed a bug in Adios2StMan::setShape()

ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h, ms/MeasurementSets/test/tMSIter.cc, ms/MeasurementSets/test/tMSIter.out
Some metadata related to Data Description that has been computed at every iteration (i.e, when calling next()) is now computed less often to improve performance. This is driven by a change in CASA that now uses the MSIter class in the subchunk iteration loop of the VI/VB2. Usually each subchunk has single timestamp and there is no need to query metadata such as the DDID, SpwID or PolID, since this is done in the chunk iteration. With this PR only if the application asks for such information will MSIter compute (and cache) it, rather than computing it unconditionally in each next() call. In a test MS that saves 50 ms per subchunk iteration on a total budget of 400 ms.
Specifically:
1) If DDId is in the sorting columns then the information is always computed, since it likely that the …
=> MSIter: Compute DDId information on demand.

ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h, ms/MeasurementSets/test/tMSIter.cc, ms/MeasurementSets/test/tMSIter.out
Some metadata related to the feed that has been computed at every iteration (i.e, when calling next()) is now computed only when some feed related metadata is requested.
Similar to #1103 this is driven by a change in CASA that now uses the MSIter class in the subchunk iteration loop of the VI/VB2. Usually each subchunk has single timestamp and there is no need to query metadata related to the feed.
With this change, the MSIter next() method reduces its execution time from ~400 microseconds to  ~100 microseconds, which is a big improvement since the next() is called very often in each subchunk.
In particular, the feed related metadata is computed (and cached) when the following methods are called: CJones(), CJonesAll(),
receptorAngle(), receptorAngles(), getBeamOffsets(), …
=>  MSIter: Compute Feed information on demand.

casa/Utilities/Sort.cc, casa/Utilities/Sort.h, casa/Utilities/Sort.tcc, casa/Utilities/test/tSort.cc, casa/Utilities/test/tSort.out, ms/MeasurementSets/MSIter.cc, tables/Tables/BaseTabIter.cc, tables/Tables/BaseTabIter.h, tables/Tables/BaseTable.cc, tables/Tables/BaseTable.h, tables/Tables/TableIter.cc, tables/Tables/TableIter.h, tables/Tables/test/tTableIter.cc
This PR allows the caching of the iteration boundaries by the table iterators. Those boundaries are cheap to obtain while sorting the table in the first place.  
This avoids calling the sorting functions again when doing a next() iteration call as it has been done until now, since a vector with the iteration boundaries is cached and hence the information of which rows are part of the next iteration is readily available.
The mechanism is disable by default and controlled by a boolean switch in the  TableIterator constructor. For the time being only MSIter makes (partial) use of it.
As a reference, it has been verified that after this change the following CASA tests pass: test_agentflagger, test_bandpass, test_calanalysis, test_concat, test_coordsys, test_cvel, test_fixvis, test_flagcmd, …
=> TableIter: Add support for caching the iteration boundaries that have been created while sorting the tables

ms/MeasurementSets/MSIter.cc, ms/MeasurementSets/MSIter.h, ms/MeasurementSets/test/tMSIter.cc, ms/MeasurementSets/test/tMSIter.out
Similar to PR #1103  and #1104  some metadata like field attributes (fieldID, field name) and related attributes (restFrequency and phaseCenter) are now computed on demand only if it is asked for. For clients that don't require retrieving of field information for each iteration there is no need to compute that metadata.
Note that the relevant metadata accessors are phaseCenter(), fieldId(), fieldName(), restFrequency().
=> MSIter: Compute field attributes on demand.

tables/Tables/BaseTabIter.cc, tables/Tables/BaseTabIter.h, tables/Tables/RefTable.cc, tables/Tables/RefTable.h
This PR will use an existing RefTable created at construction time in the BaseTableIterator class  to avoid paying the cost of a RefTable creation every time the next() method is called to advance iteration.
When next() is called then the RefTable is reset with a call to RefTable::removeAllRow() and then the rows for this iteration are added. For that, also a convenient function addRownrRange() has been added to RefTable, to avoid calling addRownr() in a tight loop.
In a dataset with 10 rows per iteration the cost goes down from ~80 usecs per next() call to ~13 usecs.
Note that this PR depends on PR #1106 and should merged after that one.
=> Table iterator: Reuse a RefTable for each iteration

tables/DataMan/Adios2StMan.cc, tables/DataMan/Adios2StMan.h, tables/DataMan/Adios2StManImpl.h
This set of commits improves on the flexibility of the `Adios2StMan` by allow it to be configured via properties, and exposing its specification to external users. This allows us to remove a number of static members that were previously used to transmit state between different storage manager copies, and to flexibly configure instances of the storage manager from non-C++ environments like python or taql.
The storage manager also confused its "name" with its "type name", so that distinction has been clarified. This was changed in such a way that serialization from/to the `AipsIO` object remains backwards compatible.
cc: @JasonRuonanWang
=> Adios2stman improvements

ms/MSOper/MSDerivedValues.cc, msfits/MSFits/FitsIDItoMS.cc
This makes it possibly to apply the (co)-parallactic angle correction needed for VLBI data processing of data that includes antennas with an X-Y mount. An example of such an antenna is the 26m antenna at Hobart that is part of the Australian Long Baseline Array (LBA).
This code has been tested by applying the parallacting angle correction to data for LBA observation VT23 in both AIPS and CASA and comparing the phases on baselines that include the Hobart antenna.
=> Add support for X-Y mounts

ms/MSSel/MSTimeGram.yy, ms/MSSel/test/tMSTimeGram.out, ms/MSSel/test/tMSTimeGram.run
I noticed that timerange selection by "T+dT" syntax omits the sub-seconds value. More specifically, if we write "HH:MM:SS.ss", ".ss" part is omitted in parsing "T+dT" string. I think this is a bug because "T1~T2" syntax handles sub-seconds value properly. This pull request is possible fix for the bug.
=> fix insufficient precision issue in T+dT syntax

casa/Exceptions/Error2.cc, measures/Measures/MeasTable.cc, measures/Measures/MeasTable.h
Fixes #1126
I also did the same change for a few commented out Mutex instances in other files, to prevent future confusion.
=> Replace leftofer Mutex/ScopedMutexLock with std::mutex

tables/Tables/RefTable.cc
Fixes #1123. I've tested compilation on a i386 virtual machine, and it's fixed. However,
there are many failing unit tests on the i386 VM.
=> Fix compilation of RefTable on i386 platform

casa/System/test/tObjectID.cc
This fails one out of 256 times. Fixes #1130.
=> Remove assertion that does (time&0xff)!=0

casa/BasicSL/STLMath.h, casa/BasicSL/String.h, casa/Containers/test/tBlock.cc, casa/OS/test/tFile.cc, casa/OS/test/tPath.cc, casa/OS/test/tRegularFile.cc, lattices/LatticeMath/LattStatsSpecialize.cc, lattices/LatticeMath/LattStatsSpecialize.h, lattices/Lattices/test/tPixelCurve1D.cc, ms/MSOper/MSLister.cc, msfits/MSFits/MSFitsOutput.cc, scimath/Mathematics/test/dSparseDiff.cc, scimath/Mathematics/test/tFFTServer.cc, tables/TaQL/ExprNodeRep.cc, tables/Tables/NullTable.cc, tables/Tables/NullTable.h
Apple clang version 13.0.0 (clang-1300.0.29.3) gave several warnings which have been fixed.
Most warnings were about using std::move (if e.g. a Vector is returned as Array) or about self-assignment in test programs.
Close #1136
=> Fixed clang warnings

msfits/MSFits/MSFitsInput.cc, msfits/MSFits/MSFitsInput.h, msfits/MSFits/MSFitsOutput.cc
Follow the scheme documented in AIPS memo 117 (revised, 19 June 2017)
and use separate SUBARRAY, ANTENNA1 and ANTENNA2 random parameters
when antenna numbers larger than 255 are encountered when writing
UVFITS files.
Add support for reading such UVFITS files back in as well.
=> Add UVFITS support for large antenna numbers

.github/workflows/linux.yml, docker/ubuntu1804_clang.docker, docker/ubuntu1804_gcc.docker, docker/ubuntu2004_clang.docker, docker/ubuntu2004_gcc.docker
It seems that on the linux-based CI jobs, the tests don't run. The tests do run on OSX. This is an attempt to get the CI-jobs to run `make test`.
=> Try to get CI to run tests on linux

images/Images/ImageOpener.cc
This PR changes ImageOpener::openImage to check the function map before using the default open functions in casacore.
ImageOpener::openImage uses defined open functions for certain image types (including HDF5) before checking the function map, so there is no way to set a custom function for these types.  CARTA HDF5 images fail with casacore::HDF5Image; we have created a custom carta::CartaHdf5Image which we would like to open instead, using registerOpenImageFunction with type HDF5.
=> Check open func map before using defaults in ImageOpener

measures/Measures/MCDirection.cc, measures/Measures/test/tMeasJPL.cc, measures/Measures/test/tMeasJPL.out
This adds the possibility to point towards solar system offsets with an offset. For example, the MDirection `sun_offset(Quantity(3, "deg"), Quantity(2, "deg"), MDirection::SUN)` will point away from the sun center 3 degrees in the right ascension direction, 2 degrees in the declination direction.
Previously, the quantities given to any object in a `MDirection::SUN` or other solar system frame were ignored. With this change, we assume that previously for getting solar system coordinates, either the coordinates were omitted or set to zero.
=> Allow offsets to JPL coordinates

msfits/MSFits/FitsIDItoMS.cc
Fix a pasto that may affect importing GAIN_CURVE tables.  The code was
inspecting the wrang class variable to decide whether the GAIN_CURVE
table should be added to the MeasurementSet.  Fortunately the impact
of this bug was limited since the way the CASA importfitsidi task
uses the code results in the GAIN_CURVE tables getting created anyway.
=> Fix handling of FITS-IDI GAIN_CURVE tables

scimath_f/CMakeLists.txt
Compiling `fftpak.f` with newer versions of gcc (>= 10?) gfortran results in compile time errors. This change allows builds to complete.  I realize that fftpack is deprecated, but some versions of CASA still require it. A more targeted option to try is `-fallow-argument-mismatch`. Testing fortran compiler options in CMake seems not to be possible with the minimum CMake version for casacore, and I'm not sure how to deal with that possibility. I'm also not sure how much effort is warranted here --- I wouldn't mind if the PR were not merged.
=> Add -std=legacy compiler option for scimath_f

scimath_f/CMakeLists.txt
This reverts commit c32cf89d81e697b64b89d8e9248d63419c1e8da1 as requested by @aroffringa in #1134.
=> Revert "Add -std=legacy compiler option for scimath_f"

tables/TaQL/TaQLNode.h, tables/TaQL/TaQLNodeDer.cc, tables/TaQL/TaQLNodeDer.h
TaQLNode and associated classes were using raw pointers at a few places. It has been replaced by unique_ptr. Furthermore, restore now returns a TaQLNode object instead of a pointer.
=> Avoid possible TaQLNode memory leaks

tables/Dysco/dyscostman.cc, tables/Dysco/dyscostman.h, tables/Dysco/dyscostmancol.h, tables/Dysco/threadeddyscocolumn.cc, tables/Dysco/threadeddyscocolumn.h
The Dysco storage manager has been changed to use 64-bit row numbers.
Furthermore, it has been assured that the array storage is contiguous by using getStorage.
Close #1139
=> Use 64-bit rownrs in Dysco

images/Regions/WCExtension.cc
WCExtension uses the construct &x[0], where x can be a std::vector of length 0. The behavior in that case is undefined, and the _GLIBCXX_ASSERTIONS compile flag causes an Abort and core dump at runtime.  CARTA creates a carta-casacore RPM containing CASA imageanalysis and casacore, and we think rpmbuild sets this compile flag.
WCExtension::doToLCRegion sets the stretch and extension axes in std::vector, which may be length 0 if these axes are not required.  But then the empty vector is sorted with GenSortIndirect, causing a core dump when the compile flag is used:
GenSortIndirect<Int,uInt>::sort (strinx, &(tmpstr[0]), ndstr);
/usr/include/c++/8/bits/stl_vector.h:932: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = …
=> WCExtension sort extension/stretch axes only if nonzero size

casa/Arrays/Array.tcc
Compilation was broken with Intel compilers as "uninitialized" was declared but never defined.
=> Array: Fix static member not being defined.

tables/DataMan/Adios2StMan.cc, tables/DataMan/Adios2StMan.h, tables/DataMan/Adios2StManImpl.h, tables/DataMan/test/tAdios2StMan.cc
@rtobar Please help review.
After experimenting various data compression techniques in ADIOS2 for a while, we want to finalize the API so the ASKAP DINGO project can incorporate this into their production workflow.
This PR adds a std::vector<std::map<std::string, std::string>> typed container of parameters into Adios2StMan::Adios2StMan(), to pass data compression parameters from user applications down to the ADIOS2 library. Each element in std::vector<std::map<std::string, std::string>> is a map containing necessary information to add an ADIOS2 operator (data compressor in this case). A parameter map must have the key *Operator* to specify the data compressor, and the key *Variable* to specify the CTDS column (ADIOS2 variable) that this operator is attaching to. 
So far, the Bzip2, Blosc …
=> Add operator parameters in Adios2StMan for data compression

images/Regions/RFReaderWriter.cc
The code clearly assigns 4 values into the vector, but it only requests
space for 2. This was warned by g++ 11.2.
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>
=> Create vector of correct size

measures/TableMeasures/ArrayMeasColumn.h
It looks like this doc was originally for an ROArrayMeasColumn, which no longer exists.
=> Fix doc error in ArrayMeasColumn

casa/Arrays/Vector.h, casa/Arrays/test/tVector.cc, images/Regions/RFReaderWriter.cc, ms/MSSel/MSArrayParse.h, ms/MSSel/MSObservationParse.h, ms/MSSel/MSScanParse.h
Before this MR, it is possible to implicitly convert a std::vector to a casacore::Vector, for example:
std::vector<int> foo();
casacore::Vector<int> v = foo();
would be fine. Since this can be expensive, this should not be done implicitly. There are several bugs in DP3 because of this, and I also found one casacore typo-bug (in RFReaderWriter.cc) by making this conversion explicit.
It might require a few fixes in software that uses casacore, particularly casa (but the upside is that it might also highlight some bugs :) ).
The related DP3 MR is here: https://git.astron.nl/RD/DP3/-/merge_requests/661
=> Make conversion from std::vector to casacore::Vector explicit

lattices/Lattices/ArrayLattice.tcc
A trivial change "fixing" issue #1171 - added assert to ensure the lattice has more dimensions than the source before adding degenerate axes. As discussed on the ticket, it is possible to support ldim < sdim case as well via reform method. However, mismatched dimensions in this particular operation is a sloppy code. So perhaps, it is better to detect this condition with an assertion rather than sweep under the carpet. 
I can easily implement the support of the ldim < sdim case, if others think it is worth doing.
=> Added assert to detect issue #1171

tables/Tables/BaseTable.h
CC: @pelahi who will be interested in this, as well as @JasonRuonanWang
So far most of the applications we had used with MPI (and the
Adios2StMan) were either writing a single Measurement Set or Table
across all MPI ranks, or passed an explicit MPI communicator to the
Table and Adios2StMan constructors. This has worked well, but means that
the default value of BaseTable.itsMpiComm (MPI_COMM_WORLD) hasn't been
relevant.
New tests have revealed that this is not a great default value. In
particular we have tried running Yandasoft (an MPI-enabled application)
against an MPI-enabled casacore. Until now all of the data written by
Yandasoft doesn't happen with the Adios2StMan, and thus it is expected
that each rank writes its own Tables. Without changing each Table
creation invocation in …
=> Default BaseTable's MPI communicator to SELF

ms/MSSel/MSSpwIndex.cc
Fixed a bug where a 0 length vector may get addressed (in the min …
…max calls e.g min(chanIn)) in function matchFrequencyRange.  this happens (CAS-13843) when in the first pass the freqrange appear to be in a given spw min and max frequencies but on second pass the range falls in gaps between channels.  Fixed it by making the second pass check (numMatched can be 0) before trying to decide to address the vectors used.
Also removed a commented out piece of code in that function
=>   Fixed a bug where a 0 length vactor was being sent to min or max.

CMakeLists.txt, docker/py36_wheel.docker, docker/py37_wheel.docker, docker/py38_wheel.docker, docker/py39_wheel.docker, docker/ubuntu2004_clang.docker, docker/ubuntu2004_gcc.docker, docker/ubuntu2204_clang.docker, docker/ubuntu2204_gcc.docker
This is about 2,5 years overdue... We could also remove all magic for working with multiple python versions, but I think for now just setting the right default is quickest and best. We may even need the logic again for python4.
=> Build python3 by default, not python2

CMakeLists.txt, casacore.pc.in
Using pkg-config files (https://en.wikipedia.org/wiki/Pkg-config) is a convenient way for clients of casacore to get the compiler and linker flags needed to develop an application that uses casa. This pull request adds support for the creation and installation of a casacore.pc file that can be used for such purpose.
The need for this comes from casa, which traditionally has been keeping internal knowledge and how to compile against casacore. The idea here is to remove such knowledge from casa itself and leave it to the casacore installation to provide such information in a standard way.
=> Add support for installation of pkg-config files

coordinates/Coordinates/Coordinate.cc, measures/Measures/MCFrequency.cc, measures/Measures/MeasMath.cc
Changes aim to speedup frequency frame conversion by reducing memory allocation and deallocation. I'm sorry that many whitespace changes are included, especially in Coordinate.cc. Major changes of Coordinate.cc is L977-1036.
I carried out hot spot analysis on the imaging (convolutional gridding) of single dish data using CASA's tsdimaging task. Test data contains about 70000 rows with 2048 channels and 2 polarizations. Roughly 10^8 frequency conversions are required. The screenshots below are the result of hot spot analysis of original code. You can see that significant fraction of CPU time was spent for `operator new` (please see Summary figure), which is very likely to accompany extra CPU time to execute constructor code. Indeed, constructor was one of the bottleneck of frequency …
=> Speedup frame conversion

casacore.pc.in
The WCSLIB headers are included in public casacore headers, hence the flags to discover the WCSLIB library must also be propagated.
This is a small correction patch on previous PR #1202 .
=> Add wcslib includes to the clients of casacore.

tables/Tables/BaseTabIter.cc, tables/Tables/BaseTabIter.h, tables/Tables/BaseTable.cc, tables/Tables/BaseTable.h, tables/Tables/ConcatTable.h, tables/Tables/MemoryTable.cc, tables/Tables/NullTable.cc, tables/Tables/NullTable.h, tables/Tables/PlainTable.cc, tables/Tables/RefTable.cc, tables/Tables/RefTable.h, tables/Tables/Table.cc, tables/Tables/Table.h, tables/Tables/TableColumn.cc
The Table object used its own (old) way of counting BaseTable references. It has been replaced by shared_ptr<BaseTable>.
However, it is somewhat tricky because not all BaseTable references in DataManager objects can be counted (otherwise mutual referencing occurs). Therefore the actual pointer in a Table object is still a raw pointer to BaseTable. A weak_ptr (in the BaseTable object itself) it used to created shared_ptr as needed.
The code has been run through valgrind without any error or leak.
=> Use shared_ptr instead of own reference counting of BaseTable

casa/Utilities.h, tables/Tables/TableRecord.h
When trying to compile CASA with an updated casacore, we noticed that there is a leftover include of Notice.h after the removal done in #1185, in a Utilities.h that is presumably only used from CASA.
This PR removes that include and fixes CASA compilation. It also removes a comment that refers to Notice.
=> Remove Notice leftovers

docker/make_images.sh, docker/py310_wheel.docker, docker/py36_wheel.docker, docker/py37_wheel.docker, docker/py38_wheel.docker, docker/py39_wheel.docker
These are the docker images that I just used for deploying python-casacore 3.5.
=> Update python docker images

casa/Containers/Record.h
When Record.h was changed, it was forgotten to add the keyword override to function removeField which resulted in compiler warnings (with clang). This has been fixed.
Furthermore, the indentation of some lines has been improved.
=> Add missing override keyword to removeField

casa/BasicSL/String.h, casa/BasicSL/test/tString.cc
Having a hash function for String makes it possible to use std::unordered_set<String> (or unordered_map).
=> Add hash function to String

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
As described in the VLBA Sensitivity Upgrade Memo 52, new versions of the DiFX correlator will apply the van Vleck when requested to do so.  This will be signalled by a new keyword in the FITS header of FITS-IDI output.  See
https://library.nrao.edu/public/memos/vlba/up/VLBASU_52.pdf
for more details.
Recognize this new keyword and skip the van Vleck correction if it is set to a non-zero value.
=> Skip van Vleck corrections based on new FITS-IDI keyword

tables/TaQL/TaQLNodeDer.cc, tables/TaQL/TaQLNodeDer.h, tables/TaQL/TaQLNodeHandler.cc, tables/TaQL/TaQLNodeHandler.h, tables/TaQL/TableGram.ll, tables/TaQL/TableGram.yy, tables/TaQL/test/tTaQLNode.out, tables/TaQL/test/tTaQLNode.run
This is the first part of the changes for support of the JOIN clause in TaQL.
This part contains the changes in the scanner/parser and the code to handle the result from the parser and store it in a tree. Handling the result tree is done in a separate PR.
The syntax of the join looks like:
select t1.col1, t2.col2, ... from table table1 t1 JOIN table2 t2 ON condition JOIN table3 t3 ON condition ... WHERE ...
Theta joins (implicit joins in the SELECT clause) are not supported. They are discouraged in SQL.
=> First stage of join clause in TaQL

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
Correction of the autocorrelations in the lag domain can only be
done properly if the correlator has zero-padded the data.  Handle
the case where data has not been zero-padded and assume this is
the default as DiFX doesn't zero-pad.
The VLBA correlator indicates whether data has been zero-padded by
setting the ZERO_PAD keyword in the MODEL_COMPS table to a non-zero
value.  Use this to override the default of assuming no zero-padding
has been done.
=> Handle VLBA/DiFX data without zero-padding correctly 

docker/make_images.sh, docker/py311_wheel.docker
Added support for building Python 3.11 docker image. Dropped support for Python 3.6, which is EOL.
=> Add Python 3.11 support

coordinates/Coordinates/SpectralCoordinate.cc
These two functions use a static 1-element Vector to avoid allocations on each invocation; however these static vectors are shared across multiple threads, leading to race conditions on unlocked data access and therefore unexpected results.
This commit adds the thread_local specifier on these static variables such that in multi-threaded scenarios each thread ends up with its own static copy of the variable, thus avoiding unlocked data shared across threads.
This issue was originally reported in #1200, and then more specifically in #1217.
Signed-off-by: Rodrigo Tobar <rtobar@icrar.org>
=> Fix data race in SpectralCoordinate's toWorld/toPixel

lattices/LatticeMath/test/tLatticeStatistics.cc, tables/DataMan/DataManagerColumn.cc, tables/DataMan/DataManagerColumn.h, tables/DataMan/test/tExternalStManNew.cc, tables/TaQL/ExprGroupAggrFuncArray.cc, tables/TaQL/ExprNodeSetElem.cc
Some incorrect DebugAssert lines, resulting in build errors, have been fixed.
tLatticeStatistics fails due to a DebugAssert in LatticeRegion. This looks like a serious error which has to be fixed by @dmehring. For the time being the offending code is not used in debug mode.
=> Fix DebugAssert problems

build-tools/casacore_memcheck
Valgrind gave the following warning about an old option. casacore-memcheck has been updated accordingly.
==3887808== Warning: --workaround-gcc296-bugs=yes is deprecated.
==3887808== Warning: Instead use: --ignore-range-below-sp=1024-1
=> Update valgrind option

derivedmscal/DerivedMC/Register.cc, tables/TaQL/ExprNode.cc, tables/TaQL/ExprNodeSet.cc, tables/TaQL/ExprNodeSet.h, tables/TaQL/ExprNodeSetElem.cc, tables/apps/taql.cc
- Fix indentation of derivedmscal help info
- Fix problem that shape([DATA]) returned an empty shape because ExprNodeSet did not set ndim and shape
- Catch exception in interactive mode in taql program, so it continues in case of errors
- Optimize IIF in case the condition is a constant scalar
=> Fix a few small TaQL issues

casa/Arrays/ArrayMath.h, casa/Arrays/ArrayMath.tcc, lattices/LEL/LELFunction2.cc, tables/TaQL/ExprFuncNodeArray.cc, tables/TaQL/MArrayMath.h, tables/TaQL/test/tExprNode.cc, tables/TaQL/test/tMArrayMath.cc
The pow function in ArrayMath only supported a mix of scalar and array, but a scalar exponent could only be of type double. This has been changed to T. An extra pow function has been added to make it possible to have a real exponent for a complex array.
LatticeMath and MArrayMath have been changed accordingly.
Close #1241
=> Add pow function of std::complex<T> and T

tables/TaQL/ExprNode.h
After removing ExprNode::tabe(), DP3 does no longer compile. We can easily restore backwards compatibility by adding a new table() function that uses the new getTableInfo() function, which replaced the table() function.
=> Restore ExprNode::table()

tables/TaQL/ExprNode.h
Avoid referencing the Table in a temporary TableExprInfo object. Copy the Table instead.
=> Avoid referencing a temporary Table

ms/MSOper/MSLister.cc
The cast of the result from rint() to (Int) in this line: https://github.com/casacore/casacore/blob/990a7e0e4108d1b39534aa918f675fff27baf4d3/ms/MSOper/MSLister.cc#L909 produces an undefined behavior that with more modern GCCs and the optimization flag `-ftree-vrp` enabled (it is included in `-O2`) makes the MSLister crash in a CASA task test. 
Besides the potential crash that happens when (max(phase)+0.5 < 0), dependent on how the undefined cast behaves in practice, the code is miscalculating that "order" of the phase array, as it assumes that the largest values in (absolute value) are positive.
This patch prevents that `log10("negative value")` by adding an `abs()` around the `max()`, and also uses the same function in all the lines that make a similar calculation for other MS columns / …
=> MSLister: prevent undefined behavior from 'log10("negative value") casted to int' that produces crashes in the CASA task listvis with newer GCCs

casa/BasicSL/Constants.cc, casa/BasicSL/Constants.h, casa/BasicSL/test/tConstants.cc, casa/BasicSL/test/tConstants.out, casa/Quanta/UnitMap2.cc, casa/Quanta/test/tUnit.out
The new SI prefixes quetta, ronna, ronto and quecto have been added.
Close #1256
=> Add new unit prefixes

tables/DataMan/MSMIndColumn.cc, tables/DataMan/MSMIndColumn.h
The change makes the clear function obsolete, so the class becomes more like a typical RAII object.
=> Make a destructor noexcept

casa/BasicSL/String.h
Casa build fails with the attached error when using the latest Casacore version: 
In file included from casacore/casacore/casa/Exceptions/Error.h:31:0,
from binding/source/conversions_python.cc:6:
casacore/casacore/casa/BasicSL/String.h:1039:13: error: specialization of ‘template<class _Tp> struct std::hash’ in different namespace [-fpermissive]
struct std::hash<casacore::String>
This patch fixes the compilation error.
=> Fix String.h hash namespace

images/Images/ImageUtilities2.tcc
PR #1280 missed a ptr() call in ImageUtilities2.tcc
=> Change ImageUtilities2.tcc outImage.ptr() to get()

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
While there are issues with correction of the autocorrelations in
the lag domain for data that has not been zero-padded in the
correlator, the default in AIPS is to do it anyway.  For now it
is better to stay aligned with what AIPS does.
=> Revert zeropad

ms/MSSel/MSSpwIndex.cc
Fixed line is inside two for loops: one for spw using index "i" and another for freqList using index "j". Here, array indices are mixed up so that "i" is used for freqList. Correct index should be "j".
This bug caused invalid memory access. In one of CASA's unit test, sdimaging_test_selection.test_spw_id_default_frequency, valgrind reported the following invalid memory access:
```
==1117991== Invalid read of size 4
==1117991==    at 0xE2EE9098: casa6core::MSSpwIndex::convertToChannelIndex(casa6core::Vector<int, std::allocator<int> > const&, casa6core::Vector<float, std::allocator<float> > const&, int&) (in /work/dev/nakazato/git/casa6/casatools/build/lib.linux-x86_64-3.6/casatools/__casac__/lib/libcasatools.cpython-36m-x86_64-linux-gnu.so)
==1117991==    by 0xE2EC9600: MSSpwGramparse() …
```
=> Fix array indexing bug that causes invalid memory access in ms spw selection.

fits/FITS/fitsio.cc
Older FITS-IDI from the VLBA archive have an extra record filled with zeroes after the last HDU of the file.  This causes the FITS code in casacore to read the last HDU over and over again.  Fix this by signalling the end of file even if there are remaining bytes after the last HDU.
=> Fix reading FITS files with extra bytes after last HDU

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h
A CASA user dug out some that from the VLBA archive that uses multiple frequency setups in a single FITS-IDI. This appeared to work (after working around the issue address in #1267) but the CASA listobs complained about DATA_DESC_IDs in that are not found in the DATA_DESCRIPTION table. The first commit in this series addresses this
issue. The second commit then adds support for recognizing specific frequency setups in flagging information in the FITS-IDI FLAG table.
=> Fixes for importing FITS-IDI files with multiple frequency setups

msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
There is some interest to process older VLBA data that was correlated with the old VLBA hardware correlator with CASA.
This needs some additional corrections in the FITS-IDI import code which are implemented in this ticket.
Since this depends on the changes in pull requests #1267 and #1268 I've marked this pull request as draft for now.
=> Add support for older VLBA archival data

python/Converters/PycArray.cc, python/Converters/PycBasicData.h
A build warning said that std::move should be used at a few places.
This has been fixed as well as the indentation that was off at a few places.
=> Fix build warnings and indentation

lattices/LRegions/LCSlicer.cc, lattices/LRegions/test/tLCSlicer.cc
The compiler warned about using MimicSource as a float number, because it is not exact.
The code has been changed to be more relaxed in the test on MimicSource. It appeared that the test program did not test on it, so MimicSource tests have been added.
=> Fix build warning in LCSLicer

tables/Dysco/bytepacker.h
It appears GCC 13.1 no longer includes standard C types and requires explicit inclusion of cstdint.
=> add C-style header to fix GCC 13.1 compile error on uint16_t 

CMakeLists.txt
This changes behaviour due to enabling compiler specific extensions by setting e.g. `-std=gnu++11` instead of `-std=c++11` when building with gcc. This might be considered desirable (see #1314) or not, in the latter case additionally `set(CMAKE_CXX_EXTENSIONS OFF)` would keep the `-std=c++11`.
=> Use CMAKE_CXX_STANDARD instead of manually implementing C++ standard selection

CMakeLists.txt, casa/Containers/Allocator.h
C++20 has removed a few deprecated functions, in particular related to allocators. While it might take a while before we want to compile casacore by default with c++20, projects that make use of Casacore and C++20 also fail to compile because casacore headers do not compile, which is probably becoming more standard in the near future.
In this MR I provided a work-around fix to the allocators in Casacore. I should mention though that the way Casacore uses allocators is deprecated, and probably also unnecessary. One of the places where it is used extensively, is in the Block class, which by itself is also easily replaced by something from std, that would also have proper move semantics. So a future task could be te remove all allocator and block functionality, as to simplify the codebase.
=> Fix compilation when using C++20

casa/Utilities/Assert.tcc
Using the latter triggers a warning on (for example) recent macOS versions as it is inherently unsafe to use.
Fixes #1306
=> Use snprintf instead of sprintf

lattices/LatticeMath/LatticeCleaner.h, lattices/LatticeMath/LatticeCleaner.tcc
This is a trivial pull request fixing constness in LatticeCleaner<T>::setMask input parameter. The method doesn't change the input mask lattice (and shouldn't conceptually), so having it passed via const reference (i.e. the same way as it is done for the dirty image and PSF) seems to be more appropriate.
I've also done few minor tweaks to the body of the method which do not alter the functionality (making use of previously unused variables).
P.S. I also noticed that MultiTermLatticeCleaner class has a bit of technical debt / needs some work, if it is working at all (in contrast to LatticeCleaner we don't use it in ASKAPsoft and reimplemented the same algorithm some other way, probably for a reason). Although this class is derived from LatticeCleaner, it does not override setMask method …
=> fixed constness in LatticeCleaner<T>::setMask parameter

ms/MSOper/MSLister.cc
Casa test test_task_listvis crashes when built on macOS Ventura/Clang 14. When maxDigitsToPrint gets an array of zeroes,  log10(0) returns -inf, which then gets turned into comparison of 1 and maximum int value. This patch returns 1 when the max array value is 0. Casa ticket CAS-14214.
=> Guard against log10(0) in MSLister.cc

docker/make_images.sh, docker/py312_wheel.docker, ms/MSOper/MSLister.cc
Add generation of Python 3.12 wheels.
Also changed the name of the generated docker image files to contain the output of `git describe --tags` instead of the hard-coded `master`.
=> Add py312 wheels

ms/MSOper/MSConcat.cc, ms/MSOper/MSConcat.h, msfits/MSFits/FitsIDItoMS.cc, msfits/MSFits/FitsIDItoMS.h, msfits/MSFits/MSFitsIDI.cc
=> Add support for Earth Orientation Parameters

.github/workflows/docker.yml
The new 'docker' GitHub workflow uses a variable to determine the name of the default branch in the repository. However, it turns out that this variable can only be used in workflow _templates_. It is also not possible to use the `github.event` family of variables in the `on:` clause. So, unfortunately, the only way to currently do this is to use a hard-coded name: `'master'`
=> Fix docker GitHub workflow

coordinates/Coordinates/ObsInfo.cc
This will make sure an ObsInfo object can be created, even when no Observatories table is present. With this change, also Images can be created without having an Observatories table.
Fixes #1321
=> Make ObsInfo work without Observatories table

tables/Dysco/bytepacker.h, tables/Dysco/threadeddyscocolumn.cc
#1166 fixed Dysco to support non-contiguous arrays, but introduced a small issue which is fixed in this PR.
=> Fix a previous contiguous array fix in Dysco

msfits/MSFits/MSFitsOutput.cc
Implemented by Dirk Petry (@petry)
Fixes #1340
=> Make export to UVFits work with non-constant receptor angles

.github/workflows/osx.yml
runs tests on macos-13 (x68) and macos-14 (arm64)
I needed to pin boost to 1.83 because of this issue https://github.com/casacore/casacore/issues/1348 
Tests pass on macos-13, but two fail on macos-14 due to what appears to be floating point discrepancies
```txt
99% tests passed, 2 tests failed out of 493
Total Test time (real) =  79.27 sec
The following tests FAILED:
226 - tLSQaips (Failed)
227 - tLSQFit (Failed)
226/493 Test #226: tLSQaips .........................***Failed    0.07 sec
User time: 0
User time: 0
User time: 0
User time: 0
User time: 0
User time: 0
20,26c20,26
< Sol0: 1, 0.00582354, 0.00582354
< Sol1: 2, 0.00582354, 0.00582354
< Sol2: 0, 0.00582354, 0.00582354
< Sol3: 0, 0.00582354, 0.00582354
< Sol4: 0, 0.00582354, 0.00582354
< Sol5: 0, 0.00582354, 0.00582354
< Errors: …
```
=> Fix macOS CI

mirlib/uvio.c
This PR fixes #1344 and supersedes #1345
CASA and CARTA users still require support for MIRIAD images which prevents them from being removed.
fixes #1345
=> Fix gcc14 compile

casa/Containers/RecordDescRep.cc, casa/Json/JsonOut.cc, casa/OS/File.cc, casa/System/Casarc.cc, casa/System/ObjectID2.cc, fits/FITS/BinTable.cc, fits/FITS/FITSTable2.cc, fits/FITS/fits.cc, fits/FITS/fits.h, fits/FITS/fitsio.cc, fits/FITS/hdu2.cc, fits/FITS/test/tBinTable.cc, fits/FITS/test/tfits5.cc, lattices/LatticeMath/LatticeStatistics.tcc, tables/DataMan/DataManager.cc, tables/DataMan/ISMIndColumn.cc, tables/DataMan/StIndArrAIO.cc, tables/DataMan/TSMFile.cc, tables/DataMan/test/tForwardCol.cc, tables/DataMan/test/tForwardColRow.cc, tables/DataMan/test/tStArrayFile.cc, tables/DataMan/test/tStMan.cc, tables/DataMan/test/tVirtualTaQLColumn.cc, tables/Tables/ReadAsciiTable.cc, tables/Tables/TableProxy.cc, tables/Tables/test/tColumnsIndex.cc, tables/Tables/test/tConcatTable.cc, tables/Tables/test/tConcatTable2.cc, tables/Tables/test/tTable.cc, tables/Tables/test/tTable_2.cc
clang warned that the insecure sprintf should be replaced by snprintf.
It was easy to do; only fits.h/cc required a bit more work.
=> Replace insecure sprintf by snprintf

.github/workflows/osx.yml
This change fixes the macOS CI. It's currently broken because `gfortran` is not symlinked correctly in the brew-installed gcc of the GitHub Actions macOS images.
=> macos CI: use gfortran from brew gcc

tables/DataMan/Adios2StMan.cc
A change in the most recent ADIOS2 (2.10) API requires the BeginStep call to be earlier in the column creation/ data writing process.
=> updated AdiosStMan for API update in ADIOS2

mirlib/bug.c, mirlib/dio.c
This is a small PR that prevents compilation issues within the mirlib directory when using gcc 8.5 and several -W options enabled like -Wmissing-declarations . The changes are:
- Defining _XOPEN_SOURCE to get the strdup declaration (man strdup)
- Defining _DEFAULT_SOURCE to get the sys_nerr declaration (man sys_nerr)
- Using I_ISDIR rather than I_IFDIR (https://www.gnu.org/software/libc/manual/html_node/Testing-File-Type.html)
=> mirlib: fix minor compilation issues

CHANGES.md, CMakeLists.txt, docker/py_wheel.docker
When compiling with `oldest_supported_numpy`, the resulting package is incompatible with numpy 2.0. Using the latest numpy should get us numpy 2.0 compatibility.
=> Install newer numpy for python wheels

tables/Dysco/CMakeLists.txt
The tests for Dysco were compiled unconditionally (i.e., irrespective of whether `BUILD_TESTING` was set to `ON` or `OFF`), which triggered an issue on systems with older Boost libraries (<1.72). This has been fixed.
=> Fix Dysco test compilation issue with older Boost versions

CMakeLists.txt
SOFA is only used for testing, so we don't need to look for it when not building testing. This will suppress the warning "SOFA not found" for most users, possibly reducing confusion.
=> Only look for SOFA with testing

msfits/MSFits/FitsIDItoMS.cc
In particular, clear the array name when processing the primary HDU. This makes sure converting multiple FITS-IDI files from different arrays will correctly identify the array and make the appropriate digital corrections for the various array/correlator combinations. Change the warning about conflicting observatory names to SEVERE as this now only applies to conflicting names within a single FITS-IDI file, which would be serious trouble as the wrong digital corrections would probably be applied.  This should not happen in real life.
=> Properly reset class variables in FITS-IDI filler

casa/Logging/LogMessage.cc, casa/Logging/LogOrigin.cc, casa/OS/Time.cc, casa/Quanta/MVAngle.cc, casa/Quanta/MVTime.cc
Due to change of rules in implicit move in C++23, at least with GCC (14) there are a few lines that no longer compiled. This has to do with the move-only class ostringstream, which seem to hide the conversion constructor of String.
The changes are of course backward compatible, so that c++23 is not required.
=> Support compilation with c++23 turned on

CMakeLists.txt, python3/CMakeLists-cmake3.14.txt
Ensure that CasaCore uses the new "LOCATION" strategy for finding Python, which will become the default in the future.
With the old strategy, CasaCore will not build if a system has for example both Python 3.10 and 3.12, while only 3.10 has all required development features.
=> Use new Python find strategy

tables/AlternateMans/BitPacking.h, tables/AlternateMans/RowBasedFile.h, tables/AlternateMans/SimpleColumnarFile.h
This PR merges towards the stokes--storage-manager and is part of several PRs that together will add this stman. The work is split in several PRs to allow easier reviewing.
The tests for these classes are here: https://github.com/casacore/casacore/pull/1381
The idea of the low-level class added in this PR is that it can be reused for further storage managers, like specialized antenna and uvw-column storage managers.
=> Add SimpleColumnarFile class for use in Stokes I stman

tables/AlternateMans/RowBasedFile.h, tables/AlternateMans/StokesIStManColumn.h
This performs two things:
- It adds a check to make sure all correlations have the same boolean values (~flags)
- It returns that boolean to all correlations, instead of returning false for the 2nd and 3rd correlation.
=> Fix and perform boolean Stokes I checking

docker/ubuntu2204_clang.docker, docker/ubuntu2404_gcc.docker, tables/AlternateMans/BufferedColumnarFile.h, tables/AlternateMans/RowBasedFile.h, tables/AlternateMans/SimpleColumnarFile.h, tables/AlternateMans/StokesIStMan.cc, tables/AlternateMans/StokesIStMan.h, tables/AlternateMans/test/CMakeLists.txt, tables/AlternateMans/test/tColumnarFile.cc, tables/AlternateMans/test/tStokesIStMan.cc
These changes add support for opening a read-only file, and make sure that no writing or truncation is performed when no changes are made. This is e.g. important for supporting MS-es as input in e.g. CWL tasks.
It also adds a magic header mark to the Stokes I data column, such that Stokes I, UVW and Antenna cols can be distinguished from each other already from the header. This changes the format of the Stokes I columns, but since it is not used yet, now is the time (and it should be the last change). This makes the Stokes I stman in line with the other compressing storage managers.
A test set is added for the operations done in the Stokes I stman.
Finally there are some fixes to make sure everything remains robust when failures occur. The RO changes showed that e.g. if a close fails but …
=> Various finishing touches for the compressing storage managers

docker/ubuntu2404_gcc.docker, tables/AlternateMans/test/CMakeLists.txt, tables/AlternateMans/test/tColumnarFile.cc
Not all gcc versions in use correctly implement std::filesystem::permissions, so this MR uses boost instead.
=> Fix a compilation issue for some gcc versions

tables/TaQL/TaQLNode.h
Because the destructor of TaQLNode was not virtual, but is used as base class, deleting it through a pointer to base class causes a memory leak. Because TaQLNode has a mutex, it also leaks resources, which at least is somewhat serious.
This was found by the address sanitizer.
=> Fix memory leak in TaQLNode

mainpage.dox
Fixed the hyperlinks in the main page of the documentation. The link to WCSLib was wrong, all links now use https.
=> Fix hyperlinks in documentation

tables/Dysco/aftimeblockencoder.cc
With the default AF normalization, Dysco would set all the data to NaN when the antennas are swapped, i.e. when ANTENNA1 > ANTENNA2. This affects amongst other some of the simulated SKA measurement sets.
=> Fix a bug in Dysco when antenna indices are swapped

tables/AlternateMans/BufferedColumnarFile.h
In boolean (bit-packed) columns, the code confused nr of bytes with nr bits.
=> Fix an out of bounds issue in Stokes I StMan

tables/AlternateMans/UvwFile.h, tables/AlternateMans/test/tUvwFile.cc
When writing a file with only auto-correlations, enabling UVW compression would cause issues. When writing measurement sets with multiple auto-correlations, the UvwFile would never be changed (as there's nothing to write) and therefore the file would never be written. Technically such a file is not supported by the given requirements for UVW compression, as it says:
> Also, it requires the baselines to be ordered such that a relation to the
> reference antenna can be made.
...and that's not the case when there are more than one antennas. However, it's easy to support files with auto-correlations, so that's added in this MR.
A second issue was that if a file has only one auto-correlation and therefore also only one antenna, the nr of rows in the file was not properly calculated. This is …
=> Support UVW compression on sets with only auto-correlations

tables/DataMan/DataManInfo.cc
There's an indexing bug in `DataManInfo::removeDminfoColumns()`, which triggered an error in the test that was added in Dp3 here: https://git.astron.nl/RD/DP3/-/merge_requests/1431 .
The function used the same index for the input and output info structures. However, if dms are removed somewhere in the middle, the output info has fewer elements, so the wrong index is used. This causes this error to be thrown:
```
std exception detected: RecordInterface::define - new fieldNumber exceeds #fields
```
This test compresses a MS with meta-data compression, and then decompresses it. This causes a call to `DataManInfo::removeDminfoColumns()` in which the dm for the antenna columns is not the first dm in the set, which triggered this bug.
=> Fix an indexing bug in DataManInfo::removeDminfoColumns()

mirlib/CMakeLists.txt, mirlib/uvio.c
This fixes #1417. It fixes it from two sides: the incorrect function declarations in the centuries old Miriad code has been fixed, but I've also required the use of C17 for the Miriad code to avoid future nastiness. We already required C++17, but not C17.
=> Require use of C17 to avoid C23 errors from gcc 15

measures/Measures/MCFrame.cc, measures/Measures/MCFrame.h, measures/Measures/MeasFrame.cc
This removes an unnecessary MeasFrame field from MCFrame. Since that field keeps a reference, it makes it hard to reason about thread safety.
It also refactors the MCFrame class; the internal fields are moved to the unit file by using the pimpl pattern. This also allows the use of std::optional instead of (smart) pointers, which avoids manual copying (and saves some allocations).
=> Refactor MCFrame to remove ref to MeasFrame and use pimpl pattern

measures/Measures/MeasFrame.cc, measures/Measures/MeasFrame.h
I did get at some point thread sanitizer errors on the 'reference counter' variable that's used. I'm not entirely sure they were correct, but std::shared_ptr uses an atomic counter by default and therefore solves this issue. It also simplifies the class a lot, making it more obvious what happens ; and makes move construct/assign trivial.
=> Simplify MeasFrame for improving thread-safety and add independentCopy()

docker/py_wheel.docker, docker/ubuntu2004_clang.docker, docker/ubuntu2004_gcc.docker, docker/ubuntu2204_clang.docker, docker/ubuntu2204_gcc.docker, docker/ubuntu2404_clang.docker, docker/ubuntu2404_gcc.docker
The FTP site is currently down, and in the meantime the file has been additionally hosted under this new https URL. See #1427 for details.
=> Download WSRT Measures from https URL

ms/MSOper/MSConcat.cc
When merging FIELD tables, look up the field by name and pass it as a hint to MSFieldColumns::matchDirection() such that the same name is used if the directions match.
Fixes #1432
=> Attempt to preserve field names during concat
